force-app/main/default/objects/Booking_Room_Code__c/Booking_Room_Code__c.object-meta.xml
<CustomObject>
    <label>Booking Room Code</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Code Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings Room codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Code__c/fields/Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Booking_FK__c</fullName>
    <label>Booking FK</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings Room codes</relationshipLabel>
    <relationshipName>Bookings_Room_codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/Booking_Room_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line	 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Room Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Line__c/fields/Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Booking_FK__c</fullName>
    <label>Booking_FK</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Option</relationshipLabel>
    <relationshipName>Bookings_Room_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/ToDelete__c.field-meta.xml
<CustomField>
    <fullName>ToDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ToDelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line_Price__c/Booking_Room_Line_Price__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line Price</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings Room Line Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/classes/AP01_BookingRoomLinePrice_Test.cls
@isTest
private class AP01_BookingRoomLinePrice_Test {
    public static testmethod void DeleteBookingRoomLinePrice_Test(){
        Account newAcc = new Account();
        newAcc = utils.CreatePersonAccount('test Account 1',null);
        insert newAcc;
        Opportunity newMB = new Opportunity();
        newMB = utils.CreateMasterBookingOpportunity('test Master Booking 1',newAcc.id);
        insert newMB;
        Opportunity newB = new Opportunity();
        newB = utils.CreateBookingOpportunity('test Booking 1');
        newB.stageName = label.ClosedWonStage;
        newB.Master_Booking_FK__c = newMB.id;
        insert newB;
        Booking_Room_Line__c newBRL = new Booking_Room_Line__c();
        newBRL = utils.CreateBookingRoomLine(newB.id);
        insert newBRL;
        Booking_Room_Line_Price__c newBRLP = new Booking_Room_Line_Price__c();
        newBRLP = utils.CreateBookingRoomLinePrice(newBRL.id,123);
        insert newBRLP;
        newBRLP.ToDelete__c = true;
        update newBRLP;
        newBRL.ToDelete__c = true;
        update newBRL;
        Booking_room_code__c newBRC = new Booking_room_code__c();
        newBRC.Booking_FK__c = newB.id;
        insert newBRC;
        newBRC.ToDelete__c = true;
        update newBRC;
    }
}