force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Vouchers (Hotel)</relationshipLabel>
    <relationshipName>Vouchers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/OPCO__c.field-meta.xml
<CustomField>
    <fullName>OPCO__c</fullName>
    <description>Filled with the hotel country of the voucher.
Used in voucher sharing rules.</description>
    <label>OPCO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP05_Voucher.cls
/**
* @author TMA-EIL CG
* @date 06/03/2020
* @description Fill the field opco of the object voucher on insert and update CRMSS-474
* @test class : AP05_voucher_test
* @coverage: 100%
*/

public without sharing class AP05_Voucher {
    
    //method to fill th field opco of a voucher on before insert or update
    public static void fillVoucherOpco(list<voucher__c> listNewVouch){
        
        map<string, string> mapVouchIdHotelId = new map<string, string>();//map each voucher with its hotel
        map<string, string> mapHotelIdCountry = new map<string, string>();//map each hotel retrieved with its country
        map<string, string> mapVouchIdHotelCountry = new map<string, string>();//map each voucher with its hotel's country
        
        if(listNewVouch != null && listNewVouch.size()>0){
            
            for(voucher__c vouch : listNewVouch){
                
                //map each voucher with its hotel
                mapVouchIdHotelId.put(vouch.id, vouch.hotel__c);
            }
            
            if(mapVouchIdHotelId != null && mapVouchIdHotelId.size()>0){
                
                //map each retrieved hotel with its country
                for(Hotel__c hot : [select id, Country__c from hotel__c where Id IN: mapVouchIdHotelId.values()]){
                    
                    mapHotelIdCountry.put(hot.Id, hot.Country__c);
                }
                
                if(mapHotelIdCountry != null && mapHotelIdCountry.size()>0){
                    
                    for(string vouchId : mapVouchIdHotelId.keyset()){
                        
                        if(mapHotelIdCountry.containsKey(mapVouchIdHotelId.get(vouchId))){
                            
                            //map each voucher with its hotel's country
                            mapVouchIdHotelCountry.put(vouchId,mapHotelIdCountry.get(mapVouchIdHotelId.get(vouchId)));
                        }
                    }
                    
                    if(mapVouchIdHotelCountry != null && mapVouchIdHotelCountry.size()>0){
                        
                        for(voucher__c vouch : listNewVouch){
                            
                            if(mapVouchIdHotelCountry.containsKey(vouch.Id)){
                                
                                //update the voucher's OPCO field with the corresponding hotel country
                                vouch.OPCO__c = mapVouchIdHotelCountry.get(vouch.Id);
                            }
                        }
                    }
                }
            }
        } 
    }
}