force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_1__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 1)</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_2__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 2)</relationshipLabel>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_3__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 3</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 3)</relationshipLabel>
    <relationshipName>Bookings3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_4__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 4</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 4)</relationshipLabel>
    <relationshipName>Bookings4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_5__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 5</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 5)</relationshipLabel>
    <relationshipName>Bookings5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HotelCountry__c.field-meta.xml
<CustomField>
    <fullName>HotelCountry__c</fullName>
    <formula>TEXT(Hotel__r.Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HotelCountry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/classes/AP01_Hotel.cls
/*
* On insert,update and delete of a Hotel__c record, this trigger will update the fields booking france, booking germany etc..
* the trigger will calculate the percentage of hotel bookings per country and store the calculated values in the person account fields
* @author: Mohamad El Kebbi
* @date: 06/27/2018 
* @ Test: AP05_Opportunity_Test 91%
*/
public without sharing class AP01_Hotel { 
    
    public static void updateBookingsCountryPercentages(List<Hotel__c> listHotels, Map<Id, Hotel__c> mapOldHotels) {
    	
       String actionAdd = 'ADD';
       String actionRemove = 'REMOVE';
        
       Id booking_RT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Label.BookingRecordTypeName).getRecordTypeId();
        
        // Get the hotels with country changed
        Set<Id> setHotelsToTreat = new Set<Id>();
        String country;
        String oldCountry;
        Hotel__c oldHotel;
        for(Hotel__c hotel : listHotels) {
            oldHotel = mapOldHotels.get(hotel.Id);
            country  = hotel.Country__c == null ? '' : hotel.Country__c;
            oldCountry = oldHotel.Country__c == null ? '' : oldHotel.Country__c;
            if(!country.equalsIgnoreCase(oldCountry)) {
               setHotelsToTreat.add(hotel.Id); 
            }    
        }
        if(setHotelsToTreat.size() > 0) { 
            Map<Id, AccountDataHistory> mapGuestIdDataHistory = new Map<Id, AccountDataHistory>();
            String strOldHotelCountry;
            // iterate over all bookings in the hotels to treat
            for(Opportunity booking : [SELECT Id,Hotel__c,Person_Account__c,HotelCountry__c, Guest_Account_1__c,Guest_Account_2__c,Guest_Account_3__c, Guest_Account_4__c, Guest_Account_5__c, StageName
                                       FROM Opportunity
                                       WHERE RecordTypeId = :booking_RT AND Hotel__c IN :setHotelsToTreat 
                                       AND (StageName =: Label.StageBooked OR StageName =: Label.StageChecked)
                                      ]) {
                                           if(booking.Hotel__c != null && booking.HotelCountry__c != null) {
                                               AP05_Opportunity.doCalculateCountryPercentage(booking, mapGuestIdDataHistory, actionAdd, null, new Set<Integer> {1,2,3,4,5});
                                           }
                                           oldHotel = mapOldHotels.get(booking.Hotel__c);
                                           strOldHotelCountry = oldHotel.Country__c;
                                           if(strOldHotelCountry != null) {
                                               AP05_Opportunity.doCalculateCountryPercentage(booking, mapGuestIdDataHistory, actionRemove, strOldHotelCountry, new Set<Integer> {1,2,3,4,5});
                                           }
                                       }
            AP04_Account.doUpdateGuestFields(mapGuestIdDataHistory);
            
        }
    }
    
}