force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Commercial_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Hotel_Name__c</fullName>
    <label>Commercial Hotel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>IR</fullName>
                <label>Iran, Islamic Republic of</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <externalId>true</externalId>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Email_du_client__c.field-meta.xml
<CustomField>
    <fullName>Email_du_client__c</fullName>
    <description>(mandatory). Dans le cas où il n&apos;y a pas d&apos;email, rattacher manuellement à un User générique (avec un email générique).
Dans le cas où le client n&apos;a pas d&apos;adresse email, son nom, prénom et téléphone seront a saisir dans le champ commentaire</description>
    <label>Email du client</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Guest_Account__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Champ lookup vers Guest Account (qui affichera le Prénom+ Nom du client). Si le GA n&apos;existe pas, possibilité de le créer depuis le lookup. Possibilité de chercher le client par nom ou email</description>
    <label>Guest Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.PersonContact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vouchers (Guest Account)</relationshipLabel>
    <relationshipName>Vouchers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Vouchers (Hotel)</relationshipLabel>
    <relationshipName>Vouchers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/recordTypes/IR.recordType-meta.xml
<RecordType>
    <fullName>IR</fullName>
    <active>true</active>
    <description>Invité et Remboursé-C&apos;est pour afficher/masquer les champs à la page de Consultation/Modification des Vouchers</description>
    <label>IR</label>
</RecordType>

force-app/main/default/classes/AP05_Voucher_Test.cls
/*
* Description: Test Class for AP05_Voucher 
* @author: TMA-EI CG
* @date: 10/03/2019
*/

@isTest
public class AP05_Voucher_Test {
    
    @isTest
    public static void fillVoucherOpco(){
        
        Id Voucher_RT_IR_Id = Schema.SObjectType.Voucher__c.getRecordTypeInfosByDeveloperName().get('IR').getRecordTypeId();
        
        Account acc = new Account();
        acc.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        acc.LastName='testAcc';
        insert acc;
        
        list<hotel__c> listHotels = new list<hotel__c>();
        
        hotel__c hotFR = new hotel__c(Commercial_Hotel_Name__c = 'test hotel1', Hotel_ID__c='2343', country__c = 'FR');
        listHotels.add(hotFR);
        
        hotel__c hotIT = new hotel__c(Commercial_Hotel_Name__c = 'test hotel2', Hotel_ID__c='2345', country__c = 'IT');
        listHotels.add(hotIT);
        
        hotel__c hotES = new hotel__c(Commercial_Hotel_Name__c = 'test hotel3', Hotel_ID__c='2346', country__c = 'ES');
        listHotels.add(hotES);
        
        insert listHotels;
        
        list<Voucher__c> listVouch=  new list<Voucher__c>();
        
        Voucher__c vouch1 = new Voucher__c(Guest_Account__c=acc.Id, recordTypeId = Voucher_RT_IR_Id, hotel__c = hotFR.Id, Email_du_client__c='testVouch1@test.com');
        listVouch.add(vouch1);
        
        Voucher__c vouch2 = new Voucher__c(Guest_Account__c=acc.Id, recordTypeId = Voucher_RT_IR_Id, hotel__c = hotIT.Id, Email_du_client__c='testVouch2@test.com');
        listVouch.add(vouch2);
        
        Voucher__c vouch3 = new Voucher__c(Guest_Account__c=acc.Id, recordTypeId = Voucher_RT_IR_Id, hotel__c = hotES.Id, Email_du_client__c='testVouch3@test.com');
        listVouch.add(vouch3);
        
        test.startTest();
        
        insert listVouch;
        
        vouch1.Hotel__c = hotIT.Id;
        update listVouch;
        
        test.stopTest();
    }
}