force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Adress__c.field-meta.xml
<CustomField>
    <fullName>Adress__c</fullName>
    <label>Adress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Commercial_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Hotel_Name__c</fullName>
    <label>Commercial Hotel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/GPS_code__c.field-meta.xml
<CustomField>
    <fullName>GPS_code__c</fullName>
    <label>GPS code</label>
    <scale>3</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/ZIP_code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_code__c</fullName>
    <label>ZIP code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Hotel_Junction__c/Opportunity_Hotel_Junction__c.object-meta.xml
<CustomObject>
    <description>Objetc to link an opportunity to several hotel</description>
    <label>Opportunity_Hotel_Junction</label>
    <nameField>
        <label>Opportunity_Hotel_Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities_Hotels_Junction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Hotel_Junction__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance (Km)</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Hotel_Junction__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities_Hotels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Hotel_Junction__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Hotels</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AP01_Opportunity.cls
/*
* Description: Controller class for opportunity lightning components
* @author: Jenny Jawhar
* @date: 09/08/2017
* @Test class: AP01_Opportunity_Test
* @Lightning Components: LC01_Opportunity / LC01_Opportunity_Body 
*/
public class AP01_Opportunity {    
    //Method called on the initiation and when the value of the filter is chosen
    //on the component LC01_Opportunity_Body to get the list of hotels filtered by country
    @AuraEnabled
    public static List<Hotel__c> getHotels(){       
        return [Select Id, Commercial_Hotel_Name__c 
                From Hotel__c];
    }  
    @AuraEnabled
    public static string getAddressAutoComplete(String input) {
        list<string> listAddresses = new list<string>();
        String url = Label.AutoCompleteSite + EncodingUtil.urlEncode(input, 'UTF-8')
            + '&key='+label.AutoCompleteKey;
        HttpRequest objrequest = new HttpRequest();            
        objrequest.setEndpoint(url);
        objrequest.setMethod('GET');
        HttpResponse objresponse = new HttpResponse(); 
        if(!test.isRunningTest()){
            objresponse = new http().send(objrequest);
        }
        else{
            objresponse.setStatusCode(200);
            objresponse.setStatus(label.StatusComplete);
            objresponse.setBody(label.BodyAutoCompleteAddress);            
        }        
        if(objresponse.getStatusCode() == 200){
            return objresponse.getBody();
        }
        return null;
    }
    @AuraEnabled
    public static string getlocationlatlong(string address)
    {                
        address = address.replaceAll('\\s', '');
        HttpRequest objrequest = new HttpRequest();            
        objrequest.setEndpoint(Label.GeocodeSite+address+'&sensor=false');
        objrequest.setMethod('GET');
        objrequest.setCompressed(false);            
        objrequest.setHeader('Encoding','iso-8859-1');
        objrequest.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        objrequest.setTimeout(120000);//max timeout
        HttpResponse objresponse = new HttpResponse(); 
        if(!test.isRunningTest()){
            objresponse = new http().send(objrequest);
        }
        else{
            objresponse.setStatusCode(200);
            objresponse.setStatus(label.StatusComplete);
            objresponse.setBody(label.BodyLongLat);            
        }
        if(objresponse.getStatusCode() == 200){
            return objresponse.getBody();  
        }
        return null;
    }
    @AuraEnabled
    public static list<Hotel__c> Filter(string latlong){
        list<Hotel__c> listHotel =new list<Hotel__c>();                                  
        if(latlong != null && latlong!=Label.OverQueryLimit && latlong!=Label.ZeroResult){
            string[] split = latlong.split(',');
            decimal lat=decimal.valueOf(split[0]);
            decimal longit=decimal.valueOf(split[1]);            
            list<Hotel__c> listHotelLocation = [SELECT Id, Commercial_Hotel_Name__c,GPS_code__c
                                                FROM Hotel__c 
                                                WHERE DISTANCE(GPS_code__c, GEOLOCATION(:lat,:longit), 'km') < 50
                                                ORDER BY DISTANCE(GPS_code__c, GEOLOCATION(:lat,:longit), 'km')];
            if(listHotelLocation.Size()>0){
                list<Hotel__c> listHotelToUpdate = new list<Hotel__c>();
                for(Hotel__c hotel:listHotelLocation){                    
                    Location searchedLocation = Location.newInstance(lat, longit);
                    decimal distance = Location.getDistance(searchedLocation,hotel.GPS_code__c, 'km');                 
                    hotel.Distance__c = distance.setScale(2);
                    listHotelToUpdate.add(hotel);
                }
                update listHotelToUpdate; 
                listHotel = [SELECT Id, Commercial_Hotel_Name__c,Distance__c
                             From Hotel__c
                             where Id IN: listHotelToUpdate
                             Order By Distance__c];
            }
        }        
        else{
            listHotel= getHotels();
        }   
        return listHotel;              
    }
    //Method to create Opportunity_Hotel_Junction__c depending on the chosen Hotels and create an attachement containing all the infos of the chosen hotels  
    @AuraEnabled
    public static void createHotel(string sfdcId,List<Hotel__c> ListHotel,string address){
        list<Opportunity_Hotel_Junction__c> listJunctionOppHotel = new list<Opportunity_Hotel_Junction__c>();
        for(Hotel__c hotel: listHotel){
            Opportunity_Hotel_Junction__c junctionOppHotel = new Opportunity_Hotel_Junction__c();
            junctionOppHotel.Opportunity__c = sfdcId;
            junctionOppHotel.Hotel__c = hotel.Id;
            junctionOppHotel.Distance__c = hotel.Distance__c;
            junctionOppHotel.Address__c = address;
            listJunctionOppHotel.add(junctionOppHotel);
        }
        insert listJunctionOppHotel;
        
        list<Opportunity_Hotel_Junction__c> listJunction = [Select Opportunity__r.Name, Hotel__r.Commercial_Hotel_Name__c, Address__c, 
                                                            Distance__c,Hotel__r.Adress__c,Hotel__r.Country__c,Hotel__r.City__c,
                                                            Hotel__r.Region__c, Hotel__r.ZIP_code__c
                                                            From Opportunity_Hotel_Junction__c
                                                            Where Id IN: listJunctionOppHotel];
        string csv = label.ExcelHeaderLightning +'\n';
        string oppName;
        for(Opportunity_Hotel_Junction__c oppHotel: listJunction){
            oppName = oppHotel.Opportunity__r.Name;
            csv += '"' + oppName +'","'+ oppHotel.Hotel__r.Commercial_Hotel_Name__c + '","' + oppHotel.Hotel__r.Adress__c +
                + '","' + oppHotel.Hotel__r.Country__c + '","' + oppHotel.Hotel__r.City__c + '","' + oppHotel.Hotel__r.Region__c +
                '","' + oppHotel.Hotel__r.ZIP_code__c + '","' +  oppHotel.Address__c +'","' + oppHotel.Distance__c+'"\n';
        }
        Attachment attachment = new Attachment();
        attachment.Body = Blob.valueOf(csv);
        attachment.Name = label.HotelsDot + oppName + label.DotCSV;
        attachment.ParentId = sfdcId; 
        insert attachment;
    }   
}