force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Master_Booking.recordType-meta.xml
<RecordType>
    <fullName>Master_Booking</fullName>
    <active>true</active>
    <businessProcess>Master booking process</businessProcess>
    <label>Master Booking</label>
</RecordType>

force-app/main/default/classes/Batch_pourcentageBooking_test.cls
@isTest
public class Batch_pourcentageBooking_test {
    @isTest static void testCountryFields() {
        String masterBookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Master_Booking').getRecordTypeId();
        Opportunity masterBook = new Opportunity(Name = 'masterBookingTest', StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today());
        masterBook.Channel__c = 'Apps';
        insert masterBook;
        List<Hotel__c> lstHotels = TestDataFactory.createHotels(5);
        lstHotels[0].Country__c = 'DE'; 
        lstHotels[1].Country__c = 'FR'; 
        lstHotels[2].Country__c = 'ES'; 
        lstHotels[3].Country__c = 'IT'; 
        lstHotels[4].Country__c = 'CA'; 
        insert lstHotels;
        List<Account> lstGuestAccounts = TestDataFactory.createGuestAccounts(5);
        insert lstGuestAccounts;
        List<Opportunity> lstBookings = TestDataFactory.createBusinessBookings(10, lstGuestAccounts);
        lstBookings[0].Hotel__c = lstHotels[0].Id;
        lstBookings[0].person_account__c = lstGuestAccounts[0].Id;
        lstBookings[0].Master_Booking_FK__c = masterBook.id;
        lstBookings[1].Hotel__c = lstHotels[1].Id;
        lstBookings[1].person_account__c = lstGuestAccounts[1].Id;
        lstBookings[1].Master_Booking_FK__c = masterBook.id;
        lstBookings[2].Hotel__c = lstHotels[2].Id;
        lstBookings[2].person_account__c = lstGuestAccounts[2].Id;
        lstBookings[2].Master_Booking_FK__c = masterBook.id;
        lstBookings[3].Hotel__c = lstHotels[3].Id;
        lstBookings[3].person_account__c = lstGuestAccounts[3].Id;
        lstBookings[3].Master_Booking_FK__c = masterBook.id;
        lstBookings[4].Hotel__c = lstHotels[4].Id;
        lstBookings[4].person_account__c = lstGuestAccounts[4].Id;
        lstBookings[4].Master_Booking_FK__c = masterBook.id;
        lstBookings[5].Hotel__c = lstHotels[0].Id;
        lstBookings[5].person_account__c = lstGuestAccounts[0].Id;
        lstBookings[5].Master_Booking_FK__c = masterBook.id;
        lstBookings[6].Hotel__c = lstHotels[1].Id;
        lstBookings[6].person_account__c = lstGuestAccounts[1].Id;
        lstBookings[6].Master_Booking_FK__c = masterBook.id;
        lstBookings[7].Hotel__c = lstHotels[2].Id;
        lstBookings[7].person_account__c = lstGuestAccounts[2].Id;
        lstBookings[7].Master_Booking_FK__c = masterBook.id;
        lstBookings[8].Hotel__c = lstHotels[3].Id;
        lstBookings[8].person_account__c = lstGuestAccounts[3].Id;
        lstBookings[8].Master_Booking_FK__c = masterBook.id;
        lstBookings[9].Hotel__c = lstHotels[4].Id;
        lstBookings[9].person_account__c = lstGuestAccounts[4].Id;
        lstBookings[9].Master_Booking_FK__c = masterBook.id;
        Test.startTest();
        insert lstBookings;

       database.executeBatch(new Batch_pourcentageBooking());
        Test.stopTest();
    }
}