force-app/main/default/objects/Case/fields/Concerned_country__c.field-meta.xml
<CustomField>
    <fullName>Concerned_country__c</fullName>
    <description>Field fills by web to case in the B&amp;B website</description>
    <inlineHelpText>Hotel country location selected by the customer</inlineHelpText>
    <label>Concerned country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BW</fullName>
                <label>Botswana</label>
            </value>
            <value>
                <fullName>BV</fullName>
                <label>Bouvet Island</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Commercial_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Hotel_Name__c</fullName>
    <label>Commercial Hotel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <externalId>true</externalId>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/BypassValidationRule__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP03_Case_Test.cls
/*
* Description: Test Class for AP03_Case 
* @author: TMA-EI Cynthia Geagea
* @date: 03/06/2019
*/

@isTest
public class AP03_Case_Test {
    
    @isTest
    Public Static void AssignCaseToUserTest(){
        
        /*Database.DMLOptions dmo = new Database.DMLOptions();
          dmo.assignmentRuleHeader.useDefaultRule= true;*/
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'systadm', Email='systadm@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='systadm@testorg.com');
        u.BypassValidationRule__c = true;
        insert u;
        
        system.runAs(u){
            
            string deCaseRecordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customers Request / Claim / Feedback (Germany/Austria)').getRecordTypeId();
            string itCaseRecordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customers Request / Claim / Feedback (Italy)').getRecordTypeId();
            string frCaseRecordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customers Request / Claim / Feedback (France)').getRecordTypeId();
            string esCaseRecordtypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Request / Claim / Feedback (Spain/Portugal)').getRecordTypeId();

            
            Hotel__c hotel = Utils.CreateHotel('Hotel');
            hotel.Email__c = 'hotel@asce.com';
            hotel.Country__c = label.FR;
            hotel.Commercial_Hotel_Name__c='testHotel';
            insert hotel;
            
            list<Case> listCaseToInsert = new list<Case>();
            
            Case cas = Utils.CreateCase();
            cas.Origin = 'Web';
            cas.Type = label.Information_request;
            cas.Salesforce_Case_Type__c = 'General request';
            cas.Status = 'Open';
            cas.RecordTypeId = itCaseRecordtypeId;
            cas.Hotel_ID__c = hotel.Hotel_ID__c;
            cas.SuppliedEmail = 'customerTest@asce.com';
            cas.First_Name__c = 'First';
            cas.Last_Name__c = 'Last';
            cas.Concerned_country__c = 'IT';
            //cas.setOptions(dmo);
            listCaseToInsert.add(cas);
            
            Case cas1 = Utils.CreateCase();
            cas1.Origin = 'Web';
            cas1.Type = label.Information_request;
            cas1.Salesforce_Case_Type__c = 'General request';
            cas1.Status = 'Open';
            cas.RecordTypeId = frCaseRecordtypeId;
            cas1.Hotel_ID__c = hotel.Hotel_ID__c;
            
            cas1.SuppliedEmail = 'customerTest1@asce.com';
            cas1.Concerned_country__c = 'FR';
            cas1.First_Name__c = 'First1';
            cas1.Last_Name__c = 'Last1';
            //cas1.setOptions(dmo);
            listCaseToInsert.add(cas1);
            
            Case cas2 = Utils.CreateCase();
            cas2.Origin = 'Web';
            cas2.Status = 'Open';
            cas2.Type = label.Information_request;
            cas2.Salesforce_Case_Type__c = 'General request';
            cas2.SuppliedEmail = 'customerTest2@asce.com';
            cas2.RecordTypeId = esCaseRecordtypeId;
            cas2.Hotel_ID__c = hotel.Hotel_ID__c;
            cas2.First_Name__c = 'First2';
            cas2.Last_Name__c = 'Last2';
            cas2.Concerned_country__c = 'ES';
            //cas2.setOptions(dmo);
            listCaseToInsert.add(cas2);
            
            Case cas3 = Utils.CreateCase();
            cas3.Origin = 'Web';
            cas3.Status = 'Open';
            cas3.Type = label.Information_request;
            cas3.Salesforce_Case_Type__c = 'General request';
            cas3.SuppliedEmail = 'customerTest3@asce.com';
            cas3.RecordTypeId = deCaseRecordtypeId;
            cas3.Hotel_ID__c = hotel.Hotel_ID__c;
            cas3.First_Name__c = 'First3';
            cas3.Last_Name__c = 'Last3';
            cas3.Concerned_country__c = 'AT';
            //cas3.setOptions(dmo);
            listCaseToInsert.add(cas3);
            
            insert listCaseToInsert;
            
            List<Group> queueIds = [Select Id from Group
                                    Where Name = 'Italy Service Agent' or Name = 'French Queue hotel case' or Name = 'Spain Queue Hotel Case' ];
            
            listCaseToInsert[0].OwnerId = queueIds[0].Id;
            listCaseToInsert[1].OwnerId = queueIds[1].Id;
            listCaseToInsert[2].OwnerId = queueIds[2].Id;
            
            update listCaseToInsert;
            
            
        }
    }
    
}