force-app/main/default/objects/Case/fields/Concerned_country__c.field-meta.xml
<CustomField>
    <fullName>Concerned_country__c</fullName>
    <description>Field fills by web to case in the B&amp;B website</description>
    <inlineHelpText>Hotel country location selected by the customer</inlineHelpText>
    <label>Concerned country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BW</fullName>
                <label>Botswana</label>
            </value>
            <value>
                <fullName>BV</fullName>
                <label>Bouvet Island</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email</description>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <externalId>true</externalId>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/classes/AP01_AgentWork_Test.cls
/**
* ********************************************************************************** PS *************************************************************************************************************
* *********************************** Before Runing it, we should connect to omni-channel -> Make the user Online ***********************************************************************************
* ********************************************************************************** End PS ********************************************************************************************************
* @version 1.00 14/03/2019
* @author TMA-EI JK
* @CodeCoverage 
*/
@IsTest
public class AP01_AgentWork_Test {
    @isTest
    public static void test_flagCase(){
        Account PersonAccount1 =  Utils.CreatePersonAccount('Person', null); 
        insert PersonAccount1; 
        
        
        Account PartnerAccount = Utils.CreatePartnerAccount('Partner',null);      
        insert PartnerAccount;
        
        Account PersonAccount = Utils.CreatePersonAccount('Person', PartnerAccount.Id);
        PersonAccount.Email__pc = 'Person@hotmail.com';
        insert PersonAccount;
        
        list<Contact> listContactToInsert = new list<Contact>();  
        Contact cont = Utils.CreateContact('ContactTest',PartnerAccount.Id,'FR');
        cont.Email = 'customer@gmail.com';
        listContactToInsert.add(cont);
        Contact cont1 = Utils.CreateContact('ContactTest1', PartnerAccount.Id, 'FR');
        cont1.Email = 'Person@hotmail.com';
        listContactToInsert.add(cont1);
        insert listContactToInsert;    
        
        //User user1 = new User();
        //user1 = [select ID from user where  id='0050Y0000035GDI' limit 1];
        //system.debug('user1' + user1);
       // System.runAs(user1){
            Hotel__c hotel = Utils.CreateHotel('Hotel 1');
            hotel.Email__c = 'hotel1@gmail.com';
            hotel.Hotel_ID__c = 'test';
            hotel.Country__c = label.FR;
            insert hotel;
            
            list<Case> listCaseToInsert = new list<Case>();
            
            Case cas = Utils.CreateCase();
            cas.Origin = 'Web';
            cas.Type = label.Information_request;
            cas.RecordTypeId = Label.Case_RT_CustomersRequestFeedback;
            cas.Hotel_ID__c = hotel.Hotel_ID__c;
            cas.SuppliedEmail = 'customer1@gmail.com';
            cas.First_Name__c = 'First1';
            cas.Last_Name__c = 'Last1';
            cas.Concerned_country__c = 'IT';
            listCaseToInsert.add(cas);
            
            insert listCaseToInsert;
            ServiceChannel[] SChannel= [SELECT Id,RelatedEntity FROM ServiceChannel Where DeveloperName='Cases' ];
            system.debug('SChannel ' +SChannel);
            ID SChannelId= [SELECT Id FROM ServiceChannel Where DeveloperName='Cases' Limit 1].Id;
            system.debug('SChannelId ' +SChannelId);
            
            
            
            
            
            Schema.SObjectType spType = Schema.getGlobalDescribe().get('ServicePresenceStatus');
            SObject sps = spType.newSObject();
            sps.put('Language', 'en_US');
            sps.put('MasterLabel', 'Available Cases Label');
            sps.put('DeveloperName', 'Available_Cases');
            //  Database.SaveResult sr = Database.insert(sps, true);
            //  insert sps;
               //UserServicePresence USP1 = new UserServicePresence();
                
            
                 //insert USP1;
            
            Schema.SObjectType uspType = Schema.getGlobalDescribe().get('UserServicePresence');
            SObject usp = uspType.newSObject();
            //   usp.put('IsAway', 'false');
            //  usp.put('Name', 'Test User Service Presence');
            //  usp.put('ServicePresenceStatusId', sps.id);
            //  usp.put('StatusStartDate', system.now());
            //    usp.put('UserId', user1.id);
            //      Database.insert(usp, true); 
            //   insert usp;
           
            String user1 = Userinfo.getUserId();
            AgentWork awork = new AgentWork();
            awork.ServiceChannelId = SChannelId;
            awork.UserId = user1;
            awork.WorkItemId = cas.Id;
            insert awork;
        //}
    }
    
  
}