force-app/main/default/objects/Case/recordTypes/Case_linked_to_IR.recordType-meta.xml
<RecordType>
    <fullName>Case_linked_to_IR</fullName>
    <active>true</active>
    <businessProcess>Case process</businessProcess>
    <label>Case linked to IR</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Demande_d_assistance__c.field-meta.xml
<CustomField>
    <fullName>Demande_d_assistance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Au moment de la création de l&apos;IR ce champ n&apos;apparait pas. 
Ce champ se remplira automatiquement à l&apos;enregistrement de l&apos;IR avec le lien du case associé 
(champ lookup vers le case associé créé)</description>
    <label>Demande d&apos;assistance</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Vouchers (Demande d&apos;assistance)</relationshipLabel>
    <relationshipName>Vouchers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Email_du_client__c.field-meta.xml
<CustomField>
    <fullName>Email_du_client__c</fullName>
    <description>(mandatory). Dans le cas où il n&apos;y a pas d&apos;email, rattacher manuellement à un User générique (avec un email générique).
Dans le cas où le client n&apos;a pas d&apos;adresse email, son nom, prénom et téléphone seront a saisir dans le champ commentaire</description>
    <label>Email du client</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Guest_Account__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Champ lookup vers Guest Account (qui affichera le Prénom+ Nom du client). Si le GA n&apos;existe pas, possibilité de le créer depuis le lookup. Possibilité de chercher le client par nom ou email</description>
    <label>Guest Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.PersonContact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vouchers (Guest Account)</relationshipLabel>
    <relationshipName>Vouchers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/recordTypes/IR.recordType-meta.xml
<RecordType>
    <fullName>IR</fullName>
    <active>true</active>
    <description>Invité et Remboursé-C&apos;est pour afficher/masquer les champs à la page de Consultation/Modification des Vouchers</description>
    <label>IR</label>
</RecordType>

force-app/main/default/classes/AP04_Voucher_Test.cls
/*
* Description: Test Class for AP04_Voucher 
* @author: TMA-EI JKA
* @date: 14/10/2019
*/

@isTest
public class AP04_Voucher_Test {
    
    @isTest
    public static void CalculateVoucher(){
        
        Id Voucher_RT_IR_Id = Schema.SObjectType.Voucher__c.getRecordTypeInfosByDeveloperName().get('IR').getRecordTypeId();
        Id Case_RT_Case_linked_to_IR_Id = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Case_linked_to_IR').getRecordTypeId();
        
        Account acc1=new Account();
        acc1.RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        acc1.LastName='test';
        insert acc1;
        
        Case case1 = new Case(Status = 'Open', RecordTypeId=Case_RT_Case_linked_to_IR_Id);
        insert case1;
        
        
        list<Voucher__c> listVouch=  new list<Voucher__c>();
        
        Voucher__c vouch1 = new Voucher__c(Guest_Account__c=acc1.Id, recordTypeId = Voucher_RT_IR_Id,Email_du_client__c='testVouch1@test.com');
        listVouch.add(vouch1);
        
        Voucher__c vouch2 = new Voucher__c( Guest_Account__c=acc1.Id, recordTypeId = Voucher_RT_IR_Id,Email_du_client__c='testVouch2@test.com');
        listVouch.add(vouch2);
        
        Voucher__c vouch3 = new Voucher__c(Guest_Account__c=acc1.Id, recordTypeId = Voucher_RT_IR_Id, Email_du_client__c='testVouch3@test.com');
        listVouch.add(vouch3);
        
        Voucher__c vouch4 = new Voucher__c(Guest_Account__c=acc1.Id, recordTypeId = Voucher_RT_IR_Id,Email_du_client__c='testVouch4@test.com');
        vouch4.Demande_d_assistance__c = case1.Id;
        listVouch.add(vouch4);
        
        test.startTest();
        
        Database.insert(listVouch, false);
        
        vouch2.Demande_d_assistance__c=case1.Id;
        Database.update(listVouch, false);
        
        Database.delete(vouch4, false);
        
        test.stopTest();
        
    }
}