force-app/main/default/objects/Master_Voucher__c/Master_Voucher__c.object-meta.xml
<CustomObject>
    <label>Master Voucher OC</label>
    <nameField>
        <displayFormat>MOC-{00000000}</displayFormat>
        <label>Master Voucher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Vouchers OC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Voucher__c/fields/Dur_e_de_validit__c.field-meta.xml
<CustomField>
    <fullName>Dur_e_de_validit__c</fullName>
    <defaultValue>&apos;2 mois&apos;</defaultValue>
    <label>Durée de validité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6 mois</fullName>
            </value>
            <value>
                <fullName>2 mois</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Nature_de_la_demande__c.field-meta.xml
<CustomField>
    <fullName>Nature_de_la_demande__c</fullName>
    <label>Nature de la demande</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manifestation sportive</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Prospection commerciale</fullName>
            </value>
            <value>
                <fullName>Offre mariage</fullName>
            </value>
            <value>
                <fullName>Réclamation (Réservé SRC)</fullName>
            </value>
            <value>
                <fullName>Prolongation IR-OC (SRC - DR)</fullName>
            </value>
            <value>
                <fullName>Prolongation IR-OC (CRC - DR)</fullName>
                <isActive>false</isActive>
                <label>Prolongation IR-OC (CRC - DR)</label>
            </value>
            <value>
                <fullName>Réclamation (Réservé CRC)</fullName>
                <isActive>false</isActive>
                <label>Réclamation (Réservé CRC)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Nombre_de_copie_s__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_copie_s__c</fullName>
    <label>Nombre de copie(s)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Prestation_Offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_Offerte__c</fullName>
    <label>Prestation Offerte</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Une nuit en chambre 1-2 personnes</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre familiale</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre 1-2 personnes avec petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre familiale avec petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Un petit déjeuner</fullName>
            </value>
            <value>
                <fullName>Deux petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Trois petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Quatre petits déjeuners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Tech_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Tech_CreatedDate__c</fullName>
    <formula>DATEVALUE( CreatedDate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tech_CreatedDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LCC16_DashboardOCList.cls
/*
* Description: Controller class for LC16_DashboardOClist 
* @author: TMA-EI CG
* @date: 22/10/2020
* @Test class: LCC16_DashboardOCList_Test
* @Coverage: 100%
* @Lightning Components: LC16_DashboardOClist
*/

public with sharing class LCC16_DashboardOCList {
    
    @AuraEnabled
    public static ReturnedInfo GetMasterVouchers() {
        
        ReturnedInfo ret = new ReturnedInfo();
        
        ret.listMasterVouch = [select Id, Name, Nature_de_la_demande__c, Prestation_Offerte__c, Dur_e_de_validit__c, Nombre_de_copie_s__c, Tech_CreatedDate__c, CreatedDate 
                               from Master_Voucher__c
                               order by CreatedDate Desc];
        
        return ret;
    }
    
    public class ReturnedInfo{
        
        @AuraEnabled public List<Master_voucher__c> listMasterVouch;
    }
}