force-app/main/default/objects/Master_Voucher__c/Master_Voucher__c.object-meta.xml
<CustomObject>
    <label>Master Voucher OC</label>
    <nameField>
        <displayFormat>MOC-{00000000}</displayFormat>
        <label>Master Voucher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Vouchers OC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Voucher__c/fields/Nature_de_la_demande__c.field-meta.xml
<CustomField>
    <fullName>Nature_de_la_demande__c</fullName>
    <label>Nature de la demande</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manifestation sportive</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Prospection commerciale</fullName>
            </value>
            <value>
                <fullName>Offre mariage</fullName>
            </value>
            <value>
                <fullName>Réclamation (Réservé SRC)</fullName>
            </value>
            <value>
                <fullName>Prolongation IR-OC (SRC - DR)</fullName>
            </value>
            <value>
                <fullName>Prolongation IR-OC (CRC - DR)</fullName>
                <isActive>false</isActive>
                <label>Prolongation IR-OC (CRC - DR)</label>
            </value>
            <value>
                <fullName>Réclamation (Réservé CRC)</fullName>
                <isActive>false</isActive>
                <label>Réclamation (Réservé CRC)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Nom_Pr_nom_client__c.field-meta.xml
<CustomField>
    <fullName>Nom_Pr_nom_client__c</fullName>
    <label>Prénom / Nom client</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Nombre_de_copie_s__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_copie_s__c</fullName>
    <label>Nombre de copie(s)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Offert_l_occasion_de__c.field-meta.xml
<CustomField>
    <fullName>Offert_l_occasion_de__c</fullName>
    <label>Offert à l&apos;occasion de</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/P_riode_de_validit__c.field-meta.xml
<CustomField>
    <fullName>P_riode_de_validit__c</fullName>
    <label>Période de validité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Du lundi au dimanche</fullName>
            </value>
            <value>
                <fullName>Les ven.; sam.;dim. ou fériés</fullName>
                <label>Les ven., sam.,dim. ou fériés</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Personal_account__c.field-meta.xml
<CustomField>
    <fullName>Personal_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Vouchers OC (Personal account)</relationshipLabel>
    <relationshipName>Master_Vouchers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Prestation_Offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_Offerte__c</fullName>
    <label>Prestation Offerte</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Une nuit en chambre 1-2 personnes</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre familiale</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre 1-2 personnes avec petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre familiale avec petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Un petit déjeuner</fullName>
            </value>
            <value>
                <fullName>Deux petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Trois petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Quatre petits déjeuners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/objects/User/fields/BypassValidationRule__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LCC17_DashboardConsultOC_Test.cls
/*
* Description: Test class for LC17_DashboardConsultOC 
* @author: TMA-EI CG
* @date: 26/10/2020
*/

@isTest
public class LCC17_DashboardConsultOC_Test {
    
    @isTest
    public static void GetRelatedVouchersTest(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User testUser = new User(Alias = 'systadm', Email='systadm@testorg.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = p.Id,division = Label.AP01_MasterVoucher_DivisionCorporate, FirstName = 'user',
                                 TimeZoneSidKey='America/Los_Angeles', UserName='systadm@testorg.com');
        // testUser.BypassValidationRule__c = true;
        insert testUser;
        
        system.runAs(testUser){
            
            Id MVcreationId = Schema.SObjectType.Master_Voucher__c.getRecordTypeInfosByDeveloperName().get(Label.MasterVoucher_RT_OnCreation_DevName).getRecordTypeId();
            
            Account PersonAccount =  Utils.CreatePersonAccount('Person', null);    
            PersonAccount.LastName = 'Test';
            PersonAccount.FirstName = 'Test';
            PersonAccount.personemail = 'personaccounttest@asce.com';
            PersonAccount.personmobilephone = '96156848474';
            insert PersonAccount;
            
            
            Master_Voucher__c masterVouch = new Master_Voucher__c();
            masterVouch.recordtypeid = MVcreationId;
            masterVouch.Personal_account__c = PersonAccount.Id;
            masterVouch.Nombre_de_copie_s__c = 10;
            masterVouch.Nom_Pr_nom_client__c = 'testPrenom';
            masterVouch.Offert_l_occasion_de__c = 'testOccasion';
            masterVouch.Prestation_Offerte__c = 'Une nuit en chambre 1-2 personnes';
            masterVouch.Nature_de_la_demande__c = 'Animation';
            masterVouch.P_riode_de_validit__c = 'Du lundi au dimanche';
            
            test.startTest();
            insert masterVouch;
            test.stopTest();
            
            LCC17_DashboardConsultOC.GetRelatedVouchers(masterVouch.ID);
            
        }
    }
    
}