force-app/main/default/objects/Master_Voucher__c/Master_Voucher__c.object-meta.xml
<CustomObject>
    <label>Master Voucher OC</label>
    <nameField>
        <displayFormat>MOC-{00000000}</displayFormat>
        <label>Master Voucher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Vouchers OC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Voucher__c/fields/Nom_Pr_nom_client__c.field-meta.xml
<CustomField>
    <fullName>Nom_Pr_nom_client__c</fullName>
    <label>Prénom / Nom client</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Offert_l_occasion_de__c.field-meta.xml
<CustomField>
    <fullName>Offert_l_occasion_de__c</fullName>
    <label>Offert à l&apos;occasion de</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VFC01_GetRelatedVouchers_Test.cls
@isTest
public class VFC01_GetRelatedVouchers_Test {
    
    @isTest
    public static void getvouchers()
    {
        string rtID = Schema.SObjectType.Master_Voucher__c.getRecordTypeInfosByDeveloperName().get(Label.MasterVoucher_RT_Consultation_DevName).getRecordTypeId();
        Master_Voucher__c masterVouch= new Master_Voucher__c();
        masterVouch.RecordTypeId = rtID ;
        masterVouch.Nom_Pr_nom_client__c = 'testPrenom';
        masterVouch.Offert_l_occasion_de__c = 'testOccasion';
        insert masterVouch;
        
        voucher__c voucherOC = new voucher__c();
        insert voucherOC;
  
        system.Test.startTest();
        VFC01_GetRelatedVouchers controller = new VFC01_GetRelatedVouchers(new ApexPages.StandardController(voucherOC));
        system.Test.stopTest();   
        
        
    }
}