force-app/main/default/objects/Master_Voucher__c/Master_Voucher__c.object-meta.xml
<CustomObject>
    <label>Master Voucher OC</label>
    <nameField>
        <displayFormat>MOC-{00000000}</displayFormat>
        <label>Master Voucher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Vouchers OC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Voucher__c/fields/Date_d_expiration__c.field-meta.xml
<CustomField>
    <fullName>Date_d_expiration__c</fullName>
    <label>Date d&apos;expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Dur_e_de_validit__c.field-meta.xml
<CustomField>
    <fullName>Dur_e_de_validit__c</fullName>
    <defaultValue>&apos;2 mois&apos;</defaultValue>
    <label>Durée de validité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6 mois</fullName>
            </value>
            <value>
                <fullName>2 mois</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Hotel_emetteur__c.field-meta.xml
<CustomField>
    <fullName>Hotel_emetteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filled from dashboard uniquely with the emitting hotel</description>
    <label>Hôtel émetteur</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Master Vouchers OC (Hôtel émetteur)</relationshipLabel>
    <relationshipName>Master_Vouchers_OC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Hotel_Service_Emmetteur__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Service_Emmetteur__c</fullName>
    <description>Filled automatically with the connected user&apos;s division</description>
    <label>Hôtel/Service Emetteur</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Nature_de_la_demande__c.field-meta.xml
<CustomField>
    <fullName>Nature_de_la_demande__c</fullName>
    <label>Nature de la demande</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manifestation sportive</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Prospection commerciale</fullName>
            </value>
            <value>
                <fullName>Offre mariage</fullName>
            </value>
            <value>
                <fullName>Réclamation (Réservé SRC)</fullName>
            </value>
            <value>
                <fullName>Prolongation IR-OC (SRC - DR)</fullName>
            </value>
            <value>
                <fullName>Prolongation IR-OC (CRC - DR)</fullName>
                <isActive>false</isActive>
                <label>Prolongation IR-OC (CRC - DR)</label>
            </value>
            <value>
                <fullName>Réclamation (Réservé CRC)</fullName>
                <isActive>false</isActive>
                <label>Réclamation (Réservé CRC)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Nombre_de_copie_s__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_copie_s__c</fullName>
    <label>Nombre de copie(s)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/P_riode_de_validit__c.field-meta.xml
<CustomField>
    <fullName>P_riode_de_validit__c</fullName>
    <label>Période de validité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Du lundi au dimanche</fullName>
            </value>
            <value>
                <fullName>Les ven.; sam.;dim. ou fériés</fullName>
                <label>Les ven., sam.,dim. ou fériés</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Personal_account__c.field-meta.xml
<CustomField>
    <fullName>Personal_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Vouchers OC (Personal account)</relationshipLabel>
    <relationshipName>Master_Vouchers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Pr_nom_Nom_de_l_m_tteur__c.field-meta.xml
<CustomField>
    <fullName>Pr_nom_Nom_de_l_m_tteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prénom / Nom de l&apos;émetteur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Prestation_Offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_Offerte__c</fullName>
    <label>Prestation Offerte</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Une nuit en chambre 1-2 personnes</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre familiale</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre 1-2 personnes avec petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre familiale avec petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Un petit déjeuner</fullName>
            </value>
            <value>
                <fullName>Deux petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Trois petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Quatre petits déjeuners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Valable_dans_cet_h_tel__c.field-meta.xml
<CustomField>
    <fullName>Valable_dans_cet_h_tel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Valable dans cet hôtel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Hotel__c.Country__c</field>
            <operation>equals</operation>
            <value>France</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipName>Master_Vouchers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Dur_e_de_validit__c.field-meta.xml
<CustomField>
    <fullName>Dur_e_de_validit__c</fullName>
    <label>Durée de validité</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2 mois</fullName>
            </value>
            <value>
                <fullName>6 mois</fullName>
                <default>true</default>
                <label>6 mois</label>
            </value>
            <value>
                <fullName>12 mois</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Email_du_client__c.field-meta.xml
<CustomField>
    <fullName>Email_du_client__c</fullName>
    <description>(mandatory). Dans le cas où il n&apos;y a pas d&apos;email, rattacher manuellement à un User générique (avec un email générique).
Dans le cas où le client n&apos;a pas d&apos;adresse email, son nom, prénom et téléphone seront a saisir dans le champ commentaire</description>
    <label>Email du client</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/expireDate__c.field-meta.xml
<CustomField>
    <fullName>expireDate__c</fullName>
    <label>expireDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Hotel_Validite_France__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Validite_France__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel Validité</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Hotel__c.Country__c</field>
            <operation>equals</operation>
            <value>France</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Invitations France</relationshipLabel>
    <relationshipName>Invitation_France</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Nature_de_la_demande__c.field-meta.xml
<CustomField>
    <fullName>Nature_de_la_demande__c</fullName>
    <label>Nature de la demande</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manifestation sportive</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Prospection commerciale</fullName>
            </value>
            <value>
                <fullName>Offre mariage</fullName>
            </value>
            <value>
                <fullName>Réclamation</fullName>
            </value>
            <value>
                <fullName>Prolongation IR-OC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vouchers</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Prestation_offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_offerte__c</fullName>
    <label>Prestation offerte</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>6000</fullName>
                <label>Une nuit en chambre 1-2 personnes</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>Une nuit en chambre familiale</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>Une nuit en chambre 1-2 personnes avec petits déjeuners</label>
            </value>
            <value>
                <fullName>6003</fullName>
                <label>Une nuit en chambre familiale avec petits déjeuners</label>
            </value>
            <value>
                <fullName>6004</fullName>
                <label>Un petit déjeuner</label>
            </value>
            <value>
                <fullName>6005</fullName>
                <label>Deux petits déjeuners</label>
            </value>
            <value>
                <fullName>6006</fullName>
                <label>Trois petits déjeuners</label>
            </value>
            <value>
                <fullName>6007</fullName>
                <label>Quatre petits déjeuners</label>
            </value>
            <value>
                <fullName>60 euros</fullName>
                <label>Voucher 60 euros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>En attente</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Annulé(e)</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <label>Périmé(e)</label>
            </value>
            <value>
                <fullName>Used</fullName>
                <label>Consommé(e)</label>
            </value>
            <value>
                <fullName>Generated</fullName>
                <label>Emis</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Type_d_invitation__c.field-meta.xml
<CustomField>
    <fullName>Type_d_invitation__c</fullName>
    <label>Type d&apos;invitation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5000</fullName>
                <default>true</default>
                <label>Remboursé et Invité</label>
            </value>
            <value>
                <fullName>Opération commerciale</fullName>
            </value>
            <value>
                <fullName>Voucher BBH CLUB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Validite__c.field-meta.xml
<CustomField>
    <fullName>Validite__c</fullName>
    <description>(read only dès la création, always &quot;Du lundi au dimanche&quot; for IR)</description>
    <label>Validité</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9000</fullName>
                <default>true</default>
                <label>Du lundi au dimanche</label>
            </value>
            <value>
                <fullName>Les vendredis, samedis, dimanches ou jours fériés</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/recordTypes/OC.recordType-meta.xml
<RecordType>
    <fullName>OC</fullName>
    <active>true</active>
    <description>Opération Commerciale-C&apos;est pour afficher/masquer les champs à la page de Consultation/Modification des Vouchers</description>
    <label>OC</label>
</RecordType>

force-app/main/default/classes/AP02_MasterVoucher.cls
/*
* Description: Class to create Voucher OC and fill the code when the master voucher is created on after insert
* @author: TMA JK
* @date: 02/10/2020
* @Test: AP02_MasterVoucher_Test
* @Coverage: 89%
*/
public without sharing class AP02_MasterVoucher {
    
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////Create Voucher OC from Master Voucher //////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    public static void CreateVoucherOCOnInsert(list<Master_Voucher__c> listMasterVoucher){
        
        //Map each Prestation Offertte value selected on the master voucher OC, with the corresponding Nb de nuit and Nb de Pdj on the voucher OC CRMSS-909
        List<Prestation_NbNuit_NbPdj_OC__mdt> listPrestationNbNuitNbPdj = [select Id, Prestation_Offerte__c, Nb_de_nuit__c, Nb_de_Pdj__c from Prestation_NbNuit_NbPdj_OC__mdt];//retrieve all custom metadata mappings
        map<string,double> mapPrestationNbNuit = new map<string,double>();
        map<string,double> mapPrestationNbPdj = new map<string,double>();
        
        //Fill the maps with the corresponding values
        if(listPrestationNbNuitNbPdj != null && listPrestationNbNuitNbPdj.size()>0){
            
            for(Prestation_NbNuit_NbPdj_OC__mdt presta : listPrestationNbNuitNbPdj){
                
                mapPrestationNbNuit.put(presta.Prestation_Offerte__c, presta.Nb_de_nuit__c);
                mapPrestationNbPdj.put(presta.Prestation_Offerte__c, presta.Nb_de_Pdj__c);
            }
        }
        
        List<Voucher__c> listVoucherToBeCreated = new List<Voucher__c>();
        List<Voucher__c> listFailedVoucherToBeCreated = new List<Voucher__c>();
        
        String VoucherOCRT = Schema.SObjectType.Voucher__c.getRecordTypeInfosByName().get('OC').getRecordTypeId();
        
        //Creation of the vouchers according to the number of copies selected on the master voucher OC, and filling them with corresponding data
        for(Master_Voucher__c MasterVoucher : listMasterVoucher){
            
            if(MasterVoucher.Nombre_de_copie_s__c != null ){
                
                for(integer i = 0; i < MasterVoucher.Nombre_de_copie_s__c; i++){
                    
                    Voucher__c VoucherToBeCreated = new Voucher__c();
                    VoucherToBeCreated.RecordTypeId = VoucherOCRT;
                    VoucherToBeCreated.Type_d_invitation__c = Label.AP02_MasterVoucher_OperationCommerciale;
                    VoucherToBeCreated.Master_Voucher_OC__c = MasterVoucher.id;
                    VoucherToBeCreated.Nom_de_l_m_tteur__c = MasterVoucher.Pr_nom_Nom_de_l_m_tteur__c;
                    VoucherToBeCreated.Hotel_emetteur__c = MasterVoucher.Hotel_Service_Emmetteur__c;
                    VoucherToBeCreated.Hotel_Validite_France__c = MasterVoucher.Valable_dans_cet_h_tel__c;
                    VoucherToBeCreated.Dur_e_de_validit__c = MasterVoucher.Dur_e_de_validit__c;
                    VoucherToBeCreated.Validite__c = MasterVoucher.P_riode_de_validit__c;
                    VoucherToBeCreated.expireDate__c = MasterVoucher.Date_d_expiration__c;
                    VoucherToBeCreated.Email_du_client__c = MasterVoucher.Email_client__c;
                    VoucherToBeCreated.Person_Account__c = MasterVoucher.Personal_account__c;
                    VoucherToBeCreated.Nature_de_la_demande__c = MasterVoucher.Nature_de_la_demande__c;
                    VoucherToBeCreated.Statut__c = Label.AP02_MasterVoucher_Status_Generated;
                    VoucherToBeCreated.Valorisation__c = MasterVoucher.Valorisation__c;
                    VoucherToBeCreated.Code_OC__c = generateVoucherOcCode();//Added by TMA-EIT CG CRMSS-870
                    VoucherToBeCreated.Commentaires__c = MasterVoucher.Commentaires__c;//Added by TMA-EIT CG CRMSS-916
                    
                    //CRMSS-909 
                    if(MasterVoucher.Prestation_Offerte__c != null && MasterVoucher.Prestation_Offerte__c != ''){
                        
                        VoucherToBeCreated.Prestation_offerte__c = MasterVoucher.Prestation_Offerte__c;
                        
                        if(mapPrestationNbNuit != null && mapPrestationNbNuit.size()>0 && mapPrestationNbNuit.containsKey(MasterVoucher.Prestation_Offerte__c)){
                            
                            VoucherToBeCreated.Nb_de_nuit_OC__c = mapPrestationNbNuit.get(MasterVoucher.Prestation_Offerte__c);
                        }
                        
                        if(mapPrestationNbPdj != null && mapPrestationNbPdj.size()>0 && mapPrestationNbPdj.containsKey(MasterVoucher.Prestation_Offerte__c)){
                            
                            VoucherToBeCreated.Nb_de_Pdj_OC__c = mapPrestationNbPdj.get(MasterVoucher.Prestation_Offerte__c);
                        }
                        
                    }
                    
                    listVoucherToBeCreated.add(VoucherToBeCreated);
                }
            }
        }
        
        //Added by TMA-EIT CG CRMSS-870
        if(listVoucherToBeCreated != null && listVoucherToBeCreated.size() > 0 ){
            
            Database.UpsertResult[] insertResults = database.upsert(listVoucherToBeCreated, false); //insert the vouchers partially
            
            //do while will execute at least once
            do{system.debug('### cg im in do');
                //clear the list of failed vouchers to fill it properly
                if(listFailedVoucherToBeCreated != null && listFailedVoucherToBeCreated.size()>0){
                    
                    listFailedVoucherToBeCreated.clear();
                }
                system.debug('### cg listFailedVoucherToBeCreated size afetr clear: '+listFailedVoucherToBeCreated.size());
                //loop over the dynamic insert result to retrieve failures and insert them again
                for(integer i = 0; i < insertResults.size(); i++){
                    
                    //catching all failed vouchers on insert
                    if(!insertResults[i].isSuccess()){
                        system.debug('### cg insertResults[i] error: '+insertResults[i].getErrors());
                        listFailedVoucherToBeCreated.add(listVoucherToBeCreated[i]);
                    }
                }
                system.debug('### cg listFailedVoucherToBeCreated filled again: '+listFailedVoucherToBeCreated);
                if(listFailedVoucherToBeCreated.size()>0){
                    
                    for(voucher__c vouch : listFailedVoucherToBeCreated){
                        
                        vouch.Code_OC__c = generateVoucherOcCode();//call the generation function to regenerate unique and random codes for failed vouchers
                    }
                    
                    insertResults = database.upsert(listFailedVoucherToBeCreated, false);//retry inserting the failed vouchers
                }
                
            }while(listFailedVoucherToBeCreated.size()>0);
            
        }
    }
    
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////Generate unique and random Voucher OC Codes //////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /* 
     * @Description: method to generate unique and random Voucher OC codes CRMSS-870
     * @author: TMA-EIT CG 
     * @date: 02/10/2020
     */
    
    public static string generateVoucherOcCode(){
        
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        string resultingCode = '';
        
        while(resultingCode.length() < 10){
            
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            resultingCode += chars.substring(idx, idx+1);
        }
        
        resultingCode = 'OC'+resultingCode;
        return resultingCode;
    }
    
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////Update Email and Account of vouchers when they are updated on the Master voucher OC //////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /* 
     * @Description: method to update Vouchers based on Master Vouchers info CRMSS-825
     * @author: TMA-EIT CG 
     * @date: 02/10/2020
     */
    
    public static void UpdateVoucherOCOnMVUpdate(list<Master_Voucher__c> listMasterVoucher, map<Id,Master_Voucher__c> mapOldMasterVoucher){
        
        List<Voucher__c> listVoucherToUpdate = new List<Voucher__c>(); 
        set<String> setUpdatedMVIds = new set<String>();
        
        for(Master_Voucher__c masterVoucher : listMasterVoucher){
            
            if(masterVoucher.Account_Company__c != mapOldMasterVoucher.get(masterVoucher.Id).Account_Company__c || masterVoucher.Email_client__c != mapOldMasterVoucher.get(masterVoucher.Id).Email_client__c ){
                
                setUpdatedMVIds.add(masterVoucher.Id);
            }
        }
        
        if(setUpdatedMVIds != null && setUpdatedMVIds.size()>0){
            
            listVoucherToUpdate = [select Id ,Email_du_client__c, Account_Company__c, Master_Voucher_OC__r.Email_client__c, Master_Voucher_OC__r.Account_Company__c from voucher__c where Master_Voucher_OC__c in: setUpdatedMVIds];
            
            if(listVoucherToUpdate != null && listVoucherToUpdate.size()>0){
                
                for(Voucher__c vouch : listVoucherToUpdate){
                    
                    vouch.Email_du_client__c = vouch.Master_Voucher_OC__r.Email_client__c;
                    vouch.Account_Company__c = vouch.Master_Voucher_OC__r.Account_Company__c;
                }
                
                update listVoucherToUpdate;
            }
        }
    }
    
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////Update the number of existing vouchers on an Hotel when a new MV OC is created /////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /* 
     * @Description: method to update Hotels remaining Vouchers OC CRMSS-869-951
     * @author: TMA-EIT CG 
     * @date: 19/11/2020
     */ 
    
    public static void fillHotelRemainInvit(list<Master_Voucher__c> listMasterVoucher){
        
        set<Id> setEmitId = new set<Id>();
        list<string> listEmitEmails = new list<string>();
        map<string, list<double>> mapEmitEmailListExistVouchNb = new map<string, list<double>>();
        map<string, double> mapEmitEmailTotalVouchNb = new map<string, double>();
        list<hotel__c> listHotelsToUpdate = new list<Hotel__c>();
        
        for(Master_voucher__c mvouch : listMasterVoucher){
            system.debug('### mvouch.Pr_nom_Nom_de_l_m_tteur__c: '+mvouch.Pr_nom_Nom_de_l_m_tteur__c);
            if(mvouch.Pr_nom_Nom_de_l_m_tteur__c != null){
                
                setEmitId.add(mvouch.Pr_nom_Nom_de_l_m_tteur__c);
            }
        }
        
        if(setEmitId != null && setEmitId.size()>0){
            
            For(user usObj : [select Id, Email from user where Id In:setEmitId]){
                
                listEmitEmails.add(usObj.Email);
            }
            
        }
        system.debug('### listEmitEmails: '+listEmitEmails);
        
        if(listEmitEmails != null && listEmitEmails.size()>0){
            
            list<Master_Voucher__c> listExistingMV = new list<Master_Voucher__c>([Select Id, Pr_nom_Nom_de_l_m_tteur__c, Tech_EmetteurEmail__c , Nombre_de_copie_s__c 
                                                                                  from Master_Voucher__c
                                                                                 where Tech_EmetteurEmail__c  IN: listEmitEmails]);
            system.debug('### listExistingMV: '+listExistingMV);
            system.debug('### listExistingMV size: '+listExistingMV.size());
            if(listExistingMV != null && listExistingMV.size()>0){
                
                for(Master_Voucher__c mvouch : listExistingMV){
                    
                    if(!mapEmitEmailListExistVouchNb.containsKey(mvouch.Tech_EmetteurEmail__c)){
                        
                        list<double> listToPut = new list<double>();
                        listToPut.add(mvouch.Nombre_de_copie_s__c);
                        mapEmitEmailListExistVouchNb.put(mvouch.Tech_EmetteurEmail__c, listToPut);
                    }
                    else{
                        
                        list<double> listToPut = mapEmitEmailListExistVouchNb.get(mvouch.Tech_EmetteurEmail__c);
                        listToPut.add(mvouch.Nombre_de_copie_s__c);
                        mapEmitEmailListExistVouchNb.put(mvouch.Tech_EmetteurEmail__c, listToPut);
                    }
                }
                system.debug('### mapEmitEmailListExistVouchNb: '+mapEmitEmailListExistVouchNb);
                if(mapEmitEmailListExistVouchNb != null && mapEmitEmailListExistVouchNb.size()>0){
                    
                    for(string emailEmit : mapEmitEmailListExistVouchNb.keySet()){
                        
                        double nbExistVouch = 0;
                        
                        if(mapEmitEmailListExistVouchNb.get(emailEmit) != null && mapEmitEmailListExistVouchNb.get(emailEmit).size()>0){
                            
                            for(double nbCopies : mapEmitEmailListExistVouchNb.get(emailEmit)){
                                
                                nbExistVouch = nbExistVouch + nbCopies;
                            }
                        }
                        
                        mapEmitEmailTotalVouchNb.put(emailEmit,nbExistVouch);
                    }
                    system.debug('### mapEmitEmailTotalVouchNb: '+mapEmitEmailTotalVouchNb);
                    if(mapEmitEmailTotalVouchNb != null && mapEmitEmailTotalVouchNb.size()>0){
                        
                        list<Contact_role__c> listMVContactRoles = new list<Contact_role__c>([Select id, Contact__c, contact__r.Email, hotel__c, hotel__r.Invitations_existantes__c
                                                                                  from Contact_role__c
                                                                                  Where contact__r.Email IN: mapEmitEmailTotalVouchNb.keySet()]);
                        
                        system.debug('### listMVContactRoles: '+listMVContactRoles);
                        if(listMVContactRoles != null && listMVContactRoles.size()>0){
                            
                            for(Contact_role__c contRole : listMVContactRoles){
                                
                                Hotel__c hot = new Hotel__c();
                                hot.Id = contRole.hotel__c;
                                hot.Invitations_existantes__c = mapEmitEmailTotalVouchNb.get(contRole.contact__r.Email);
                                system.debug('### mapEmitEmailTotalVouchNb.get(contRole.contact__r.Email): '+mapEmitEmailTotalVouchNb.get(contRole.contact__r.Email));
                                
                                listHotelsToUpdate.add(hot);
                            }
                            system.debug('### listHotelsToUpdate: '+listHotelsToUpdate);
                            if(listHotelsToUpdate != null && listHotelsToUpdate.size()>0){
                                
                                update listHotelsToUpdate;
                            }
                            
                        }
                    }
                }
            }
        }
        
    }
}