force-app/main/default/objects/InvitationValorisation__c/InvitationValorisation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>InvitationValorisation</label>
</CustomObject>

force-app/main/default/objects/InvitationValorisation__c/fields/Prestation_offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_offerte__c</fullName>
    <label>Prestation offerte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvitationValorisation__c/fields/Valorisation__c.field-meta.xml
<CustomField>
    <fullName>Valorisation__c</fullName>
    <label>Valorisation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvitationValorisationmdt__mdt/InvitationValorisationmdt__mdt.object-meta.xml
<CustomObject>
    <label>InvitationValorisation</label>
    <pluralLabel>InvitationValorisations</pluralLabel>
</CustomObject>

force-app/main/default/objects/InvitationValorisationmdt__mdt/fields/Prestation_offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_offerte__c</fullName>
    <label>Prestation offerte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvitationValorisationmdt__mdt/fields/Valorisation__c.field-meta.xml
<CustomField>
    <fullName>Valorisation__c</fullName>
    <label>Valorisation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Guest_Account__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Champ lookup vers Guest Account (qui affichera le Prénom+ Nom du client). Si le GA n&apos;existe pas, possibilité de le créer depuis le lookup. Possibilité de chercher le client par nom ou email</description>
    <label>Guest Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.PersonContact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vouchers (Guest Account)</relationshipLabel>
    <relationshipName>Vouchers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Vouchers (Hotel)</relationshipLabel>
    <relationshipName>Vouchers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Objet__c.field-meta.xml
<CustomField>
    <fullName>Objet__c</fullName>
    <label>Objet</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3000</fullName>
                <label>Annulation client</label>
            </value>
            <value>
                <fullName>3001</fullName>
                <label>Erreur hôtel</label>
            </value>
            <value>
                <fullName>3002</fullName>
                <label>Modification client</label>
            </value>
            <value>
                <fullName>3003</fullName>
                <label>Echec paiement hôtel</label>
            </value>
            <value>
                <fullName>3004</fullName>
                <label>Factures</label>
            </value>
            <value>
                <fullName>3005</fullName>
                <label>Relevé mensuel</label>
            </value>
            <value>
                <fullName>3006</fullName>
                <label>Problème Identification/Internet</label>
            </value>
            <value>
                <fullName>3007</fullName>
                <label>Compliment SRC</label>
            </value>
            <value>
                <fullName>3008</fullName>
                <label>Compliment Accueil</label>
            </value>
            <value>
                <fullName>3009</fullName>
                <label>Compliment Hôtel</label>
            </value>
            <value>
                <fullName>3010</fullName>
                <label>Compliment sur la réponse</label>
            </value>
            <value>
                <fullName>3011</fullName>
                <label>Impayé Eclub</label>
            </value>
            <value>
                <fullName>3012</fullName>
                <label>Divers Avis Clients</label>
            </value>
            <value>
                <fullName>3013</fullName>
                <label>Dédommagement</label>
            </value>
            <value>
                <fullName>3014</fullName>
                <label>Réponse du gérant</label>
            </value>
            <value>
                <fullName>3015</fullName>
                <label>Bug du site</label>
            </value>
            <value>
                <fullName>3016</fullName>
                <label>Débit frauduleux</label>
            </value>
            <value>
                <fullName>3017</fullName>
                <label>Erreur du client</label>
            </value>
            <value>
                <fullName>3018</fullName>
                <label>Annulation/modif pour imprévu</label>
            </value>
            <value>
                <fullName>3019</fullName>
                <label>Conditions de la promo</label>
            </value>
            <value>
                <fullName>3021</fullName>
                <label>accueil</label>
            </value>
            <value>
                <fullName>3022</fullName>
                <label>pas de réservation</label>
            </value>
            <value>
                <fullName>3023</fullName>
                <label>erreur de résa</label>
            </value>
            <value>
                <fullName>3024</fullName>
                <label>erreur de paramétrage</label>
            </value>
            <value>
                <fullName>3025</fullName>
                <label>site web</label>
            </value>
            <value>
                <fullName>3026</fullName>
                <label>Divers récla</label>
            </value>
            <value>
                <fullName>3027</fullName>
                <label>N° surtaxé</label>
            </value>
            <value>
                <fullName>3028</fullName>
                <label>Dde infos résa</label>
            </value>
            <value>
                <fullName>3029</fullName>
                <label>Accueil à l&apos;arrivée</label>
            </value>
            <value>
                <fullName>3030</fullName>
                <label>Localisation/accessibilité/GPS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Prestation_offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_offerte__c</fullName>
    <label>Prestation offerte</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>6000</fullName>
                <label>Une nuit en chambre 1-2 personnes</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>Une nuit en chambre familiale</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>Une nuit en chambre 1-2 personnes avec petits déjeuners</label>
            </value>
            <value>
                <fullName>6003</fullName>
                <label>Une nuit en chambre familiale avec petits déjeuners</label>
            </value>
            <value>
                <fullName>6004</fullName>
                <label>Un petit déjeuner</label>
            </value>
            <value>
                <fullName>6005</fullName>
                <label>Deux petits déjeuners</label>
            </value>
            <value>
                <fullName>6006</fullName>
                <label>Trois petits déjeuners</label>
            </value>
            <value>
                <fullName>6007</fullName>
                <label>Quatre petits déjeuners</label>
            </value>
            <value>
                <fullName>60 euros</fullName>
                <label>Voucher 60 euros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Types__c.field-meta.xml
<CustomField>
    <fullName>Types__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
                <label>Annulation/modification</label>
            </value>
            <value>
                <fullName>2001</fullName>
                <label>Facturation CL</label>
            </value>
            <value>
                <fullName>2002</fullName>
                <label>Problème Identification/Internet</label>
            </value>
            <value>
                <fullName>2003</fullName>
                <label>Compliments</label>
            </value>
            <value>
                <fullName>2004</fullName>
                <label>Compliments Avis Clients</label>
            </value>
            <value>
                <fullName>2005</fullName>
                <label>Recouvrement</label>
            </value>
            <value>
                <fullName>2006</fullName>
                <label>AVIS CLIENTS</label>
            </value>
            <value>
                <fullName>2007</fullName>
                <label>OFFRES PROMOS</label>
            </value>
            <value>
                <fullName>2008</fullName>
                <label>SPECIAL EVENT</label>
            </value>
            <value>
                <fullName>2009</fullName>
                <label>OFFRE NOEL</label>
            </value>
            <value>
                <fullName>2010</fullName>
                <label>OFFRE NOW</label>
            </value>
            <value>
                <fullName>2011</fullName>
                <label>RESERVATION</label>
            </value>
            <value>
                <fullName>2012</fullName>
                <label>ARRIVEE SUR LE SITE</label>
            </value>
            <value>
                <fullName>2013</fullName>
                <label>PARTIES COMMUNES</label>
            </value>
            <value>
                <fullName>2014</fullName>
                <label>LA CHAMBRE ET LA SALLE DE BAIN</label>
            </value>
            <value>
                <fullName>2015</fullName>
                <label>RESTAURATION DISNEY</label>
            </value>
            <value>
                <fullName>2016</fullName>
                <label>LE PETIT DEJEUNER</label>
            </value>
            <value>
                <fullName>2017</fullName>
                <label>FACTURATION</label>
            </value>
            <value>
                <fullName>2018</fullName>
                <label>DOMMAGES /SINISTRES</label>
            </value>
            <value>
                <fullName>2019</fullName>
                <label>RBT</label>
            </value>
            <value>
                <fullName>2020</fullName>
                <label>CLUB</label>
            </value>
            <value>
                <fullName>2021</fullName>
                <label>Signalement client</label>
            </value>
            <value>
                <fullName>2022</fullName>
                <label>Signalement hôtelier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Valorisation__c.field-meta.xml
<CustomField>
    <fullName>Valorisation__c</fullName>
    <label>Valorisation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Voucher__c/recordTypes/IR.recordType-meta.xml
<RecordType>
    <fullName>IR</fullName>
    <active>true</active>
    <description>Invité et Remboursé-C&apos;est pour afficher/masquer les champs à la page de Consultation/Modification des Vouchers</description>
    <label>IR</label>
</RecordType>

force-app/main/default/classes/AP01_Voucher_Test.cls
/**
* 
* @version 1.00 14/03/2019
* @author TMA-EI JK
* @CodeCoverage 
*/
@isTest
public class AP01_Voucher_Test {
    
    //added by TMA EIL CRMSS-469 24-02-2020 Start
    @testVisible static List<InvitationValorisationmdt__mdt> customMetadata {    
        
        get {
            if ( customMetadata == null )
                customMetadata = [select Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, Prestation_offerte__c, Valorisation__c from InvitationValorisationmdt__mdt]; 
            return customMetadata;
            
        } set;
    }
    //added by TMA EIL CRMSS-469 24-02-2020 end
    
    public static testMethod void FillInvitationInformationOnCreation_Test()
    {
        //Insert PA
        Account PersonAccount =  Utils.CreatePersonAccount('Person', null);                      
        insert PersonAccount;
                
        
        //Insert Custom settings Data
        //added by TMA EIL CRMSS-469 24-02-2020 Start
        /*
        InvitationValorisation__c IV = new InvitationValorisation__c();
        IV.name = 'Un petit déjeuner';
        IV.Prestation_offerte__c = 'Un petit déjeuner';
        IV.Valorisation__c = 123;
        insert IV;
        */
        //added by TMA EIL CRMSS-469 24-02-2020 end
                
        //Create Hotel
        Hotel__c hotel = Utils.CreateHotel('789');
        insert hotel;        
        
        //Insert an IR invitation
        Voucher__c voucher = new Voucher__c();
        voucher.RecordTypeId = Schema.SObjectType.Voucher__c.getRecordTypeInfosByName().get(Label.Voucher_IR_RT_OnCreation_Name).getRecordTypeId();
        Voucher.Guest_Account__c = PersonAccount.id;
        voucher.Types__c = '2003';
        voucher.Objet__c = '3007';
        voucher.Motif__c = '4014';
        voucher.Prestation_offerte__c = 'Un petit déjeuner';
        voucher.Email_du_client__c = 'test@email.com';
        voucher.Service__c = 'Hotel';
        voucher.Hotel__c = hotel.id;
        voucher.Guest_Account__c = Label.Account_CompteGenericID;
        insert voucher;
        
        voucher.Statut__c = 'Generated';
        update voucher;
        
        voucher.RecordTypeId = Schema.SObjectType.Voucher__c.getRecordTypeInfosByName().get(Label.Voucher_OC_RT_OnCreation_Name).getRecordTypeId();
        voucher.Service__c = 'Build';
        update voucher;
        
        voucher.RecordTypeId = Schema.SObjectType.Voucher__c.getRecordTypeInfosByName().get(Label.Voucher_Eclub_RT_OnCreation_Name).getRecordTypeId();
        update voucher;
                        
        /*voucher.Statut__c = 'Cancelled';
        update voucher;
        
        voucher.Statut__c = 'Expired';
        update voucher;
        
        voucher.Statut__c = 'Used';
        update voucher;*/
        
    }
}