force-app/main/default/objects/Booking_Room_Line__c/Booking_Room_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line	 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Room Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Line_Price__c/Booking_Room_Line_Price__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line Price</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings Room Line Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel_Room_Option__c/Hotel_Room_Option__c.object-meta.xml
<CustomObject>
    <label>Hotel Room Code &amp; Option</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Hotel Room &amp; Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels Rooms &amp; Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/Stay__c/Stay__c.object-meta.xml
<CustomObject>
    <description>Junction object between booking and Person account (Account object)</description>
    <label>Stay</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Stay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Utils_Test.cls
/**
* 
* @version 1.00 22/09/2017
* @author Jenny Jawhar
* @CodeCoverage 100%
*/
@isTest
public class Utils_Test {
  static testmethod void testUtils() {
      Account Partner = Utils.CreatePartnerAccount('Partner1','456');
      insert Partner;
      Contact con = Utils.CreateContact('Contact', Partner.Id, label.EN);
      insert con;
      Account Person = Utils.CreatePersonAccount('Person1',Partner.Id);
      insert Person;
      Opportunity MasterBooking = Utils.CreateMasterBookingOpportunity('MasterBooking1', Person.Id);
      MasterBooking.StageName = label.ClosedWonStage;
      insert MasterBooking;
      Opportunity Booking = Utils.CreateBookingOpportunity('Booking1');
      Booking.Master_Booking_fk__c = MasterBooking.Id;
      Booking.StageName = label.ClosedWonStage;
      insert Booking;
      //Stay__c stay = Utils.CreateStay(Person.Id,Booking.Id);
      //insert stay;
      Booking_Room_Line__c roomLine = Utils.CreateBookingRoomLine(Booking.Id);
      insert roomLine;
      //Booking_Room_Line_Price__c roomPrice = Utils.CreateBookingRoomLinePrice(roomLine.Id, 100);
      //insert roomPrice;
      Contract contract = Utils.CreateContract();
      contract.AccountId = Partner.Id;
      insert contract;
      Hotel__c hotel = Utils.CreateHotel('123');
      insert hotel;
      Case cas = Utils.CreateCase();
      insert cas;
      //Hotel_Room_Option__c hotelRoomOptionAndCode = Utils.CreateHotelRoomOptionAndCode();
      //insert hotelRoomOptionAndCode;
      Product2 prod = Utils.CreateProduct();
      prod.Name = 'prod1';
      insert prod;
      Messaging.SingleEmailMessage SEM = Utils.CreateSingleEmailMessage(null,null,null,null,label.WebCaseEnglishEmailTemplateId,'jennyjawhar@hotmail.com');
      
    }
}