force-app/main/default/objects/Booking_Room_Line__c/Booking_Room_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line	 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Room Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Line__c/fields/Obsolete__c.field-meta.xml
<CustomField>
    <fullName>Obsolete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obsolete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/classes/Batch_DeleteBookingRoomLineObsolete_Test.cls
/*
* Test Class for Batch_DeleteBookingRoomLineObsolete
* @author: Bachir Asmar
* @date: 11/04/2019
* @Coverage:  ??? %
* @Description: By Setting the 
*/
@isTest
public class Batch_DeleteBookingRoomLineObsolete_Test 
{
	
    @isTest
    public static void TestDeleteObsolete() 
    {
        
        Date createdDate = Date.today().addDays(-2);
        
        Account personAccount = Utils.CreatePersonAccount('Person 1', null);
        insert personAccount;
        

        Opportunity bookingOpportunity = Utils.CreateBookingOpportunity('todelete');
        bookingOpportunity.StageName = label.ClosedWonStage;
        bookingOpportunity.createdDate = createdDate;
        insert bookingOpportunity;
        //Test.setCreatedDate(bookingOpportunity.Id, createdDate);


        Booking_Room_Line__c bookingRoomLine = Utils.CreateBookingRoomLine(bookingOpportunity.Id);
        bookingRoomLine.Obsolete__c = True;
        bookingRoomLine.createdDate = createdDate;
        insert bookingRoomLine; 
        //Test.setCreatedDate(bookingRoomLine.Id, createdDate);
        
        Batch_DeleteBookingRoomLineObsolete deleteBRLObsolete = new Batch_DeleteBookingRoomLineObsolete();
        Database.executeBatch(deleteBRLObsolete);
            
    }
}