force-app/main/default/objects/Booking_Room_Line__c/Booking_Room_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line	 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Room Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Line__c/fields/Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Booking_FK__c</fullName>
    <label>Booking_FK</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Option</relationshipLabel>
    <relationshipName>Bookings_Room_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Room_code__c.field-meta.xml
<CustomField>
    <fullName>Room_code__c</fullName>
    <label>Room code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/Hotel_Room_Option__c.object-meta.xml
<CustomObject>
    <label>Hotel Room Code &amp; Option</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Hotel Room &amp; Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels Rooms &amp; Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel_Room_Option__c/fields/Room_Code__c.field-meta.xml
<CustomField>
    <fullName>Room_Code__c</fullName>
    <label>Room Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/fields/Room_Code_Label__c.field-meta.xml
<CustomField>
    <fullName>Room_Code_Label__c</fullName>
    <label>Room Code Label</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/fields/Room_Type_Label__c.field-meta.xml
<CustomField>
    <fullName>Room_Type_Label__c</fullName>
    <label>Room Type Label</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/fields/Type_code__c.field-meta.xml
<CustomField>
    <fullName>Type_code__c</fullName>
    <label>Type code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Room</fullName>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP01_Hotel_Room_Option.cls
/*
* Update Booking Room Line that are related to the updated or deleted Hotel_Room_Option
* @author: Jenny Jawhar
* @date: 05/01/2018
* @Test: AP01_Hotel_Room_Option_Test
*/
public without sharing class AP01_Hotel_Room_Option 
{
    /*Commented by TMA-EIL CG CRMSS-448 23/01/2020 Start
    public static void updateBookingRoomLine(list<Hotel_Room_Option__c> triggerNew, list<Hotel_Room_Option__c> triggerOld,map<Id,Hotel_Room_Option__c> oldMap)
    {
        list<string> listRoomCode = new list<string>();
        if(triggerNew != null)
        {
            for(Hotel_Room_Option__c hotelRoomOption: triggerNew)
            {
                Hotel_Room_Option__c oldHotelRoomOption=oldMap==null ? hotelRoomOption : oldMap.get(hotelRoomOption.Id);
                if(oldMap == null || hotelRoomOption.Room_code__c != oldHotelRoomOption.Room_Code__c || hotelRoomOption.Type_code__c != oldHotelRoomOption.Type_code__c
                   || hotelRoomOption.Room_Code_Label__c != oldHotelRoomOption.Room_Code_Label__c || hotelRoomOption.Room_Type__c != oldHotelRoomOption.Room_Type__c
                   || hotelRoomOption.Room_Type_Label__c != oldHotelRoomOption.Room_Type_Label__c)
                {
                    if(!string.IsBlank(hotelRoomOption.Room_Code__c))
                    {
                        listRoomCode.add(hotelRoomOption.Room_Code__c); 
                    }
                    if(!string.IsBlank(oldHotelRoomOption.Room_Code__c))
                    {
                        listRoomCode.add(oldHotelRoomOption.Room_Code__c);
                    }
                }
            }
        }
        else
        {
            for(Hotel_Room_Option__c hotelRoomOption: triggerOld)
            {
                if(!string.IsBlank(hotelRoomOption.Room_Code__c))
                {
                    listRoomCode.add(hotelRoomOption.Room_Code__c); 
                }
            }
        }
        if(listRoomCode.size() > 0)
        {
            list<Booking_Room_Line__c> listBookingRoomLine = [Select Id, Booking_FK__c
                                                              From Booking_Room_Line__c
                                                              Where Room_code__c IN: listRoomCode];
            set<Id> setBookingId = new set<Id>();
            list<Booking_Room_Line__c> listBookingRoomLineToUpdate = new list<Booking_Room_Line__c>();
            for(Booking_Room_Line__c bookingRoomLine: listBookingRoomLine)
            {
                if(!setBookingId.Contains(bookingRoomLine.Booking_FK__c))
                {
                    setBookingId.add(bookingRoomLine.Booking_FK__c);
                    listBookingRoomLineToUpdate.add(bookingRoomLine);
                }
            }
            update listBookingRoomLineToUpdate;
        }
    }
    Commented by TMA-EIL CG CRMSS-448 23/01/2020 Start */
}