force-app/main/default/objects/Booking_Room_Line__c/Booking_Room_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line	 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Room Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Line__c/fields/Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Booking_FK__c</fullName>
    <label>Booking_FK</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Option</relationshipLabel>
    <relationshipName>Bookings_Room_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Room_code__c.field-meta.xml
<CustomField>
    <fullName>Room_code__c</fullName>
    <label>Room code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BookingLinesCustomSettings__c/BookingLinesCustomSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>BookingLinesCustomSettings</label>
</CustomObject>

force-app/main/default/objects/BookingLinesCustomSettings__c/fields/Breakfast_Room_Code__c.field-meta.xml
<CustomField>
    <fullName>Breakfast_Room_Code__c</fullName>
    <label>Breakfast Room Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BookingLinesCustomSettings__c/fields/ChamreRoomCode__c.field-meta.xml
<CustomField>
    <fullName>ChamreRoomCode__c</fullName>
    <label>Chamre Room Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BookingLinesCustomSettingsmdt__mdt/BookingLinesCustomSettingsmdt__mdt.object-meta.xml
<CustomObject>
    <label>BookingLinesCustomSettings</label>
    <pluralLabel>BookingLinesCustomSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/BookingLinesCustomSettingsmdt__mdt/fields/Breakfast_Room_Code__c.field-meta.xml
<CustomField>
    <fullName>Breakfast_Room_Code__c</fullName>
    <label>Breakfast Room Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BookingLinesCustomSettingsmdt__mdt/fields/Chamre_Room_Code__c.field-meta.xml
<CustomField>
    <fullName>Chamre_Room_Code__c</fullName>
    <label>Chamre Room Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Breakfasts__c.field-meta.xml
<CustomField>
    <fullName>Breakfasts__c</fullName>
    <label>#Breakfasts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/classes/AP02_BookingRoomLine_Test.cls
/*
* Description: Test class for AP02_BookingRoomLine
* @author: TMA-EIL Cynthia Geagea
* @date: 29/11/2019
* @coverage : 77%
*/


@isTest
public class AP02_BookingRoomLine_Test {
     //added by TMA EIL CRMSS-469 24-02-2020 Start
    @testVisible static List<BookingLinesCustomSettingsmdt__mdt> customMetadata {    
        
    get {
        if ( customMetadata == null )
            customMetadata = [select Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, Breakfast_Room_Code__c, Chamre_Room_Code__c from BookingLinesCustomSettingsmdt__mdt]; 
        return customMetadata;
        
    } set;
    }
    //added by TMA EIL CRMSS-469 24-02-2020 end
    
    
    @isTest
    static void updateBooking(){	
        
        //Insert Booking
        Account Partner = Utils.CreatePartnerAccount('Partner1','456');
        insert Partner;
        
        Contact con = Utils.CreateContact('Contact', Partner.Id, label.EN);
        insert con;
        
        Account Person = Utils.CreatePersonAccount('Person1',Partner.Id);
        insert Person;
        
        Account Person2 = Utils.CreatePersonAccount('Person2',Partner.Id);
        insert Person2;
        
        Opportunity MasterBooking = Utils.CreateMasterBookingOpportunity('MasterBooking1', Person.Id);
        MasterBooking.StageName = label.ClosedWonStage;
        insert MasterBooking;
        
        Opportunity MasterBooking2 = Utils.CreateMasterBookingOpportunity('MasterBooking2', Person2.Id);
        MasterBooking.StageName = label.ClosedWonStage;
        insert MasterBooking2;
        
        List<Opportunity> bookings = new List<Opportunity> ();
        list<Opportunity> listBookings = new list<Opportunity>();
        
        Opportunity book1 = new Opportunity(Name = 'Booking1', CloseDate = date.today(), StageName = 'Cancelled', Breakfasts__c = 0, RecordTypeId = Label.BookingRecordTypeId, Master_Booking_FK__c = MasterBooking.id);
        listBookings.add(book1);
        
        Opportunity book2 = new Opportunity(Name = 'Booking2', CloseDate = date.today(),  StageName = label.ClosedWonStage, Breakfasts__c = 3, RecordTypeId = Label.BookingRecordTypeId, Master_Booking_FK__c = MasterBooking2.id);
        listBookings.add(book2);
        
        insert listBookings;

        
        List<Booking_Room_Line__c> bookingRoomLines = new List<Booking_Room_Line__c> ();
        
        Booking_Room_Line__c roomLine = Utils.CreateBookingRoomLine(book1.Id);
        Booking_Room_Line__c roomLine2 = Utils.CreateBookingRoomLine(book2.Id);
        Booking_Room_Line__c roomLine3 = Utils.CreateBookingRoomLine(book2.Id);
        
        roomLine.Quantity__c = 3;
        roomLine.Room_code__c = 'BREAKFAST';
        roomLine2.Quantity__c = 4;
        roomLine2.Room_code__c = 'F112'; 
        roomLine3.Quantity__c = 0;
        roomLine3.Room_code__c = 'F112'; 
        
        bookingRoomLines.add(roomLine);  
        bookingRoomLines.add(roomLine2); 
        bookingRoomLines.add(roomLine3); 
        //added by TMA EIL CRMSS-469 24-02-2020 Start
        /*
        BookingLinesCustomSettings__c broomCode= new BookingLinesCustomSettings__c(name = 'BREAKFAST',Breakfast_Room_Code__c='BREAKFAST');
        insert broomCode;
        BookingLinesCustomSettings__c chambreCode1= new BookingLinesCustomSettings__c(name = 'F112T',ChamreRoomCode__c='F112T');
        insert chambreCode1;
        BookingLinesCustomSettings__c chambreCode= new BookingLinesCustomSettings__c(name = 'F112',ChamreRoomCode__c='F112');
        insert chambreCode;
        
        BookingLinesCustomSettings__c broomCode1= new BookingLinesCustomSettings__c(name = 'BKF-ECLUB',Breakfast_Room_Code__c='BKF-ECLUB');
        insert broomCode1;
        */
        //added by TMA EIL CRMSS-469 24-02-2020 end
        Test.startTest();
        
        insert bookingRoomLines;
        roomLine.Quantity__c = 4;
        roomLine.Room_code__c='BKF-ECLUB';
        roomLine2.Room_code__c='F112T';
        roomLine.Booking_FK__c = book2.Id;
        roomLine2.Booking_FK__c = book1.Id;
        roomLine3.Quantity__c = 3;
        update bookingRoomLines;
        roomLine2.Booking_FK__c = book2.Id;
        update bookingRoomLines;
        book2.Master_Booking_fk__c = MasterBooking.Id;
        update listBookings;
        delete bookingRoomLines;
        Test.stopTest();
        
    }
    
}