force-app/main/default/objects/Booking_Room_Line__c/Booking_Room_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line	 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Room Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Line__c/fields/Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Booking_FK__c</fullName>
    <label>Booking_FK</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Option</relationshipLabel>
    <relationshipName>Bookings_Room_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Booking_Room_Line_Parent__c.field-meta.xml
<CustomField>
    <fullName>Booking_Room_Line_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link between an option in a Booking Room line and a room type in a booking room line</description>
    <label>Booking Room Line Parent</label>
    <referenceTo>Booking_Room_Line__c</referenceTo>
    <relationshipLabel>Bookings Room Line</relationshipLabel>
    <relationshipName>Bookings_Room_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/BookingSource__c.field-meta.xml
<CustomField>
    <fullName>BookingSource__c</fullName>
    <label>BookingSource</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/BuinessLead__c.field-meta.xml
<CustomField>
    <fullName>BuinessLead__c</fullName>
    <label>BuinessLead</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/ChannelCategory__c.field-meta.xml
<CustomField>
    <fullName>ChannelCategory__c</fullName>
    <label>ChannelCategory</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/CheckInDate__c.field-meta.xml
<CustomField>
    <fullName>CheckInDate__c</fullName>
    <label>CheckInDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/CheckoutDate__c.field-meta.xml
<CustomField>
    <fullName>CheckoutDate__c</fullName>
    <label>CheckoutDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Children_ages__c.field-meta.xml
<CustomField>
    <fullName>Children_ages__c</fullName>
    <label>Children ages</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Count_Promotion_Night__c.field-meta.xml
<CustomField>
    <fullName>Count_Promotion_Night__c</fullName>
    <label>Count Promotion Night</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <label>Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/DistributionMode__c.field-meta.xml
<CustomField>
    <fullName>DistributionMode__c</fullName>
    <label>DistributionMode</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Externalid__c.field-meta.xml
<CustomField>
    <fullName>Externalid__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Externalid</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Hotel_Room_Code_Option__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Room_Code_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link between Booking Room line and Hotel Room Code &amp; option</description>
    <label>Hotel Room Code &amp; Option</label>
    <referenceTo>Hotel_Room_Option__c</referenceTo>
    <relationshipLabel>Bookings Room Line</relationshipLabel>
    <relationshipName>Bookings_Room_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Is_Rate_Included__c.field-meta.xml
<CustomField>
    <fullName>Is_Rate_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rate Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Number_of_adults__c.field-meta.xml
<CustomField>
    <fullName>Number_of_adults__c</fullName>
    <label>Number of adults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Number_of_children__c.field-meta.xml
<CustomField>
    <fullName>Number_of_children__c</fullName>
    <label>Number of children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Obsolete__c.field-meta.xml
<CustomField>
    <fullName>Obsolete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obsolete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/PMS_Article_Code__c.field-meta.xml
<CustomField>
    <fullName>PMS_Article_Code__c</fullName>
    <label>PMS Article Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/PMS_Line_ID__c.field-meta.xml
<CustomField>
    <fullName>PMS_Line_ID__c</fullName>
    <label>PMS Line ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Price_Euros__c.field-meta.xml
<CustomField>
    <fullName>Price_Euros__c</fullName>
    <label>Price €</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Promotion_Code__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Code__c</fullName>
    <label>Promotion Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Room_code__c.field-meta.xml
<CustomField>
    <fullName>Room_code__c</fullName>
    <label>Room code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Stay_Price__c.field-meta.xml
<CustomField>
    <fullName>Stay_Price__c</fullName>
    <label>Stay Price</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/TVA_Rate_and_Price__c.field-meta.xml
<CustomField>
    <fullName>TVA_Rate_and_Price__c</fullName>
    <label>TVA Rate and Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BookingSource__c.field-meta.xml
<CustomField>
    <fullName>BookingSource__c</fullName>
    <label>BookingSource</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ChannelCategory__c.field-meta.xml
<CustomField>
    <fullName>ChannelCategory__c</fullName>
    <label>ChannelCategory</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CheckInDate__c.field-meta.xml
<CustomField>
    <fullName>CheckInDate__c</fullName>
    <label>CheckInDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CheckOutDate__c.field-meta.xml
<CustomField>
    <fullName>CheckOutDate__c</fullName>
    <label>CheckOutDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DistributionMode__c.field-meta.xml
<CustomField>
    <fullName>DistributionMode__c</fullName>
    <label>DistributionMode</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Externalid__c.field-meta.xml
<CustomField>
    <fullName>Externalid__c</fullName>
    <externalId>true</externalId>
    <label>Externalid</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <summarizedField>Booking_Room_Line__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Booking_Room_Line__c.Booking_FK__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/classes/BookingRoomLine.cls
global without sharing class BookingRoomLine {
    
    webservice String ExternalId;
    webservice Date Arrival;
    webservice String Booking;
    webservice String RoomLineParent;
    webservice String BookingSource;
    webservice String BusinessLead;
    webservice String ChannelCategory;
    webservice DateTime CheckInDate;
    webservice Date CheckOutDate;
    webservice String ChildrenAges;
    webservice Integer CountPromotionNight;
    webservice Date Departure;
    webservice String DistributionMode;
    webservice String HotelRoomCodeOption;
    webservice boolean IsRateIncluded;
    webservice Integer NumberOfAdults;
    webservice Integer NumberOfChildren;
    webservice String PMSArticleCode;
    webservice String PMSLineId;
    webservice double Price;
    webservice double PriceEuro;
    webservice String PromotionCode;
    webservice Integer Quantity;
    webservice String RoomCode;
    webservice double StayPrice;
    webservice double TVARateAndPrice;
    webservice String FieldsToNull;
    webservice boolean Obsolete;
    
    public Booking_Room_Line__c mapSFFields() {
        Booking_Room_Line__c bookingRoomLine = new Booking_Room_Line__c();
        Set<String> setFieldsToNull = new Set<String>();
        if(String.isNotBlank(FieldsToNull)) {
            for(String field : FieldsToNull.split(',')) {
                setFieldsToNull.add(field);
            }
        }
        
        if(String.isNotBlank(ExternalId) || setFieldsToNull.contains('ExternalId')) {
            bookingRoomLine.ExternalId__c = ExternalId;
        }
        if(Arrival != null || setFieldsToNull.contains('Arrival')) {
            bookingRoomLine.Arrival__c = Arrival;
        }
        if(String.isNotBlank(Booking) || setFieldsToNull.contains('Booking')) {
            if(Booking != null) {
                Opportunity bookingObj = new Opportunity(ExternalId__c = Booking);
                bookingRoomLine.Booking_FK__r = bookingObj;
            } else if(setFieldsToNull.contains('Booking')) {
                bookingRoomLine.Booking_FK__c = null;
            }
            
        }
        if(String.isNotBlank(RoomLineParent) || setFieldsToNull.contains('RoomLineParent')) {
            //bookingRoomLine.Booking_Room_Line_Parent__c = RoomLineParent; Removed by TMA-EI - JK - CRMSS - 173
            //Added by TMA-JK - CRMSS-173 Start
            if(String.isNotBlank(RoomLineParent)) {
                Booking_Room_Line__c bookingRLObj = new Booking_Room_Line__c(ExternalId__c = RoomLineParent);
                bookingRoomLine.Booking_Room_Line_Parent__r = bookingRLObj;    
            } else if(setFieldsToNull.contains('RoomLineParent')) {
                bookingRoomLine.Booking_Room_Line_Parent__c = null;
            }
            //Added by TMA-JK - CRMSS-173 End
        }
         if(Obsolete != null || setFieldsToNull.contains('Obsolete')) {
            bookingRoomLine.Obsolete__c = Obsolete;
        }
        if(String.isNotBlank(BookingSource) || setFieldsToNull.contains('BookingSource')) {
            bookingRoomLine.BookingSource__c = BookingSource;
        }
        if(String.isNotBlank(BusinessLead) || setFieldsToNull.contains('BusinessLead')) {
            bookingRoomLine.BuinessLead__c = BusinessLead;
        }
        if(String.isNotBlank(ChannelCategory) || setFieldsToNull.contains('ChannelCategory')) {
            bookingRoomLine.ChannelCategory__c = ChannelCategory;
        }
        if(CheckInDate != null || setFieldsToNull.contains('CheckInDate')) {
            bookingRoomLine.CheckInDate__c = CheckInDate;
        }
        if(CheckOutDate != null || setFieldsToNull.contains('CheckOutDate')) {
            bookingRoomLine.CheckoutDate__c = CheckOutDate;
        }
        if(String.isNotBlank(ChildrenAges) || setFieldsToNull.contains('ChildrenAges')) {
            bookingRoomLine.Children_ages__c = ChildrenAges;
        }
        if(CountPromotionNight != null || setFieldsToNull.contains('CountPromotionNight')) {
            bookingRoomLine.Count_Promotion_Night__c = CountPromotionNight;
        }
        if(Departure != null || setFieldsToNull.contains('Departure')) {
            bookingRoomLine.Departure__c = Departure;
        }
        if(String.isNotBlank(DistributionMode) || setFieldsToNull.contains('DistributionMode')) {
            bookingRoomLine.DistributionMode__c = DistributionMode;
        }
        
        /*Commented by TMA-EIL CG CRMSS-448 23/01/2020 Start
        if(String.isNotBlank(HotelRoomCodeOption) || setFieldsToNull.contains('HotelRoomCodeOption')) {
            bookingRoomLine.Hotel_Room_Code_Option__c = HotelRoomCodeOption;
        }
        Commented by TMA-EIL CG CRMSS-448 23/01/2020 End*/
        
        if(IsRateIncluded != null || setFieldsToNull.contains('IsRateIncluded')) {
            bookingRoomLine.Is_Rate_Included__c = IsRateIncluded;
        }
        if(NumberOfAdults != null || setFieldsToNull.contains('NumberOfAdults')) {
            bookingRoomLine.Number_of_adults__c = NumberOfAdults;
        }
        if(NumberOfChildren != null || setFieldsToNull.contains('NumberOfChildren')) {
            bookingRoomLine.Number_of_children__c = NumberOfChildren;
        }
        if(String.isNotBlank(PMSArticleCode) || setFieldsToNull.contains('PMSArticleCode')) {
            bookingRoomLine.PMS_Article_Code__c = PMSArticleCode;
        }
        if(String.isNotBlank(PMSLineId) || setFieldsToNull.contains('PMSLineId')) {
            bookingRoomLine.PMS_Line_ID__c = PMSLineId;
        }
        if(Price != null || setFieldsToNull.contains('Price')) {
            bookingRoomLine.Price__c = Price;
        }
        if(PriceEuro != null || setFieldsToNull.contains('PriceEuro')) {
            bookingRoomLine.Price_Euros__c = PriceEuro;
        }
        if(String.isNotBlank(PromotionCode) || setFieldsToNull.contains('PromotionCode')) {
            bookingRoomLine.Promotion_Code__c = PromotionCode;
        }
        if(Quantity != null || setFieldsToNull.contains('Quantity')) {
            bookingRoomLine.Quantity__c = Quantity;
        }
        if(String.isNotBlank(RoomCode) || setFieldsToNull.contains('RoomCode')) {
            bookingRoomLine.Room_code__c = RoomCode;
        }
        if(StayPrice != null || setFieldsToNull.contains('StayPrice')) {
            bookingRoomLine.Stay_Price__c = StayPrice;
        }
        if(TVARateAndPrice != null || setFieldsToNull.contains('TVARateAndPrice')) {
            bookingRoomLine.TVA_Rate_and_Price__c = TVARateAndPrice;
        }
        return bookingRoomLine;
    }
    
}