force-app/main/default/objects/Booking_Room_Line__c/Booking_Room_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line	 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Room Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Line__c/fields/Room_code__c.field-meta.xml
<CustomField>
    <fullName>Room_code__c</fullName>
    <label>Room code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/Hotel_Room_Option__c.object-meta.xml
<CustomObject>
    <label>Hotel Room Code &amp; Option</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Hotel Room &amp; Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels Rooms &amp; Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel_Room_Option__c/fields/Room_Code__c.field-meta.xml
<CustomField>
    <fullName>Room_Code__c</fullName>
    <label>Room Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/fields/Room_Code_Label__c.field-meta.xml
<CustomField>
    <fullName>Room_Code_Label__c</fullName>
    <label>Room Code Label</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/fields/Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Room_Type__c</fullName>
    <label>Room Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/fields/Room_Type_Label__c.field-meta.xml
<CustomField>
    <fullName>Room_Type_Label__c</fullName>
    <label>Room Type Label</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/fields/Type_code__c.field-meta.xml
<CustomField>
    <fullName>Type_code__c</fullName>
    <label>Type code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Room</fullName>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/objects/Stay__c/Stay__c.object-meta.xml
<CustomObject>
    <description>Junction object between booking and Person account (Account object)</description>
    <label>Stay</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Stay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AP01_Hotel_Room_Option_Test.cls
/**
* 
* @version 1.00 05/01/2018
* @author Jenny Jawhar
* @CodeCoverage 100%
*/
@isTest
public class AP01_Hotel_Room_Option_Test 
{
    public static testMethod void updateDeleteInsertHotelRoomOption()
    {
        //insert Hotel_Room_Option__c
        list<Hotel_Room_Option__c> listHotelRoomOptionAndCode = new list<Hotel_Room_Option__c>();
        Hotel_Room_Option__c hotelRoomOptionAndCode;
        for(integer i = 0; i < 2; i++)
        {
            hotelRoomOptionAndCode = Utils.CreateHotelRoomOptionAndCode();
            hotelRoomOptionAndCode.Type_code__c = label.TypeCodeRoom;
            hotelRoomOptionAndCode.Room_code__c = 'R'+ i;
            hotelRoomOptionAndCode.Room_Type__c = 'RT' + i;
            hotelRoomOptionAndCode.Room_Type_Label__c = label.TypeCodeRoom + i;
            listHotelRoomOptionAndCode.add(hotelRoomOptionAndCode);
        }
        for(integer i = 0; i < 5; i++)
        {
            hotelRoomOptionAndCode = Utils.CreateHotelRoomOptionAndCode();
            hotelRoomOptionAndCode.Type_code__c = label.TypeCodeOption;
            hotelRoomOptionAndCode.Room_code__c = 'O'+ i;
            hotelRoomOptionAndCode.Room_Code_Label__c = label.TypeCodeOption + i;
            listHotelRoomOptionAndCode.add(hotelRoomOptionAndCode);
        }
        insert listHotelRoomOptionAndCode;
        //insert Account      
        Account PersonAccount =  Utils.CreatePersonAccount('Person', null);                      
        insert PersonAccount;
        
        Opportunity opp = Utils.CreateBookingOpportunity('Booking');                 
        opp.StageName=Label.StatusChecked; 
        insert opp;
        
        list<Booking_Room_Line__c> listBRL = new list<Booking_Room_Line__c>();
        Booking_Room_Line__c BRL;
        for(integer i = 0; i < 3; i++)
        {
            BRL = Utils.CreateBookingRoomLine(opp.Id);
            BRL.Room_code__c = 'R'+ 0;
            listBRL.add(BRL);
        }  
        for(integer i = 0; i < 2; i++)
        {
            BRL = Utils.CreateBookingRoomLine(opp.Id);
            BRL.Room_code__c = 'R'+ 1;
            listBRL.add(BRL);
        } 
        for(integer i = 0; i < 3; i++)
        {
            BRL = Utils.CreateBookingRoomLine(opp.Id);
            BRL.Room_code__c = 'O'+ 0;
            listBRL.add(BRL);
        } 
        for(integer i = 0; i < 2; i++)
        {
            BRL = Utils.CreateBookingRoomLine(opp.Id);
            BRL.Room_code__c = 'O'+ 1;
            listBRL.add(BRL);
        }         
        BRL = Utils.CreateBookingRoomLine(opp.Id);
        BRL.Room_code__c = 'Unknown';
        listBRL.add(BRL);
        insert listBRL;
        
        //Stay__c stay = Utils.CreateStay(PersonAccount.Id,opp.Id);
        //test.startTest();
        //insert stay;
        
        Hotel_Room_Option__c hotelRoomOption = [Select Id,Room_code__c
                                                From Hotel_Room_Option__c
                                                Where Room_code__c = 'R0'];
        hotelRoomOption.Room_Type__c = 'RT01';
        update hotelRoomOption;
        Account acc = [Select Id,Favorite_Room_type__pc
                       From Account
                       Where Id =: PersonAccount.Id];
        //system.assertEquals('RT01',acc.Favorite_Room_type__pc);
        delete (hotelRoomOption);
        acc = [Select Id,Favorite_Room_type__pc
               From Account
               Where Id =: PersonAccount.Id];
        //system.assertEquals(label.UnknownProduct,acc.Favorite_Room_type__pc);
    }
}