force-app/main/default/objects/Booking_Room_Line__c/Booking_Room_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line	 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Room Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Line__c/fields/ToDelete__c.field-meta.xml
<CustomField>
    <fullName>ToDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ToDelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP01_BookingRoomLine.cls
/*

* @!#  Ticket - 49 REDMINE 1537  Classe to delete Booking Room Line if the field todelete__c is true

* @author: TMA-EI JK

* @date: 31/05/2018

* @test: AP01_BookingRoomLinePrice_Test

*/
public class AP01_BookingRoomLine {
    public static void DeleteBookingRoomLine(List<Booking_Room_Line__c> listBRL){
        List<Booking_Room_Line__c> listBRLToDelete = new List<Booking_Room_Line__c>();
        for(Booking_Room_Line__c objtBRL : listBRL){
            if(objtBRL.ToDelete__c){
                Booking_Room_Line__c objBRLTempl = new Booking_Room_Line__c();
                objBRLTempl.id = objtBRL.id;
                listBRLToDelete.add(objBRLTempl);
            }
        }
        if(listBRLToDelete != null && listBRLToDelete.size() > 0){
            delete listBRLToDelete;
        }
    }
}