force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Case/fields/Concerned_country__c.field-meta.xml
<CustomField>
    <fullName>Concerned_country__c</fullName>
    <description>Field fills by web to case in the B&amp;B website</description>
    <inlineHelpText>Hotel country location selected by the customer</inlineHelpText>
    <label>Concerned country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BW</fullName>
                <label>Botswana</label>
            </value>
            <value>
                <fullName>BV</fullName>
                <label>Bouvet Island</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
            <value>
                <fullName>PT</fullName>
                <label>Portugal</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email</description>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
            <value>
                <fullName>PT</fullName>
                <label>Portugal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <externalId>true</externalId>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/classes/AP01_Case_Test.cls
/**
* 
* @version 1.00 17/10/2017
* @author Jenny Jawhar
* @CodeCoverage 96%
*/
@isTest
public class AP01_Case_Test 
{
    static testMethod void InsertWebCase()
    {
        String compRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();
        
        /*Account PartnerAccount = Utils.CreatePartnerAccount('Partner',null);    
        PartnerAccount.RecordTypeId = compRecordTypeId;
        insert PartnerAccount;
        
        Account PersonAccount = Utils.CreatePersonAccount('Person', PartnerAccount.Id);
        PersonAccount.Email__pc = 'Person@hotmail.com';
        insert PersonAccount;

        list<Contact> listContactToInsert = new list<Contact>();  
        Contact cont = Utils.CreateContact('ContactTest',PartnerAccount.Id,'FR');
        cont.Email = 'customer@gmail.com';
        listContactToInsert.add(cont);
        Contact cont1 = Utils.CreateContact('ContactTest1', PartnerAccount.Id, 'FR');
        cont1.Email = 'Person@hotmail.com';
        listContactToInsert.add(cont1);
        insert listContactToInsert; */       
        
        Hotel__c hotel = Utils.CreateHotel('Hotel 1');
        hotel.Email__c = 'hotel1@gmail.com';
        hotel.Country__c = Label.AP01_Case_CA;//label.FR;
        insert hotel;
        
         Hotel__c hotel1 = Utils.CreateHotel('Hotel 1');
        hotel1.Email__c = 'hotel1@gmail.com';
        hotel1.Hotel_ID__c = '123456';
        hotel1.Country__c = Label.DE;//label.FR;
        insert hotel1;
        
         Hotel__c hotel2 = Utils.CreateHotel('Hotel 1');
        hotel2.Email__c = 'hotel1@gmail.com';
        hotel2.Country__c = Label.FR;//label.FR;
        hotel2.Hotel_ID__c = '1234567';
        insert hotel2;
        
         Hotel__c hotel3 = Utils.CreateHotel('Hotel 1');
        hotel3.Email__c = 'hotel1@gmail.com';
        hotel3.Country__c = Label.AP01_Case_ES;//label.FR;
        hotel3.Hotel_ID__c = '1234568';
        insert hotel3;
        
         Hotel__c hotel4 = Utils.CreateHotel('Hotel 1');
        hotel4.Email__c = 'hotel1@gmail.com';
        hotel4.Country__c = Label.IT;//label.FR;
        hotel4.Hotel_ID__c = '1234569';
        insert hotel4;
        
        list<Case> listCaseToInsert = new list<Case>();
        
        Case cas = Utils.CreateCase();
        cas.Origin = 'Web';
        cas.Type = label.Information_request;
        cas.RecordTypeId = Label.Case_RT_CustomersRequestFeedback;
        cas.Hotel_ID__c = hotel.Hotel_ID__c;
        cas.SuppliedEmail = 'customer1@gmail.com';
        cas.First_Name__c = 'First1';
        cas.Last_Name__c = 'Last1';
        cas.Concerned_country__c = 'IT';
        listCaseToInsert.add(cas);
        
        Case cas1 = Utils.CreateCase();
        cas1.Origin = 'Web';
        cas1.Type = label.Information_request;
        cas.RecordTypeId = Label.Case_RT_CustomersRequestFeedback;
        cas1.Hotel_ID__c = hotel1.Hotel_ID__c;
        cas1.SuppliedEmail = 'customer@gmail.com';
        cas1.Concerned_country__c = 'FR';
        cas1.First_Name__c = 'First2';
        cas1.Last_Name__c = 'Last2';
        listCaseToInsert.add(cas1);
        
        Case cas2 = Utils.CreateCase();
        cas2.Origin = 'Web';
        cas2.SuppliedEmail = 'Person@hotmail.com';//'Person2@hotmail.com';
        cas.RecordTypeId = Label.Case_RT_CustomersRequestFeedback;
        cas1.Hotel_ID__c = hotel2.Hotel_ID__c;
        cas2.First_Name__c = 'First3';
        cas2.Last_Name__c = 'Last3';
        cas2.Concerned_country__c = 'ES';
        listCaseToInsert.add(cas2); 
        
        Case cas3 = Utils.CreateCase();
        cas3.Origin = 'Web';
        cas3.SuppliedEmail = 'Personn@hotmail.com';//'Person2@hotmail.com';
        cas3.RecordTypeId = Label.Case_RT_CustomersRequestFeedback;
        cas3.Hotel_ID__c = hotel3.Hotel_ID__c;
        cas3.First_Name__c = 'First3';
        cas3.Last_Name__c = 'Last3';
        cas3.Concerned_country__c = 'ES';
        listCaseToInsert.add(cas3); 
        
        Case cas4 = Utils.CreateCase();
        cas4.Origin = 'Web';
        cas4.SuppliedEmail = 'Personnn@hotmail.com';//'Person2@hotmail.com';
        cas4.RecordTypeId = Label.Case_RT_CustomersRequestFeedback;
        cas4.Hotel_ID__c = hotel4.Hotel_ID__c;
        cas4.First_Name__c = 'First3';
        cas4.Last_Name__c = 'Last3';
        cas4.Concerned_country__c = 'ES';
        listCaseToInsert.add(cas4); 
        
        Case cas5 = Utils.CreateCase();
        cas5.Origin = 'Web';
        cas5.SuppliedEmail = 'Personnn2@hotmail.com';//'Person2@hotmail.com';
        cas5.RecordTypeId = Label.Case_RT_CustomersRequestFeedback_ES_PT;
        cas5.Hotel_ID__c = hotel4.Hotel_ID__c;
        cas5.First_Name__c = 'First3';
        cas5.Last_Name__c = 'Last3';
        cas5.Concerned_country__c = 'PT';
        cas5.type = 'Information request';
        cas5.Description = 'testing';
        listCaseToInsert.add(cas5); 
        
        insert listCaseToInsert;
        
        list<Contact> listCon = [Select Id
                                 From Contact
                                 Where Email =: cas1.SuppliedEmail];
        //system.assertEquals(2, listCon.size());
        Case updatedCase = [Select Hotel__c 
                            From Case
                            Where Id =: cas.Id];
        //system.assertEquals(hotel.Id,updatedCase.Hotel__c);
    }
}