force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Corporate_Code__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Code__c</fullName>
    <label>Corporate Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Carte_Log_e.recordType-meta.xml
<RecordType>
    <fullName>Carte_Log_e</fullName>
    <active>true</active>
    <description>Record type for loge card</description>
    <label>Carte Logée</label>
</RecordType>

force-app/main/default/objects/Contract/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <description>Record type for corporate opportunity</description>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <businessProcess>Business Process</businessProcess>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/User/fields/BypassApex__c.field-meta.xml
<CustomField>
    <fullName>BypassApex__c</fullName>
    <label>BypassApex</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TriggerHandlerName</fullName>
            </value>
            <value>
                <fullName>UtilsMethodeForAccount</fullName>
            </value>
            <value>
                <fullName>AP02_Contract</fullName>
            </value>
            <value>
                <fullName>AP01_Hotel</fullName>
            </value>
            <value>
                <fullName>AP01_SObject</fullName>
            </value>
            <value>
                <fullName>AP04_Account</fullName>
            </value>
            <value>
                <fullName>Account_Handler</fullName>
            </value>
            <value>
                <fullName>AP05_Account</fullName>
            </value>
            <value>
                <fullName>AP01_Account</fullName>
            </value>
            <value>
                <fullName>AP07_Account</fullName>
            </value>
            <value>
                <fullName>AP06_Account</fullName>
            </value>
            <value>
                <fullName>Ap01_Contact</fullName>
            </value>
            <value>
                <fullName>AP01_Case</fullName>
            </value>
            <value>
                <fullName>AP02_Case</fullName>
            </value>
            <value>
                <fullName>AP03_Case</fullName>
            </value>
            <value>
                <fullName>AP01_BookingRoomLine</fullName>
            </value>
            <value>
                <fullName>AP01_Voucher</fullName>
            </value>
            <value>
                <fullName>AP04_Voucher</fullName>
            </value>
            <value>
                <fullName>AP03_voucher</fullName>
            </value>
            <value>
                <fullName>AP08_Opportunity</fullName>
            </value>
            <value>
                <fullName>OpportunityHandler</fullName>
            </value>
            <value>
                <fullName>AP05_Opportunity</fullName>
            </value>
            <value>
                <fullName>AP03_Opportunity</fullName>
            </value>
            <value>
                <fullName>AP04_Opportunity</fullName>
            </value>
            <value>
                <fullName>AP17_Opportunity</fullName>
            </value>
            <value>
                <fullName>AP014_Opportunity</fullName>
            </value>
            <value>
                <fullName>AP02_Opportunity</fullName>
            </value>
            <value>
                <fullName>AP06_Opportunity</fullName>
            </value>
            <value>
                <fullName>BookingRoomLine_Handler</fullName>
            </value>
            <value>
                <fullName>AP05_Voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/BypassValidationRule__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/BypassWorkflow__c.field-meta.xml
<CustomField>
    <fullName>BypassWorkflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_Contract_StatusUpdate_Test.cls
/*
* Description: Test class for Batch_Contract_StatusUpdate
* @author: TMA Cynthia Geagea
* @date: 31/10/2019
*/

@isTest
public class Batch_Contract_StatusUpdate_Test {
    
    @isTest
    static void batchContractStatusUpdateTest(){
        
        Profile prof = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User userTest = new User(Alias = 'systadm', Email='systadm@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = prof.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='systadm@testorg.com');
        userTest.BypassValidationRule__c = true;
     //   u.BypassApex__c = true;
        userTest.BypassWorkflow__c = true;
        insert userTest;
       date TodayDate = date.today();
        system.debug('@@@@@ test TODAY '+TodayDate);
        System.runAs(userTest){

            Id CompanyAccountRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Company').getRecordTypeId();system.debug('### cg CompanyAccountRTId'+CompanyAccountRTId);
            Id CarteLogeRTId = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Carte_Log_e').getRecordTypeId();system.debug('### cg CarteLogeRTId'+CarteLogeRTId);
            Id CorporateRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Corporate').getRecordTypeId();
             Id CorporateRTI2 = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Corporate').getRecordTypeId();
            
            Account acc = new Account(Name = 'TestAccount', RecordTypeId = CompanyAccountRTId, BillingCountry = 'Algeria', BillingPostalCode='1');
            insert acc;
            system.debug('#### accc'+acc);
            Opportunity opp = new Opportunity(Name = 'TestOpportunity',RecordTypeId = CorporateRTId, AccountId = acc.id, StageName = 'Booked', CloseDate = date.valueOf('2019-08-25'));
            insert opp;
            system.debug('#### opp.account'+opp.account);
            List<Contract> listContracts = new List<Contract>();
            
            For(Integer i = 0; i<100; i++){
                
                Contract cont = Utils.CreateContract();
                cont.RecordTypeId = CorporateRTI2;
                cont.StartDate = TodayDate.addMonths(-3);
                cont.StartDate = cont.StartDate.adddays(+1);
                cont.Status = 'Draft';
                cont.ContractTerm = 5;
                cont.name = 'dbfbf'+ i;
                //cont.enddate = TodayDate.addMonths(-5);
                cont.AccountId = acc.Id;
                cont.Opportunity__c = opp.Id;
                cont.Corporate_Code__c = '1242r'+i;
                system.debug('### jka AccountId'+cont.AccountId);
                system.debug('@@@@@ test Expiration_Date__c '+cont.enddate);
                system.debug('@@@@@ test22222 TODAY '+TodayDate.addMonths(2));
                listContracts.add(cont);
            }
            
        
            
            insert listContracts;
            
            Test.startTest();
            Batch_Contract_StatusUpdate batchObj = new Batch_Contract_StatusUpdate();
            DataBase.executeBatch(batchObj);
            Test.stopTest();
        }
    }

}