force-app/main/default/objects/Data_Clean_Logs__c/Data_Clean_Logs__c.object-meta.xml
<CustomObject>
    <label>Data Clean Logs</label>
    <nameField>
        <label>Data Clean Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Clean Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_Departure__c.field-meta.xml
<CustomField>
    <fullName>Max_Departure__c</fullName>
    <label>Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/classes/Batch01_CleanDataHistory_Test.cls
/*
* Test Class for Batch01_CleanDataHistory
* @author: Georges Hobeika
* @date: 04/01/2019
* @Coverage: 100%
*/
@isTest
public class Batch01_CleanDataHistory_Test {

    @testSetup static void setup() {
        Integer dataCleanFromMonth = Integer.valueOf(Label.DataCleanFromMonth);
        Date createdDate = Date.today().addMonths(-5);
        
        Account personAccount = Utils.CreatePersonAccount('Person 1', null);
        insert personAccount;
        
        Opportunity masterBookingOpportunity = Utils.CreateMasterBookingOpportunity('Master Booking', personAccount.Id);
        insert masterBookingOpportunity;
        Test.setCreatedDate(masterBookingOpportunity.Id, createdDate);
        
        Opportunity bookingOpportunity = Utils.CreateBookingOpportunity('todelete');
        bookingOpportunity.Master_Booking_FK__c = masterBookingOpportunity.Id;
        bookingOpportunity.StageName = label.ClosedWonStage;
        bookingOpportunity.Max_Departure__c = date.today().addmonths(-dataCleanFromMonth);
        bookingOpportunity.Max_Departure__c = bookingOpportunity.Max_Departure__c.addmonths(-1);
        insert bookingOpportunity;
        Test.setCreatedDate(bookingOpportunity.Id, createdDate);
    }
    
    
    @isTest static void testCleanData() {
        Test.startTest();
        Database.executeBatch(new Batch01_CleanDataHistory(), 200);
        Test.stopTest();
        List<Data_Clean_Logs__c> listInsertedLogs = [SELECT Id FROM Data_Clean_Logs__c];
       // System.assertEquals(1, listInsertedLogs.size());
    }
}