force-app/main/default/objects/Data_Clean_Logs__c/Data_Clean_Logs__c.object-meta.xml
<CustomObject>
    <label>Data Clean Logs</label>
    <nameField>
        <label>Data Clean Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Clean Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Clean_Logs__c/fields/JobName__c.field-meta.xml
<CustomField>
    <fullName>JobName__c</fullName>
    <label>JobName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_Departure__c.field-meta.xml
<CustomField>
    <fullName>Max_Departure__c</fullName>
    <label>Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/classes/Batch01_CleanDataHistory.cls
/*
* @author: Georges Hobeika
* This batch is used to delete data from the environment. The new architecture is to keep bookings for maximum 4 months.
  A label is created to define the number of the months from which we need to delete data.
  The records that are deleted in this class are : Master Booking - Booking - Booking Room Line (Booking Room Line has a detail relation with Booking, will be deleted automatically)
  The scenario that a booking room line that is attached to a new booking (through update) is not taken into consideration. To do so a new batch should be created.
  The field Max_Departure__c to be used by the Test team instead of System CreationDate
* @date: 03/01/2019
* @Test: Batch01_CleanDataHistory_Test

*/
global without sharing class Batch01_CleanDataHistory implements Database.Batchable<sObject>{
    
    String masterBookingRT = Label.MasterBookingRTDevName;
    String bookingRT = Label.BookingRecordTypeName;
    Integer dataCleanFromMonth = Integer.valueOf(Label.DataCleanFromMonth);
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Set<String> setRecordTypes = new Set<String>{bookingRT,masterBookingRT };
        Date fromDate = Date.today().addMonths(-dataCleanFromMonth);
        String query = 'SELECT Id FROM Opportunity WHERE RecordType.DeveloperName IN :setRecordTypes ' +
                       'AND Max_Departure__c < :fromDate';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Opportunity> listBookings) {
        List<Data_Clean_Logs__c> listLogsToInsert = new List<Data_Clean_Logs__c>();
        Database.DeleteResult[] drList = Database.delete(listBookings, false);
        
        String message;
        for(Database.DeleteResult dr : drList) {
            if(! dr.isSuccess() || Test.isRunningTest()) {
                message = null;
                for(Database.Error error : dr.getErrors()) {
                    message += error + ';';
                }
                listLogsToInsert.add(new Data_Clean_Logs__c(JobName__c = 'Batch01_CleanDataHistory', RecordId__c = dr.getId(), Message__c = message));                
            }
        }
        
        if(listLogsToInsert.size() > 0) {
            insert listLogsToInsert;
        } 
    }
    
    global void finish(Database.BatchableContext BC) {}
}