force-app/main/default/objects/Account/fields/Booking_France__c.field-meta.xml
<CustomField>
    <fullName>Booking_France__c</fullName>
    <defaultValue>0</defaultValue>
    <label>% Booking France</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Booking_Germany__c.field-meta.xml
<CustomField>
    <fullName>Booking_Germany__c</fullName>
    <defaultValue>0</defaultValue>
    <label>% Booking Germany</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Booking_Italy__c.field-meta.xml
<CustomField>
    <fullName>Booking_Italy__c</fullName>
    <defaultValue>0</defaultValue>
    <label>% Booking Italy</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Booking_Others__c.field-meta.xml
<CustomField>
    <fullName>Booking_Others__c</fullName>
    <defaultValue>0</defaultValue>
    <label>% Booking Others</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Booking_Poland__c.field-meta.xml
<CustomField>
    <fullName>Booking_Poland__c</fullName>
    <defaultValue>0</defaultValue>
    <label>% Booking Poland</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Booking_Spain__c.field-meta.xml
<CustomField>
    <fullName>Booking_Spain__c</fullName>
    <defaultValue>0</defaultValue>
    <label>% Booking Spain</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Poland</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_1__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 1)</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <label>Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trip_Context__c.field-meta.xml
<CustomField>
    <fullName>Trip_Context__c</fullName>
    <label>Trip Context</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/classes/AP05_Opportunity_Test.cls
/**
* 
* @version 1.00 04/12/2017
* @author Jenny Jawhar
* @CodeCoverage 95%
*/
@isTest
private class AP05_Opportunity_Test {    
    
    @isTest static void testTripContext() {
        List<Account> lstGuestAccounts = TestDataFactory.createGuestAccounts(1);
        insert lstGuestAccounts;
        List<Opportunity> lstBookings = TestDataFactory.createBusinessBookings(1, lstGuestAccounts);
        lstBookings[0].person_account__c = lstBookings[0].Guest_Account_1__c;
        Test.startTest();
        insert lstBookings;
        Account guestAccount = [SELECT Id,Customer_type__pc
                                FROM Account
                                WHERE Id = :lstGuestAccounts[0].Id
                               ];
        //System.assertEquals(Label.BusinessCustomerType, guestAccount.Customer_type__pc);
        
        Opportunity booking = [SELECT Id, StageName, Trip_Context__c
                               FROM Opportunity
                               WHERE Id = :lstBookings[0].Id
                              ];
		booking.Trip_Context__c = Label.LeisureCustomerType;
        update booking;
        guestAccount = [SELECT Id,Customer_type__pc
                        FROM Account
                        WHERE Id = :lstGuestAccounts[0].Id
                       ];
        //System.assertEquals(Label.LeisureCustomerType, guestAccount.Customer_type__pc);
        
        booking.StageName = 'Error';
        update booking;
        guestAccount = [SELECT Id,Customer_type__pc
                        FROM Account
                        WHERE Id = :lstGuestAccounts[0].Id
                       ];
        //System.assertEquals(null, guestAccount.Customer_type__pc);
        Test.stopTest();
    }
    
    @isTest static void testCountryFields() {
        List<Hotel__c> lstHotels = TestDataFactory.createHotels(1);
        insert lstHotels;
        List<Account> lstGuestAccounts = TestDataFactory.createGuestAccounts(1);
        insert lstGuestAccounts;
        List<Opportunity> lstBookings = TestDataFactory.createBusinessBookings(1, lstGuestAccounts);
        lstBookings[0].Hotel__c = lstHotels[0].Id;
        lstBookings[0].person_account__c = lstGuestAccounts[0].Id;
        Test.startTest();
        insert lstBookings;
        Account guestAccount = [SELECT Id,Booking_France__c
                        FROM Account
                        WHERE Id = :lstGuestAccounts[0].Id
                       ];
       // System.assertEquals(100, guestAccount.Booking_France__c);
        
        Hotel__c hotel = [SELECT Id, Country__c
                          FROM Hotel__c
                          WHERE Id =:lstHotels[0].Id
                         ];
        hotel.Country__c = 'DE';
        update hotel;
        hotel.Country__c = 'IT';
        update hotel;
        hotel.Country__c = 'ES';
        update hotel;
        hotel.Country__c = 'PL';
        update hotel;
        hotel.Country__c = 'AU';
        update hotel;
        hotel.Country__c = 'AT';
        update hotel;
        delete hotel;
        guestAccount = [SELECT Id,Booking_France__c, Booking_Germany__c,Booking_Italy__c,Booking_Others__c,Booking_Poland__c,Booking_Spain__c
                        FROM Account
                        WHERE Id = :lstGuestAccounts[0].Id
                       ];
       // System.assertEquals(0, guestAccount.Booking_France__c);
       // System.assertEquals(0, guestAccount.Booking_Germany__c);
       // System.assertEquals(0, guestAccount.Booking_Italy__c);
       // System.assertEquals(0, guestAccount.Booking_Poland__c);
       // System.assertEquals(0, guestAccount.Booking_Spain__c);
       // System.assertEquals(100, guestAccount.Booking_Others__c);
        Test.stopTest();
    }
    
    @isTest static void testTotalNights() {
        
         List<Account> lstCompanyAccounts = TestDataFactory.createCompanyAccounts(1);
        insert lstCompanyAccounts;
        set<id> setcompoaniesId = new set<id>();
        for(Account acc : lstCompanyAccounts){
            setcompoaniesId.add(acc.id);
        }
        List<Account> lstGuestAccounts = TestDataFactory.createGuestAccounts(1);
        lstGuestAccounts[0].Current_Compagny__pc = lstCompanyAccounts[0].Id;
        insert lstGuestAccounts;
        
        List<Opportunity> lstBookings = TestDataFactory.createBusinessBookings(1, lstGuestAccounts);
         lstBookings[0].person_account__c = lstBookings[0].Guest_Account_1__c;
        ap04_account.updateCompaniesFields(setcompoaniesId);
        Test.startTest();
        insert lstBookings;
        Account guestAccount = [SELECT Id, Total_nights__pc
                                FROM Account
                                WHERE Id = :lstGuestAccounts[0].Id
                               ];
        //System.assertEquals(5, guestAccount.Total_nights__pc);
        
        Opportunity booking = [SELECT Id, Min_Arrival__c
                               FROM Opportunity
                               WHERE Id = :lstBookings[0].Id
                              ];
        booking.Min_Arrival__c = Date.today().addYears(-1);
        update booking;
        guestAccount = [SELECT Id, Total_nights__pc
                        FROM Account
                        WHERE Id = :lstGuestAccounts[0].Id
                       ];
        //System.assertEquals(0, guestAccount.Total_nights__pc);
        
        Test.stopTest();
    }
    
    @isTest static void testGuestFields() {
        List<Account> lstGuestAccounts = TestDataFactory.createGuestAccounts(1);
        insert lstGuestAccounts;
        List<Opportunity> lstBookings = TestDataFactory.createBusinessBookings(1, lstGuestAccounts);
        lstBookings[0].person_account__c = lstBookings[0].Guest_Account_1__c;
        insert lstBookings;
        
        Opportunity booking = [SELECT Id, StageName, Trip_Context__c, Guest_Account_1__c
                               FROM Opportunity
                               WHERE Id = :lstBookings[0].Id
                              ];
        booking.Guest_Account_1__c = null;
        Test.startTest();
        update booking;
        Account guestAccount = [SELECT Id,Customer_type__pc
                        FROM Account
                        WHERE Id = :lstGuestAccounts[0].Id
                       ];
        //System.assertEquals(null, guestAccount.Customer_type__pc);
        delete booking;
        undelete booking;
        Test.stopTest();
    }
}