force-app/main/default/objects/Account/fields/E_club_country_code__c.field-meta.xml
<CustomField>
    <fullName>E_club_country_code__c</fullName>
    <label>Subscription country</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Name__c</fullName>
    <label>Subscription hotel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MarketingCountry__c.field-meta.xml
<CustomField>
    <fullName>MarketingCountry__c</fullName>
    <formula>IF(
AND(
Booking_FranceNB__c &gt; Booking_GermanyNb__c,
Booking_FranceNB__c &gt; Booking_ItalyNb__c,
Booking_FranceNB__c &gt; Booking_SpainNb__c,
Booking_FranceNB__c &gt; Booking_AustriaNB__c
),
&apos;BU France&apos;,
IF(
AND(
Booking_AustriaNB__c &gt; Booking_FranceNB__c,
Booking_AustriaNB__c &gt; Booking_ItalyNb__c,
Booking_AustriaNB__c &gt; Booking_SpainNb__c,
Booking_AustriaNB__c &gt; Booking_GermanyNb__c
),
&apos;BU Austria&apos;,
IF(
AND(
Booking_GermanyNb__c &gt; Booking_FranceNB__c,
Booking_GermanyNb__c &gt; Booking_ItalyNb__c,
Booking_GermanyNb__c &gt; Booking_SpainNb__c,
Booking_GermanyNb__c &gt; Booking_AustriaNB__c
),
&apos;BU Germany&apos;,
IF(
AND(
Booking_ItalyNb__c &gt; Booking_FranceNB__c,
Booking_ItalyNb__c &gt; Booking_GermanyNb__c,
Booking_ItalyNb__c &gt; Booking_SpainNb__c,
Booking_ItalyNb__c &gt; Booking_AustriaNB__c
),
&apos;BU Italy&apos;,
IF(
AND(
Booking_SpainNb__c &gt; Booking_FranceNB__c,
Booking_SpainNb__c &gt; Booking_GermanyNb__c,
Booking_SpainNb__c &gt; Booking_ItalyNb__c,
Booking_SpainNb__c &gt; Booking_AustriaNB__c
),
&apos;BU Spain&apos;,
/*case they are all equals or 0 */
IF(
E_club_country_code__c = &apos;FR&apos;,
&apos;BU France&apos;,
IF(
E_club_country_code__c = &apos;AT&apos;,
&apos;BU Austria&apos;,
IF(
E_club_country_code__c = &apos;DE&apos;,
&apos;BU Germany&apos;,
IF(
E_club_country_code__c = &apos;IT&apos;,
&apos;BU Italy&apos;,
IF(
E_club_country_code__c = &apos;ES&apos;,
&apos;BU Spain&apos;,
IF(
/*case they souscription country is not filled with the proper value */
ISPICKVAL(PersonMailingCountryCode,&apos;FR&apos;),
&apos;BU France&apos;,
IF(
ISPICKVAL(PersonMailingCountryCode,&apos;AT&apos;),
&apos;BU Austria&apos;,
IF(
ISPICKVAL(PersonMailingCountryCode,&apos;DE&apos;),
&apos;BU Germany&apos;,
IF(
ISPICKVAL(PersonMailingCountryCode,&apos;IT&apos;),
&apos;BU Italy&apos;,
IF(
ISPICKVAL(PersonMailingCountryCode,&apos;ES&apos;),
&apos;BU Spain&apos;,
IF(
/*case they address country is not filled with the proper value */
ISPICKVAL(Language__pc ,&apos;FR&apos;),
&apos;BU France&apos;,
IF(
ISPICKVAL(Language__pc ,&apos;AT&apos;),
&apos;BU Austria&apos;,
IF(
ISPICKVAL(Language__pc ,&apos;DE&apos;),
&apos;BU Germany&apos;,
IF(
ISPICKVAL(Language__pc ,&apos;IT&apos;),
&apos;BU Italy&apos;,
IF(
ISPICKVAL(Language__pc ,&apos;ES&apos;),
&apos;BU Spain&apos;,
&apos;BU France&apos;
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)
)</formula>
    <label>MarketingCountry</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Setting__mdt/Account_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Language of User key can be used to send email to the end of user</description>
    <label>Account Setting</label>
    <pluralLabel>Account Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account_Setting__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Name of Country</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Setting__mdt/fields/DomainEmail__c.field-meta.xml
<CustomField>
    <fullName>DomainEmail__c</fullName>
    <description>Name of Domain Email</description>
    <label>Domain Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Setting__mdt/fields/Indicative__c.field-meta.xml
<CustomField>
    <fullName>Indicative__c</fullName>
    <description>Indicative phone</description>
    <label>Indicative</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Setting__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Language used</description>
    <label>Language</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Setting__mdt/fields/MarketingCountry__c.field-meta.xml
<CustomField>
    <fullName>MarketingCountry__c</fullName>
    <description>Marketing Country</description>
    <label>MarketingCountry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value of country</description>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Commercial_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Hotel_Name__c</fullName>
    <label>Commercial Hotel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Language__c/Language__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Language</label>
</CustomObject>

force-app/main/default/classes/UtilsMethodeForAccount.cls
/** 
 * Apexclass for the Utils Methode For Account 
 * @author  Omar Bensouda o.bensouda@obkconsulting.com
 * @version 0.1
 * @date 11/12/2019 
 */

public without sharing class UtilsMethodeForAccount {
    /** 
    * Method BBH Club Subscription Country
    * @parm    List<Account> newRecords
    * @author  Omar Bensouda o.bensouda@obkconsulting.com
    * @version 0.1
    * @date of creation  11/12/2019 
    */
    public static void bBHClubSubscriptionCountry(List<Account> newRecords) {
        List<Account_Setting__mdt> accountSettings = [SELECT Id, Country__c,MarketingCountry__c, DomainEmail__c, Indicative__c, 
                                                            Language__c, Value__c FROM Account_Setting__mdt];
        Map<String,String> LanguageByValue          = new Map<String,String>();
        Map<String,String> CountryByValue           = new Map<String,String>();
        Map<String,String> IndicativeByValue        = new Map<String,String>();
        Map<String,String> DomainByValue            = new Map<String,String>();
        Map<String,String> MarketingCountryByValue  = new Map<String,String>();
        for(Account_Setting__mdt tempAccountSettings: accountSettings){
            LanguageByValue.put(tempAccountSettings.Language__c,tempAccountSettings.Value__c);
            CountryByValue.put(tempAccountSettings.Country__c,tempAccountSettings.Value__c);
            IndicativeByValue.put(tempAccountSettings.Indicative__c,tempAccountSettings.Value__c);
            DomainByValue.put(tempAccountSettings.DomainEmail__c,tempAccountSettings.Value__c);
            MarketingCountryByValue.put(tempAccountSettings.MarketingCountry__c,tempAccountSettings.Value__c);
        }
        
        Map<Account, String> mapAccountByHotelName              = new  Map<Account, String>() ;
        Set<String>         setOfHotelName                      = new Set<String>();
        List<Account>       listOfNextTreatmentAccount          = new List<Account>();
        for(Account currentAccount : newRecords){
            if(currentAccount.E_club_subscription__pc == true && currentAccount.E_club_Creation_channel__pc != null){
                if(String.isNotBlank(currentAccount.Hotel_Name__c) && currentAccount.E_club_Creation_channel__pc == 'Dashboard'){
                    System.debug('@@: 1');
                    mapAccountByHotelName.put(currentAccount,currentAccount.Hotel_Name__c);
                    setOfHotelName.add(currentAccount.Hotel_Name__c);
                }else{
                    System.debug('@@: 2');
                    listOfNextTreatmentAccount.add(currentAccount);
                }
            }
        }
        Map <String,String> mapNameOfHotelByCountry = new Map <String,String>();
        List <Hotel__c> listOfHotel = [Select Id,Commercial_Hotel_Name__c,Country__c From Hotel__c where Commercial_Hotel_Name__c in:setOfHotelName];
        for(Hotel__c currentHotel : listOfHotel){
            mapNameOfHotelByCountry.put(currentHotel.Commercial_Hotel_Name__c,currentHotel.Country__c);
        }
        for(Account currentAccount : mapAccountByHotelName.keySet()){
            if(!(String.isNotBlank(mapAccountByHotelName.get(currentAccount)) && mapNameOfHotelByCountry.get(mapAccountByHotelName.get(currentAccount)) != null  && mapNameOfHotelByCountry.get(mapAccountByHotelName.get(currentAccount))!= '')){ listOfNextTreatmentAccount.add(currentAccount);
            }else{
                System.debug('@@: 10: '+mapAccountByHotelName.get(currentAccount));
                currentAccount.E_club_country_code__c = mapNameOfHotelByCountry.get(mapAccountByHotelName.get(currentAccount));
            }
        }
        bBHClubSubscriptionCountryHelper(listOfNextTreatmentAccount, LanguageByValue, CountryByValue, IndicativeByValue, DomainByValue, MarketingCountryByValue);
    }
    /** 
    * Method BBH Club Subscription Country helper
    * @parm    List<Account> newRecords
    * @author  Omar Bensouda o.bensouda@obkconsulting.com
    * @version 0.1
    * @date of creation  11/12/2019 
    */
    public static void bBHClubSubscriptionCountryHelper(List<Account> listOfNextTreatmentAccount,Map<String,String> LanguageByValue,
                                                        Map<String,String> CountryByValue, Map<String,String> IndicativeByValue,Map<String,String> DomainByValue, Map<String,String> MarketingCountryByValue) {
        String defaultValue = 'BU Groupe';                           
        for(Account currentAccount : listOfNextTreatmentAccount){
            if(String.isNotBlank(currentAccount.MarketingCountry__c) && currentAccount.MarketingCountry__c != defaultValue 
                    && MarketingCountryByValue.get(currentAccount.MarketingCountry__c) != null 
                    && MarketingCountryByValue.get(currentAccount.MarketingCountry__c)!= '' ){// Marketing country
                System.debug('@@: 4');
                currentAccount.E_club_country_code__c = MarketingCountryByValue.get(currentAccount.MarketingCountry__c);
            }else{
                if(String.isNotBlank(currentAccount.Language__pc) && String.isNotBlank(LanguageByValue.get(currentAccount.Language__pc)) ){ //Langue
                    System.debug('@@: 5');
                    currentAccount.E_club_country_code__c = LanguageByValue.get(currentAccount.Language__pc);
                }else{
                    if(String.isNotBlank(currentAccount.PersonMailingCountry) && String.isNotBlank(CountryByValue.get(currentAccount.PersonMailingCountry)) ){ //Country
                        System.debug('@@: 6');
                        currentAccount.E_club_country_code__c = CountryByValue.get(currentAccount.PersonMailingCountry);
                    }else{ 
                        if(String.isNotBlank(currentAccount.PersonMobilePhone) && extractIndicativeFromThePhone(currentAccount.PersonMobilePhone) != null && 
                                IndicativeByValue.get(extractIndicativeFromThePhone(currentAccount.PersonMobilePhone)) != null 
                                && IndicativeByValue.get(extractIndicativeFromThePhone(currentAccount.PersonMobilePhone))!= ''){ // Phone
                            System.debug('@@: 7: '+extractIndicativeFromThePhone(currentAccount.PersonMobilePhone));
                            currentAccount.E_club_country_code__c = IndicativeByValue.get(extractIndicativeFromThePhone(currentAccount.PersonMobilePhone));
                        }else{
                            if(String.isNotBlank(currentAccount.Email__pc) && extractDomainFromEmailAdresse(currentAccount.Email__pc) != null 
                                &&  DomainByValue.get(extractDomainFromEmailAdresse(currentAccount.Email__pc)) != null 
                                &&  DomainByValue.get(extractDomainFromEmailAdresse(currentAccount.Email__pc)) != ''){ // Email Domain
                                System.debug('@@: 8: '+extractDomainFromEmailAdresse(currentAccount.Email__pc));
                                currentAccount.E_club_country_code__c = DomainByValue.get(extractDomainFromEmailAdresse(currentAccount.Email__pc));
                            }else{
                                System.debug('@@: 9');
                                currentAccount.E_club_country_code__c = 'EA' ;
                            }
                        }
                    }
                }
            }
        }
    }
    /** 
    * Method extract Domain From Email Adresse 
    * @parm    String Email
    * @author  Omar Bensouda o.bensouda@obkconsulting.com
    * @version 0.1
    * @date of creation  11/12/2019 
    */
    public static String extractDomainFromEmailAdresse(String email){
        if(String.isNotBlank(email)){
            String domainFromEmail = email.split('@').get(1).split('\\.').get(1);
            return domainFromEmail;
        }
        return null;
    }
    /** 
    * Method extract Indicative From the Phone
    * @parm    String Phone
    * @author  Omar Bensouda o.bensouda@obkconsulting.com
    * @version 0.1
    * @date of creation  11/12/2019 
    */
    public static String extractIndicativeFromThePhone(String phone){
        if(String.isNotBlank(phone)){
            //Phone good format example: +33 699985133 (documentation link: WS UpdatePersonAccount )
            Pattern MyPattern = Pattern.compile('\\+[0-9]{1,4} [1-9]{1}[0-9]{1,20}$');
            Matcher MyMatcher = MyPattern.matcher(phone);
            if(MyMatcher.matches()){
                String indicative = phone.split('\\+').get(1);
                indicative = indicative.split(' ').get(0);
                return indicative;
            }
        }
        return null;
    }
}