force-app/main/default/objects/Account/fields/Externalid__c.field-meta.xml
<CustomField>
    <fullName>Externalid__c</fullName>
    <externalId>true</externalId>
    <label>Externalid</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Code__c.field-meta.xml
<CustomField>
    <fullName>Partner_Code__c</fullName>
    <externalId>true</externalId>
    <label>Partner Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Hot Prospect</fullName>
            </value>
            <value>
                <fullName>New Customer</fullName>
            </value>
            <value>
                <fullName>Active Customer</fullName>
            </value>
            <value>
                <fullName>In decline</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <externalId>true</externalId>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BookerDevice__c.field-meta.xml
<CustomField>
    <fullName>BookerDevice__c</fullName>
    <label>BookerDevice</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BookingCancellable__c.field-meta.xml
<CustomField>
    <fullName>BookingCancellable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancellable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BookingComment__c.field-meta.xml
<CustomField>
    <fullName>BookingComment__c</fullName>
    <label>BookingComment</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BookingSource__c.field-meta.xml
<CustomField>
    <fullName>BookingSource__c</fullName>
    <label>BookingSource</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BookingUpdatable__c.field-meta.xml
<CustomField>
    <fullName>BookingUpdatable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updatable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Lead__c.field-meta.xml
<CustomField>
    <fullName>Business_Lead__c</fullName>
    <label>Business Lead</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/cad_status__c.field-meta.xml
<CustomField>
    <fullName>cad_status__c</fullName>
    <description>About_check_in_online</description>
    <label>cad status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cancellation_policy_Code__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_policy_Code__c</fullName>
    <label>Cancellation policy Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ChannelCategory__c.field-meta.xml
<CustomField>
    <fullName>ChannelCategory__c</fullName>
    <label>ChannelCategory</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <label>Confirmation Number</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Status_FK__c.field-meta.xml
<CustomField>
    <fullName>Current_Status_FK__c</fullName>
    <description>ID Last Booking Status</description>
    <label>Current Status FK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DistributionMode__c.field-meta.xml
<CustomField>
    <fullName>DistributionMode__c</fullName>
    <label>DistributionMode</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_AddressBooking__c.field-meta.xml
<CustomField>
    <fullName>Email_AddressBooking__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Externalid__c.field-meta.xml
<CustomField>
    <fullName>Externalid__c</fullName>
    <externalId>true</externalId>
    <label>Externalid</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Status_FK__c.field-meta.xml
<CustomField>
    <fullName>First_Status_FK__c</fullName>
    <label>First Status FK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FirstNameBooking__c.field-meta.xml
<CustomField>
    <fullName>FirstNameBooking__c</fullName>
    <label>First name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guaranty_policy_code__c.field-meta.xml
<CustomField>
    <fullName>Guaranty_policy_code__c</fullName>
    <label>Guaranty policy code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guarentee__c.field-meta.xml
<CustomField>
    <fullName>Guarentee__c</fullName>
    <label>Guarentee</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_1__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 1)</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_2__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 2</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 2)</relationshipLabel>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_3__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 3</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 3)</relationshipLabel>
    <relationshipName>Bookings3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_4__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 4</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 4)</relationshipLabel>
    <relationshipName>Bookings4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Guest_Account_5__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 5</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 5)</relationshipLabel>
    <relationshipName>Bookings5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <formula>Hotel__r.Hotel_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Include_Breakfast__c.field-meta.xml
<CustomField>
    <fullName>Include_Breakfast__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Breakfast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LastNameBooking__c.field-meta.xml
<CustomField>
    <fullName>LastNameBooking__c</fullName>
    <label>LastName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Code__c.field-meta.xml
<CustomField>
    <fullName>Partner_Code__c</fullName>
    <label>Partner Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PartnerCode__c.field-meta.xml
<CustomField>
    <fullName>PartnerCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (partner code)</relationshipLabel>
    <relationshipName>BookingsPartnerCode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Phone_NumberBooking__c.field-meta.xml
<CustomField>
    <fullName>Phone_NumberBooking__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PMSClientId__c.field-meta.xml
<CustomField>
    <fullName>PMSClientId__c</fullName>
    <label>PMSClientId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Second_Rate_Code__c.field-meta.xml
<CustomField>
    <fullName>Second_Rate_Code__c</fullName>
    <label>Second Rate Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trip_Context__c.field-meta.xml
<CustomField>
    <fullName>Trip_Context__c</fullName>
    <label>Trip Context</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trip_Reason__c.field-meta.xml
<CustomField>
    <fullName>Trip_Reason__c</fullName>
    <label>Trip Reason</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_city_tax__c.field-meta.xml
<CustomField>
    <fullName>Type_city_tax__c</fullName>
    <label>Type city tax</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusive</fullName>
            </value>
            <value>
                <fullName>Inclusive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/utm_campaign__c.field-meta.xml
<CustomField>
    <fullName>utm_campaign__c</fullName>
    <label>utm_campaign</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/utm_content__c.field-meta.xml
<CustomField>
    <fullName>utm_content__c</fullName>
    <label>utm_content</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/utm_medium__c.field-meta.xml
<CustomField>
    <fullName>utm_medium__c</fullName>
    <label>utm_medium</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/utm_source__c.field-meta.xml
<CustomField>
    <fullName>utm_source__c</fullName>
    <label>utm_source</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/utm_term__c.field-meta.xml
<CustomField>
    <fullName>utm_term__c</fullName>
    <label>utm_term</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Wallet_Status__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Status__c</fullName>
    <label>Wallet Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Earned</fullName>
            </value>
            <value>
                <fullName>Burned</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/classes/Booking.cls
//test class: WS02_BookingInfo_Test
global class Booking {
     
    webservice String Account;
    webservice String BookingDevice;
    webservice boolean BookingCancellable;
    webservice String BookingComment;
    webservice String BookingSource;
    webservice String StageName;
    webservice boolean BookingUpdatable;
    webservice boolean IncludeBreakfast;
    webservice String BusinessLead;
    webservice String ChannelCategory;
    webservice Date CheckInDate;
    webservice Date CheckOutDate;
    webservice Date CloseDate;
    webservice String DistributionMode;
    webservice String ExternalId;
    webservice String MasterBooking;
    webservice String FirstStatus;
    webservice String CurrentStatus;
    webservice String Guarantee;
    webservice String Hotel;
    webservice double InvoicedAmount;
    webservice Date MinArrival;
    webservice Date MaxDeprature;
    webservice String Name;
    webservice String PartnerCode;
    webservice boolean PaymentAtBooking;
    webservice String PersonAccount;
    webservice String PMSClientId;
    webservice String Rate;
    webservice String Status;
    webservice String TripContext;
    webservice String TripReason;
    webservice String UtmSource;
    webservice String UtmMedium;
    webservice String UtmCampaign;
    webservice String Term;
    webservice String Content;
    webservice String CadStatus;
    webservice String LastNameBooking;
    webservice String FirstNameBooking;
    webservice String EmailAddressBooking;
    webservice String PhoneNumberBooking;
    webservice String CancellationPolicyCode;
    webservice String GuarantyPolicyCode;
    webservice String ConfirmationNumber;
    webservice String SecondRateCode;
    webservice boolean CheckinBySMS;
    webservice double InvoicedCityTax;
    webservice double AmountCityTax;
    webservice String WalletStatus;
    webservice Integer EarnPoint;
    webservice String TypeCityTax;
    webservice String FieldsToNull;
    webservice String GuestAccount1;
    webservice String GuestAccount2;
    webservice String GuestAccount3;
    webservice String GuestAccount4;
    webservice String GuestAccount5;
    webservice String CurrencyIsoCode;
    
    public Opportunity mapSFFields() {
        Opportunity booking = new Opportunity();
        Set<String> setFieldsToNull = new Set<String>();
        if(String.isNotBlank(FieldsToNull)) {
            for(String field : FieldsToNull.split(',')) {
                setFieldsToNull.add(field);
            }
        }
        
        Id bookingRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Label.BookingRecordTypeName).getRecordTypeId();
        booking.RecordTypeId = bookingRT;
        
        Account accountObj = null;
        if(String.isNotBlank(Account) || setFieldsToNull.contains('Account')) {
            accountObj = new Account(ExternalId__c = Account);
            booking.Account = accountObj;
        }
        if(String.isNotBlank(BookingDevice) || setFieldsToNull.contains('BookingDevice')) {
            booking.BookerDevice__c = BookingDevice;
        }
            if(String.isNotBlank(CurrencyIsoCode) || setFieldsToNull.contains('CurrencyIsoCode')) {
                booking.CurrencyIsoCode = CurrencyIsoCode;
            }
        if(String.isNotBlank(BookingComment) || setFieldsToNull.contains('BookingComment')) {
            booking.BookingComment__c = BookingComment;
        }
        if(String.isNotBlank(BookingSource) || setFieldsToNull.contains('BookingSource')) {
            booking.BookingSource__c = BookingSource;
        }
        if(String.isNotBlank(StageName) || setFieldsToNull.contains('StageName')) {
            booking.StageName = StageName;
        }
        if(String.isNotBlank(BusinessLead) || setFieldsToNull.contains('BusinessLead')) {
            booking.Business_Lead__c = BusinessLead;
        }
        if(String.isNotBlank(ChannelCategory) || setFieldsToNull.contains('ChannelCategory')) {
            booking.ChannelCategory__c = ChannelCategory;
        }
        if(String.isNotBlank(DistributionMode) || setFieldsToNull.contains('DistributionMode')) {
            booking.DistributionMode__c = DistributionMode;
        }
        if(String.isNotBlank(ExternalId) || setFieldsToNull.contains('ExternalId')) {
            booking.ExternalId__c = ExternalId;
        }
        if(String.isNotBlank(MasterBooking) || setFieldsToNull.contains('MasterBooking')) {
            if(MasterBooking != null) {
                Opportunity masterBookingObj = new Opportunity(ExternalId__c = MasterBooking);
                booking.Master_Booking_FK__r = masterBookingObj;
            } else if(setFieldsToNull.contains('MasterBooking')) {
                booking.Master_Booking_FK__c = null;
            }
            
        }
        if(String.isNotBlank(FirstStatus) || setFieldsToNull.contains('FirstStatus')) {
            booking.First_Status_FK__c = FirstStatus;
        }
        if(String.isNotBlank(CurrentStatus) || setFieldsToNull.contains('CurrentStatus')) {
            booking.Current_Status_FK__c = CurrentStatus;
        }
        if(String.isNotBlank(Guarantee) || setFieldsToNull.contains('Guarantee')) {
            booking.Guarentee__c = Guarantee;
        }
        if(String.isNotBlank(Hotel) || setFieldsToNull.contains('Hotel')) {
            if(Hotel != null) {                
                Hotel__c hotelObj = new Hotel__c(Hotel_ID__c = Hotel);
                booking.Hotel__r = hotelObj;
            } else if(setFieldsToNull.contains('Hotel')) {
                booking.Hotel__c = null;
            }
        }
        if(String.isNotBlank(Name) || setFieldsToNull.contains('Name')) {
            booking.Name = Name;
        }        
        if(String.isNotBlank(PartnerCode) || setFieldsToNull.contains('PartnerCode')) {
            system.debug('else remove ______ +++++');
            //booking.Partner_Code__c = PartnerCode;
            //Ticket CRMSS-286 Start
            if(PartnerCode != null) { 
                accountObj = new Account(Partner_Code__c = PartnerCode);
                booking.PartnerCode__r = accountObj;
                system.debug('#### accountObj ' + accountObj);
                //Ticket CRMSS-286 End
            }else if(setFieldsToNull.contains('PartnerCode')) {
                system.debug('else remove ______');
                booking.PartnerCode__c = null;
            }
        }
        if(String.isNotBlank(PersonAccount) || setFieldsToNull.contains('PersonAccount')) {
            if(PersonAccount != null) {
                accountObj = new Account(ExternalId__c = PersonAccount);
                booking.Person_Account__r = accountObj;
            } else if(setFieldsToNull.contains('PersonAccount')) {
                booking.Person_Account__c = null;
            }
            
        }
        if(String.isNotBlank(PMSClientId) || setFieldsToNull.contains('PMSClientId')) {
            booking.PMSClientId__c = PMSClientId;
        }
        if(String.isNotBlank(Rate) || setFieldsToNull.contains('Rate')) {
            booking.Rate__c = Rate;
        }
        if(String.isNotBlank(Status) || setFieldsToNull.contains('Status')) {
            booking.Status__c = Status;
        }
        if(String.isNotBlank(TripContext) || setFieldsToNull.contains('TripContext')) {
            booking.Trip_Context__c = TripContext;
        }
        if(String.isNotBlank(TripReason) || setFieldsToNull.contains('TripReason')) {
            booking.Trip_Reason__c = TripReason;
        }
        if(String.isNotBlank(UtmSource) || setFieldsToNull.contains('UtmSource')) {
            booking.utm_source__c = UtmSource;
        }
        if(String.isNotBlank(UtmMedium) || setFieldsToNull.contains('UtmMedium')) {
            booking.utm_medium__c = UtmMedium;
        }
        if(String.isNotBlank(UtmCampaign) || setFieldsToNull.contains('UtmCampaign')) {
            booking.utm_campaign__c = UtmCampaign;
        }
        if(String.isNotBlank(Term) || setFieldsToNull.contains('Term')) {
            booking.utm_term__c = Term;
        }
        if(String.isNotBlank(Content) || setFieldsToNull.contains('Content')) {
            booking.utm_content__c = Content;
        }
        if(String.isNotBlank(CadStatus) || setFieldsToNull.contains('CadStatus')) {
            booking.cad_status__c = CadStatus;
        }
        if(String.isNotBlank(LastNameBooking) || setFieldsToNull.contains('LastNameBooking')) {
            booking.LastNameBooking__c = LastNameBooking;
        }
        if(String.isNotBlank(FirstNameBooking) || setFieldsToNull.contains('FirstNameBooking')) {
            booking.FirstNameBooking__c = FirstNameBooking;
        }
        if(String.isNotBlank(EmailAddressBooking) || setFieldsToNull.contains('EmailAddressBooking')) {
            booking.Email_AddressBooking__c = EmailAddressBooking;
        }
        if(String.isNotBlank(PhoneNumberBooking) || setFieldsToNull.contains('PhoneNumberBooking')) {
            booking.Phone_NumberBooking__c = PhoneNumberBooking;
        }
        if(String.isNotBlank(CancellationPolicyCode) || setFieldsToNull.contains('CancellationPolicyCode')) {
            booking.Cancellation_policy_Code__c = CancellationPolicyCode;
        }
        if(String.isNotBlank(GuarantyPolicyCode) || setFieldsToNull.contains('GuarantyPolicyCode')) {
            booking.Guaranty_policy_code__c = GuarantyPolicyCode;
        }
        if(String.isNotBlank(ConfirmationNumber) || setFieldsToNull.contains('ConfirmationNumber')) {
            booking.Confirmation_Number__c = ConfirmationNumber;
        }
        if(String.isNotBlank(SecondRateCode) || setFieldsToNull.contains('SecondRateCode')) {
            booking.Second_Rate_Code__c = SecondRateCode;
        }
        if(String.isNotBlank(GuestAccount1) || setFieldsToNull.contains('GuestAccount1')) {
            if(GuestAccount1 != null) {
                accountObj = new Account(ExternalId__c = GuestAccount1);
                booking.Guest_Account_1__r = accountObj;
            } else if(setFieldsToNull.contains('GuestAccount1')) {
                booking.Guest_Account_1__c = null;
            }
            
        }
        if(String.isNotBlank(GuestAccount2) || setFieldsToNull.contains('GuestAccount2')) {
           if(GuestAccount2 != null) {
                accountObj = new Account(ExternalId__c = GuestAccount2);
                booking.Guest_Account_2__r = accountObj;
            } else if(setFieldsToNull.contains('GuestAccount2')) {
                booking.Guest_Account_2__c = null;
            }
        }
        if(String.isNotBlank(GuestAccount3) || setFieldsToNull.contains('GuestAccount3')) {
            if(GuestAccount3 != null) {
                accountObj = new Account(ExternalId__c = GuestAccount3);
                booking.Guest_Account_3__r = accountObj;
            } else if(setFieldsToNull.contains('GuestAccount3')) {
                booking.Guest_Account_3__c = null;
            }
        }
        if(String.isNotBlank(GuestAccount4) || setFieldsToNull.contains('GuestAccount4')) {
            if(GuestAccount4 != null) {
                accountObj = new Account(ExternalId__c = GuestAccount4);
                booking.Guest_Account_4__r = accountObj;
            } else if(setFieldsToNull.contains('GuestAccount4')) {
                booking.Guest_Account_4__c = null;
            }
        }
        if(String.isNotBlank(GuestAccount5) || setFieldsToNull.contains('GuestAccount5')) {
            if(GuestAccount5 != null) {
                accountObj = new Account(ExternalId__c = GuestAccount5);
                booking.Guest_Account_5__r = accountObj;
            } else if(setFieldsToNull.contains('GuestAccount5')) {
                booking.Guest_Account_5__c = null;
            }
        }
        if(String.isNotBlank(WalletStatus) || setFieldsToNull.contains('WalletStatus')) {
            booking.Wallet_Status__c = WalletStatus;
        }
        if(String.isNotBlank(TypeCityTax) || setFieldsToNull.contains('TypeCityTax')) {
            booking.Type_city_tax__c = TypeCityTax;
        }        
        if(BookingCancellable != null || setFieldsToNull.contains('BookingCancellable')) {
            booking.BookingCancellable__c = BookingCancellable;
        }
        if(BookingUpdatable != null || setFieldsToNull.contains('BookingUpdatable')) {
            booking.BookingUpdatable__c = BookingUpdatable;
        }
        if(IncludeBreakfast != null || setFieldsToNull.contains('IncludeBreakfast')) {
            booking.Include_Breakfast__c = IncludeBreakfast;
        }
        if(CheckInDate != null || setFieldsToNull.contains('CheckInDate')) {
            booking.CheckInDate__c = CheckInDate;
        }
        if(CheckOutDate != null || setFieldsToNull.contains('CheckOutDate')) {
            booking.CheckOutDate__c = CheckOutDate;
        }
        if(CloseDate != null || setFieldsToNull.contains('CloseDate')) {
            booking.CloseDate = CloseDate;
        }
        if(InvoicedAmount != null || setFieldsToNull.contains('InvoicedAmount')) {
            booking.Invoiced_amount__c = InvoicedAmount;
        }
        if(MinArrival != null || setFieldsToNull.contains('MinArrival')) {
            booking.Min_Arrival__c = MinArrival;
        }
        if(MaxDeprature != null || setFieldsToNull.contains('MaxDeprature')) {
            booking.Max_Departure__c = MaxDeprature;
        }
        if(PaymentAtBooking != null || setFieldsToNull.contains('PaymentAtBooking')) {
            booking.Payment_at_Booking__c = PaymentAtBooking;
        }
        if(CheckinBySMS != null || setFieldsToNull.contains('CheckinBySMS')) {
            booking.CheckinbySMS__c = CheckinBySMS;
        }
        if(InvoicedCityTax != null || setFieldsToNull.contains('InvoicedCityTax')) {
            booking.Invoiced_city_tax__c = InvoicedCityTax;
        }
        if(AmountCityTax != null || setFieldsToNull.contains('AmountCityTax')) {
           // booking.Amount_City_Tax__c = AmountCityTax;
        }
        if(EarnPoint != null || setFieldsToNull.contains('EarnPoint')) {
            booking.Earn_Point__c = EarnPoint;
        }
        
        return booking;
    }
    
}