force-app/main/default/objects/Account/fields/Externalid__c.field-meta.xml
<CustomField>
    <fullName>Externalid__c</fullName>
    <externalId>true</externalId>
    <label>Externalid</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000R4WJ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Concerned_country__c.field-meta.xml
<CustomField>
    <fullName>Concerned_country__c</fullName>
    <description>Field fills by web to case in the B&amp;B website</description>
    <inlineHelpText>Hotel country location selected by the customer</inlineHelpText>
    <label>Concerned country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BW</fullName>
                <label>Botswana</label>
            </value>
            <value>
                <fullName>BV</fullName>
                <label>Bouvet Island</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italy</label>
            </value>
            <value>
                <fullName>LB</fullName>
                <label>Lebanon</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Poland</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Externalid__c.field-meta.xml
<CustomField>
    <fullName>Externalid__c</fullName>
    <externalId>true</externalId>
    <label>Externalid</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Commercial_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Hotel_Name__c</fullName>
    <label>Commercial Hotel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Country_code__c.field-meta.xml
<CustomField>
    <fullName>Country_code__c</fullName>
    <label>Country code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <externalId>true</externalId>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/objects/User/fields/BypassProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>BypassProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass ProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/BypassValidationRule__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/BypassWorkflow__c.field-meta.xml
<CustomField>
    <fullName>BypassWorkflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP01_ObjectShare_Test.cls
/*******************************************************************************************************************************************************************
* @author: Kanel Services  - Sh
* @date: 02/04/2021
* @details : Test Class for AP01_ObjectShare
*
*********************************************************************************************************************************************************************/
@isTest (SeeAllData=false)
public class AP01_ObjectShare_Test {
    Public static list<Booking__c> listBookings;
    Public static list<Case>       caseList;
    
    private static testMethod void test_createSharewrtBooking(){
        User usr = createUser();
        Insert usr;
        System.Assert(usr.Id != null);

        System.runas(usr){
            createRecords();
            Test.startTest();
                Insert listBookings;
            Test.StopTest();
        }
    }

    private static testMethod void test_createSharewrtCase(){
        User usr = createUser();
        Insert usr;
        System.Assert(usr.Id != null);

        UtilsBypass.SKIP_METHOD_MAP.put('CreatePersonAccount', 'objectShareTest');
        UtilsBypass.SKIP_APEXCLASS_MAP.put('AP01_Case', 'objectShareTest');

        System.runas(usr){
            createRecords();
            Test.startTest();
                Insert caseList;
            Test.StopTest();
        }
    }
    
    private static testMethod void test_Batch_ObjectShareCatchUp_Booking(){
        User usr = createUser();
        Insert usr;
        System.Assert(usr.Id != null);

        System.runas(usr){
            createRecords();
            Insert listBookings;

            Test.startTest();
                String query ='SELECT id,Hotel__r.Country_code__c, Bucket_of_booking__c '+
                                'FROM Booking__c '+                             
                                'LIMIT 200';

                Batch_ObjectShareCatchUp batchLaunch = new Batch_ObjectShareCatchUp(query,'Booking__c','Booking__c');
                database.executebatch(batchLaunch,200);  
            Test.StopTest();
        }
    }

    private static testMethod void test_Batch_ObjectShareCatchUp_Account(){
        User usr = createUser();
        Insert usr;
        System.Assert(usr.Id != null);

        System.runas(usr){
            createRecords();
            Insert listBookings;

            Test.startTest();
                String query ='SELECT id,Hotel__r.Country_code__c, Bucket_of_booking__c,Personnal_Account__c '+
                                'FROM Booking__c '+                             
                                'LIMIT 200';

                Batch_ObjectShareCatchUp batchLaunch = new Batch_ObjectShareCatchUp(query,'Booking__c','Account');
                database.executebatch(batchLaunch,200);  
            Test.StopTest();
        }
    }

    private static testMethod void test_Batch_ObjectShareCatchUp_caseAccount(){
        User usr = createUser();
        Insert usr;
        System.Assert(usr.Id != null);

        UtilsBypass.SKIP_METHOD_MAP.put('CreatePersonAccount', 'objectShareTest');
        UtilsBypass.SKIP_APEXCLASS_MAP.put('AP01_Case', 'objectShareTest');
        
        System.runas(usr){
            createRecords();
            Insert caseList;

            Test.startTest();
                String query ='SELECT CaseNumber, Concerned_country__c, Hotel__r.Country_code__c, AccountId '+
                                'FROM Case '+                             
                                'LIMIT 200';

                Batch_ObjectShareCatchUp batchLaunch = new Batch_ObjectShareCatchUp(query,'Case','Account');
                database.executebatch(batchLaunch,200);  
            Test.StopTest();
        }
    }

    private static void createRecords(){
    
        //Create User Role
        UserRole r = new UserRole(DeveloperName = 'testFrance', Name = 'testFrance');
        Insert r;
        
        Id PARTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        
        listBookings = new list<Booking__c>();
        list<account> listPAAccounts = new list<Account>();
        list<Hotel__c> listHotels = new list<Hotel__c>();
        
        Hotel__c testHotelFR = new Hotel__c(Commercial_Hotel_Name__c = 'test hotelfr',Hotel_ID__c='2343', Country_code__c = 'FR');
        listHotels.add(testHotelFR);
        Hotel__c testHotelFR2 = new Hotel__c(Commercial_Hotel_Name__c = 'test hotelfr2',Hotel_ID__c='2344', Country_code__c = 'FR');
        listHotels.add(testHotelFR2);
        Hotel__c testHotelDE = new Hotel__c(Commercial_Hotel_Name__c = 'test hotelde',Hotel_ID__c='23431', Country_code__c = 'DE');
        listHotels.add(testHotelDE);
        Hotel__c testHotelAT = new Hotel__c(Commercial_Hotel_Name__c = 'test hotelat',Hotel_ID__c='23432', Country_code__c = 'AT');
        listHotels.add(testHotelAT);
        Hotel__c testHotelPL = new Hotel__c(Commercial_Hotel_Name__c = 'test hotelpl',Hotel_ID__c='23433', Country_code__c = 'PL');
        listHotels.add(testHotelPL);
        Hotel__c testHotelIT = new Hotel__c(Commercial_Hotel_Name__c = 'test hotelit',Hotel_ID__c='23435', Country_code__c = 'IT');
        listHotels.add(testHotelIT);
        Hotel__c testHotelES = new Hotel__c(Commercial_Hotel_Name__c = 'test hoteles',Hotel_ID__c='23436', Country_code__c = 'ES');
        listHotels.add(testHotelES);
        Hotel__c testHotelOther = new Hotel__c(Commercial_Hotel_Name__c = 'test hotelother',Hotel_ID__c='23437', Country_code__c = 'LB');
        listHotels.add(testHotelOther);
        
        Insert listHotels;
        
        for(integer i = 0; i<8; i++){
            
            string name = 'Person'+i;
            string extId = 'paExtId'+i;
            Account personAccount =  Utils.CreatePersonAccount(name, null);
            personAccount.recordtypeId = PARTId;
            personAccount.Externalid__pc = extId;
            listPAAccounts.add(personAccount);
        }
        
        Insert listPAAccounts;
        
        Buket_of_booking__c bucketBook = new Buket_of_booking__c();
        bucketBook.EXTERNALID__c = 'BUKBook1';
        Insert bucketBook;
        
        for(integer i = 0; i<8; i++){
            
            string extId = 'bookExtId'+i;
            Booking__c book = new Booking__c();
            book.Bucket_of_booking__c = bucketBook.Id;
            book.EXTERNALID__c = extId;
            book.Personnal_Account__c = listPAAccounts[i].Id;
            book.Hotel__c = listHotels[i].Id;
            book.stage__c = 'Booked';
            listBookings.add(book);
        } 
        
        
        caseList = New List<Case>();
        for(integer i = 0; i<8; i++){    
            Case cas = Utils.CreateCase();            
            cas.AccountId = listPAAccounts[i].Id;
            cas.Type = label.Information_request;
            cas.Salesforce_Case_Type__c = 'General request';
            cas.Status = 'Open';           
            cas.Hotel_ID__c = listHotels[i].Id;
            cas.SuppliedEmail = 'customerTest@asce.com';
            cas.First_Name__c = 'First' + i;
            cas.Last_Name__c = 'Last' + i;
            cas.Concerned_country__c = 'FR';
            //cas.setOptions(dmo);
            caseList.add(cas);
        }
        
    }
    
    private static User createUser(){          
        Id standardUserProfileID = [SELECT ID, Name FROM Profile WHERE Name='System Administrator'].ID;

        User usr = New User(  FirstName              = 'Admin Test' , 
                              LastName               = 'Admin' ,  
                              alias                  = 'AjdoeT' , 
                              email                  = 'Adminjdoe@bbtest.com', 
                              username               = 'AdminjohnD@testuser.com', 
                              CommunityNickname      = 'AdminDoe032' , 
                              Division               = Label.AP01_MasterVoucher_DivisionCorporate,
                              EmailEncodingKey       = 'UTF-8',
                              // DefaultCurrencyIsoCode = 'EUR', 
                              LocaleSidKey           = 'en_US', 
                              LanguageLocaleKey      = 'en_US',
                              TimeZoneSidKey         = 'Europe/Paris', 
                              ProfileID              = standardUserProfileID,
                              Phone                  = '+33 23 45 67 89',
                              BypassValidationRule__c = true,
                              BypassProcessBuilder__c = false,
                              BypassWorkflow__c       = false                             

        ); 
        return usr;     
          
  }


}