force-app/main/default/objects/Account/fields/Externalid__c.field-meta.xml
<CustomField>
    <fullName>Externalid__c</fullName>
    <externalId>true</externalId>
    <label>Externalid</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Externalid__c.field-meta.xml
<CustomField>
    <fullName>Externalid__c</fullName>
    <externalId>true</externalId>
    <label>Externalid</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FR</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>EN</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spanish</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italian</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>German</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Catalan</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>Czech</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Polish</label>
            </value>
            <value>
                <fullName>PT-BR</fullName>
                <label>Brazilian Portuguese</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Language__c/Language__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Language</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Lead__c.field-meta.xml
<CustomField>
    <fullName>Business_Lead__c</fullName>
    <label>Business Lead</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel_description__c.field-meta.xml
<CustomField>
    <fullName>Channel_description__c</fullName>
    <label>Channel description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_FK__c.field-meta.xml
<CustomField>
    <fullName>Client_FK__c</fullName>
    <label>Client FK</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distribution__c.field-meta.xml
<CustomField>
    <fullName>Distribution__c</fullName>
    <label>Distribution</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Externalid__c.field-meta.xml
<CustomField>
    <fullName>Externalid__c</fullName>
    <externalId>true</externalId>
    <label>Externalid</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoiced_amount__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoiced_city_tax__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_city_tax__c</fullName>
    <label>Invoiced city tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_Departure__c.field-meta.xml
<CustomField>
    <fullName>Max_Departure__c</fullName>
    <label>Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <label>Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mobile_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone_Number__c</fullName>
    <label>Mobile Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NB_Adults__c.field-meta.xml
<CustomField>
    <fullName>NB_Adults__c</fullName>
    <label>NB Adults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NB_Children__c.field-meta.xml
<CustomField>
    <fullName>NB_Children__c</fullName>
    <label>NB Children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/classes/MasterBooking.cls
global without sharing virtual class MasterBooking {
    
    webservice String BusinessLead;
    webservice String Channel;
    webservice String ChannelDescription;
    webservice String ClientFK;
    webservice Date CloseDate;
    webservice String Contact;
    webservice String Distribution;
    webservice String Email;
    webservice String ExternalId;
    webservice String FirstName;
    webservice String LastName;
    webservice String Language;
    webservice Date MinArrival;
    webservice Date MaxDeparture;
    webservice String MobilePhoneNumber;
    webservice String Name;
    webservice Integer NbrOfAdults;
    webservice Integer NbrOfChildren;
    webservice String PersonAccount;
    webservice String PhoneNumber;
    webservice String Source;
    webservice String StageName;
    webservice double InvoicedCityTax;
    webservice String FieldsToNull;
    webservice double InvoicedAmount;
    webservice String CurrencyIsoCode;
     
    
    public Opportunity mapSFFields() {
        Opportunity masterBooking = new Opportunity();
        Set<String> setFieldsToNull = new Set<String>();
        if(String.isNotBlank(FieldsToNull)) {
            for(String field : FieldsToNull.split(',')) {
                setFieldsToNull.add(field);
            }
        }
        
        Id masterBookingRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Label.MasterBookingRTDevName).getRecordTypeId();
        masterBooking.RecordTypeId = masterBookingRT;
        
        if(String.isNotBlank(BusinessLead) || setFieldsToNull.contains('BusinessLead')) {
            masterBooking.Business_Lead__c = BusinessLead;
        }
        if(String.isNotBlank(Channel) || setFieldsToNull.contains('Channel')) {
            masterBooking.Channel__c = Channel;
        }
        if(String.isNotBlank(CurrencyIsoCode) || setFieldsToNull.contains('CurrencyIsoCode')) {
            masterBooking.CurrencyIsoCode = CurrencyIsoCode;
        }
        if(String.isNotBlank(ChannelDescription) || setFieldsToNull.contains('ChannelDescription')) {
            masterBooking.Channel_description__c = ChannelDescription;
        }
        if(String.isNotBlank(ClientFK) || setFieldsToNull.contains('ClientFK')) {
            masterBooking.Client_FK__c = ClientFK;
        }
        if(CloseDate != null || setFieldsToNull.contains('CloseDate')) {
            masterBooking.CloseDate = CloseDate;
        }
        if(String.isNotBlank(Contact) || setFieldsToNull.contains('Contact')) {
            if(Contact != null) {
                Contact contactObj = new Contact(ExternalId__c = Contact);
                masterBooking.Contact__r = contactObj;
            } else if(setFieldsToNull.contains('Contact')){
                masterBooking.Contact__c = null;
            }
        }
        if(String.isNotBlank(Distribution) || setFieldsToNull.contains('Distribution')) {
            masterBooking.Distribution__c = Distribution;
        }
        if(String.isNotBlank(Email) || setFieldsToNull.contains('Email')) {
            masterBooking.E_mail__c = Email;
        }
        if(String.isNotBlank(ExternalId) || setFieldsToNull.contains('ExternalId')) {
            masterBooking.Externalid__c = ExternalId;
        }
        if(String.isNotBlank(FirstName) || setFieldsToNull.contains('FirstName')) {
            masterBooking.First_Name__c = FirstName;
        }
        if(String.isNotBlank(LastName) || setFieldsToNull.contains('LastName')) {
            masterBooking.Last_Name__c = LastName;
        }
        if(String.isNotBlank(Language) || setFieldsToNull.contains('Language')) {
            masterBooking.Language__c = Language;
        }
        if(MinArrival != null || setFieldsToNull.contains('MinArrival')) {
            masterBooking.Min_Arrival__c = MinArrival;
        }
        if(MaxDeparture != null || setFieldsToNull.contains('MaxDeparture')) {
            masterBooking.Max_Departure__c = MaxDeparture;
        }
        if(String.isNotBlank(MobilePhoneNumber) || setFieldsToNull.contains('MobilePhoneNumber')) {
            masterBooking.Mobile_Phone_Number__c = MobilePhoneNumber;
        }
        if(String.isNotBlank(Name) || setFieldsToNull.contains('Name')) {
            masterBooking.Name = Name;
        }
        if(String.isNotBlank(PersonAccount) || setFieldsToNull.contains('PersonAccount')) {
            if(PersonAccount != null) {
                Account personAccountObj = new Account(ExternalId__c = PersonAccount);
                masterBooking.Person_Account__r = personAccountObj;
            } else if(setFieldsToNull.contains('PersonAccount')) {
                masterBooking.Person_Account__c = null;
            }            
        }
        if(String.isNotBlank(PhoneNumber) || setFieldsToNull.contains('PhoneNumber')) {
            masterBooking.Phone_Number__c = PhoneNumber;
        }
        if(String.isNotBlank(Source) || setFieldsToNull.contains('Source')) {
            masterBooking.Source__c = Source;
        }
        if(String.isNotBlank(StageName) || setFieldsToNull.contains('StageName')) {
            masterBooking.StageName = StageName;
        }
        if(NbrOfAdults != null || setFieldsToNull.contains('NbrOfAdults')) {
            masterBooking.NB_Adults__c = NbrOfAdults;
        }
        if(NbrOfChildren != null || setFieldsToNull.contains('NbrOfChildren')) {
            masterBooking.NB_Children__c = NbrOfChildren;
        }
        if(InvoicedCityTax != null || setFieldsToNull.contains('InvoicedCityTax')) {
            masterBooking.Invoiced_city_tax__c = InvoicedCityTax;
        }
        if(InvoicedAmount != null || setFieldsToNull.contains('InvoicedAmount')) {
            masterBooking.Invoiced_amount__c = InvoicedAmount;
        }
        return masterBooking;
    }  
}