force-app/main/default/objects/Account/fields/Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Name__c</fullName>
    <label>Subscription hotel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hotelid_club_subscription__c.field-meta.xml
<CustomField>
    <fullName>Hotelid_club_subscription__c</fullName>
    <label>Hotel subscription</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Commercial_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Hotel_Name__c</fullName>
    <label>Commercial Hotel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <externalId>true</externalId>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AP07_Account.cls
/*
* Description: Class to get the hotel name based on hotel subscription
* @author: TMA-EI CKH
* @date: 06/08/2019
* @Test class: AP07_Account_Test 
* @Coverage: 100%
*/
public class AP07_Account 
{
    public static void getHotelName(List<Account> listAcc) 
    {
        Map<String,String> mapHotIdName = new Map<String,String>();
        Set<String> hotelIds = new Set<String>();
            
        for(Account acc : listAcc)
        {
            if(acc.Hotelid_club_subscription__c != null && acc.Hotelid_club_subscription__c  != ''){
            	hotelIds.add(acc.Hotelid_club_subscription__c);    
            }else{
                acc.Hotel_Name__c = null;
            }
        }
       
        if(hotelIds.size() > 0)
        {
            List<Hotel__c> lstHotels =  [SELECT id, Commercial_Hotel_Name__c, Hotel_ID__c
                                         FROM Hotel__c  
                                         WHERE Hotel_ID__c in :hotelIds and Commercial_Hotel_Name__c != null];
            
            for(Hotel__c hotel : lstHotels)
            {
                mapHotIdName.put(hotel.Hotel_ID__c, hotel.Commercial_Hotel_Name__c);
            }
            
             for(Account acc : listAcc)
             {
                 if(mapHotIdName.get(acc.Hotelid_club_subscription__c) != null )
                 {
                     acc.Hotel_Name__c = mapHotIdName.get(acc.Hotelid_club_subscription__c);
                 }
             }
        }
    }
}