force-app/main/default/objects/Account/fields/Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Name__c</fullName>
    <label>Subscription hotel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Hot Prospect</fullName>
            </value>
            <value>
                <fullName>New Customer</fullName>
            </value>
            <value>
                <fullName>Active Customer</fullName>
            </value>
            <value>
                <fullName>In decline</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/classes/AP06_Account_Test.cls
/**
* 
* @version 31/07/2019
* @author TMA-EI
* @CodeCoverage 100%
*/

@isTest
public class AP06_Account_Test 
{
 public static testMethod void trackHistory()
    {
        Account PartnerAccount = Utils.CreatePartnerAccount('Partner',null);  
        insert PartnerAccount;  
        
        Account PersonAccount = Utils.CreatePersonAccount('Person',PartnerAccount.Id);
        insert PersonAccount;
        
        Account  acc = [Select Id,Date_of_e_club_purchase__pc,E_club_Creation_channel__pc ,Hotel_Name__c, status__c
               From Account
               Where Id =: PersonAccount.Id];
		
        system.debug('###acc ' + acc.Hotel_Name__c);
        test.starttest();
        acc.Date_of_e_club_purchase__pc = system.today()+2;
        acc.E_club_Creation_channel__pc = 'Website';
        acc.Hotel_Name__c='Hotel1';
        update acc;
        system.debug('###acc ' + acc.Hotel_Name__c);
        test.stoptest();
    }
}