force-app/main/default/objects/Account/fields/Hotels_Count__c.field-meta.xml
<CustomField>
    <fullName>Hotels_Count__c</fullName>
    <label># Hotels</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Commercial_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Hotel_Name__c</fullName>
    <label>Commercial Hotel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <externalId>true</externalId>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Booking_Person_account__c.field-meta.xml
<CustomField>
    <fullName>Booking_Person_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Person account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <formula>Hotel__r.Hotel_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/User/fields/BypassValidationRule__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/BypassWorkflow__c.field-meta.xml
<CustomField>
    <fullName>BypassWorkflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_HotelCountChecked_Test.cls
/*
* Description: Test class for Batch_UpdateMB_ConfNb_HotelName
* @author: TMA-EIL JKA
* @date: 19/12/2019
*/

@isTest
public class Batch_HotelCountChecked_Test {
    
    @isTest
    static void batchHotelCountChecked(){
        
        Profile prof = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        
        User userTest = new User(Alias = 'systadm', Email='systadm@testorg.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = prof.Id, 
                                 TimeZoneSidKey='America/Los_Angeles', UserName='systadm@testorg.com');
        
        userTest.BypassValidationRule__c = true;
        userTest.BypassWorkflow__c = true;
        
        insert userTest;
        
        System.runAs(userTest){
            String bookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Booking').getRecordTypeId();
            List<Account> listPersonAcc = new List<Account>();
            List<Hotel__c> listHotels = new List<Hotel__c>();
            List<Opportunity> listBookings = new List<Opportunity>();
            
            Account personAcc1 = new Account(LastName = 'test1', Email__pc = 'test1@abcd.com', Hotels_Count__c = 0);
            listPersonAcc.add(personAcc1);
            Account personAcc2 = new Account(LastName = 'test2', Email__pc = 'test2@abcd.com', Hotels_Count__c = 0);
            listPersonAcc.add(personAcc2);
            
            insert listPersonAcc;
            
            Hotel__c testHotel1 = new Hotel__c(Commercial_Hotel_Name__c = 'test hotel1',Hotel_ID__c='2343');
            listHotels.add(testHotel1);
            Hotel__c testHotel2 = new Hotel__c(Commercial_Hotel_Name__c = 'test hotel2',Hotel_ID__c='23431');
            listHotels.add(testHotel2);
            Hotel__c testHotel3 = new Hotel__c(Commercial_Hotel_Name__c = 'test hotel3',Hotel_ID__c='23432');
            listHotels.add(testHotel3);
            Hotel__c testHotel4 = new Hotel__c(Commercial_Hotel_Name__c = 'test hotel4',Hotel_ID__c='23433');
            listHotels.add(testHotel4);
            
            insert listHotels;
            
            
            Opportunity book1 = new Opportunity(Name = 'Booking1', Hotel__c = testHotel1.id, CloseDate = date.today(), StageName = 'Checked', Booking_Person_account__c = personAcc1.id, RecordTypeId = bookingRTId);
            listBookings.add(book1);
            
            Opportunity book2 = new Opportunity(Name = 'Booking2', Hotel__c = testHotel1.id, CloseDate = date.today(), StageName = 'Checked', Booking_Person_account__c = personAcc1.id, RecordTypeId = bookingRTId);
            listBookings.add(book2);
            
            Opportunity book3 = new Opportunity(Name = 'Booking3', Hotel__c = testHotel2.id, CloseDate = date.today(), StageName = 'Cancelled', Booking_Person_account__c = personAcc2.id, RecordTypeId = bookingRTId);
            listBookings.add(book3);
            
            Opportunity book4 = new Opportunity(Name = 'Booking4', Hotel__c = testHotel3.id, CloseDate = date.today(), StageName = 'Checked', Booking_Person_account__c = personAcc2.id, RecordTypeId = bookingRTId);
            listBookings.add(book4);
            
            insert listBookings;
            
            test.startTest();
            
            
            Batch_HotelCountChecked batchObj = new Batch_HotelCountChecked(null,0);
            DataBase.executeBatch(batchObj);
            
            map<String,String> mapPAId = new map<String,String>();
            mapPAId.put(listPersonAcc[0].ID,'Test class error');
            
            batchObj = new Batch_HotelCountChecked(mapPAId,0);
            DataBase.executeBatch(batchObj);
            batchObj = new Batch_HotelCountChecked(mapPAId,3);
            DataBase.executeBatch(batchObj);
            
            String[] toAddresses = new String[] {'joanna.karam@ei-technologies.com'};
            String Subject = 'Batch Error : Batch_HotelCountChecked ';
            
            Utils_Email.sendEmailApex(toAddresses, Subject,mapPAId);
            
            test.stopTest();
            
            
        }
    }
}