force-app/main/default/objects/Account/fields/Hotelid_club_subscription__c.field-meta.xml
<CustomField>
    <fullName>Hotelid_club_subscription__c</fullName>
    <label>Hotel subscription</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Aland Islands</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei Darussalam</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia, Plurinational State of</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius and Saba</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <externalId>true</externalId>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/classes/AP07_Account_Test.cls
/**
* 
* @version 06/08/2019
* @author TMA-EI - CKH
* @CodeCoverage 100%
*/

@isTest
public class AP07_Account_Test {

    public static testMethod void trackHistory()
    {
        Hotel__c hot1 = new Hotel__c();
        hot1.Hotel_ID__c = 'hotel_1';
        hot1.Country__c = 'FR';
        hot1.Hotel_ID__c = '4504';
        insert hot1;
        
        Hotel__c hot2 = new Hotel__c();
        hot2.Hotel_ID__c = 'hotel_2';
        hot2.Country__c = 'FR';
        hot2.Hotel_ID__c = '4713';
        insert hot2;

		List<Account> lstToInsert = new List<Account>();
        
        Account PartnerAccount = Utils.CreatePartnerAccount('Partner',null);  
        PartnerAccount.Hotelid_club_subscription__c = '4504';
		lstToInsert.add(PartnerAccount);  
        
        Account PersonAccount = Utils.CreatePersonAccount('Person',PartnerAccount.Id);
        PersonAccount.Hotelid_club_subscription__c = '4713';
		lstToInsert.add(PersonAccount);
        
        insert lstToInsert; 
        
        test.starttest();
        PartnerAccount.Hotelid_club_subscription__c = '4713345';
        update PartnerAccount;
        test.stoptest();
    }
}