force-app/main/default/objects/Account/fields/MaxBookingMinArrival__c.field-meta.xml
<CustomField>
    <fullName>MaxBookingMinArrival__c</fullName>
    <label>MaxBookingMinArrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Code__c.field-meta.xml
<CustomField>
    <fullName>Partner_Code__c</fullName>
    <externalId>true</externalId>
    <label>Partner Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Nights__c.field-meta.xml
<CustomField>
    <fullName>Total_Nights__c</fullName>
    <label>Total nights</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Transactions__c.field-meta.xml
<CustomField>
    <fullName>Total_Transactions__c</fullName>
    <label>Total Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Compagny__c.field-meta.xml
<CustomField>
    <fullName>Current_Compagny__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Guest Account</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_nights__c.field-meta.xml
<CustomField>
    <fullName>Total_nights__c</fullName>
    <label>Total nights</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue__c</fullName>
    <label>Total Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessAccountId__c.field-meta.xml
<CustomField>
    <fullName>BusinessAccountId__c</fullName>
    <formula>Person_Account__r.PersonContact.Current_Compagny__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BusinessAccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <label>Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Code__c.field-meta.xml
<CustomField>
    <fullName>Partner_Code__c</fullName>
    <label>Partner Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stay__c/Stay__c.object-meta.xml
<CustomObject>
    <description>Junction object between booking and Person account (Account object)</description>
    <label>Stay</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Stay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stay__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000R4WJ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Guest Account</relationshipLabel>
    <relationshipName>Stays</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/BusinessAccountId__c.field-meta.xml
<CustomField>
    <fullName>BusinessAccountId__c</fullName>
    <formula>Guest_account__r.PersonContact.Current_Compagny__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BusinessAccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Guest_account__c.field-meta.xml
<CustomField>
    <fullName>Guest_account__c</fullName>
    <label>Guest account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Guest Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Stays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <formula>Booking__r.Min_Arrival__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Min Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AP02_Account.cls
/*
* Update and delete stays or master bookings (Opportunity) that are related to the updated and deleted GuestAccount
* @author: Jenny Jawhar
* @date: 21/12/2017
* @Test: AP02_Account_Test
*/
public class AP02_Account 
{
    //when the field current_compagny__c is updated in the guest account,the fields total_nights__c, total_revenue__c and total_transactions__c should be recalculated on the old and new
    //current_compagny__c business account
    public static void UpdateStayOppWhenGuestAccountUpdate(list<Account> triggerNew, map<Id,Account> oldMap)
    {
        list<Account> listAccount = new list<Account>();
        for(Account acc: triggerNew)
        {
            if(acc.Current_Compagny__pc != oldMap.get(acc.Id).Current_Compagny__pc && acc.RecordTypeId == label.PersonAccountRecordTypeId)
            {
                listAccount.add(acc);
            }
        }
        if(listAccount.size() > 0)
        {
            list<Stay__c> listStayToUpdate = new list<Stay__c>();
            list<Opportunity> listOpportunityToUpdate = new list<Opportunity>();
            list<Account> listBusinessAccountToUpdate = new list<Account>();
            list<Id> listBusinessAccount = new list<Id>();
            //Get the Stays and the Opportunities related to the updated person Account
            list<Account> listAccountWithlistStayAndOpp = [Select Id,Current_Compagny__pc,
                                                           (Select Id ,BusinessAccountId__c,Guest_Account__c,Min_Arrival__c
                                                            From Stays__r),
                                                           (Select Id,recordTypeId,Person_Account__c,BusinessAccountId__c
                                                            From Opportunities__r
                                                            Where RecordTypeId =: label.MasterBookingRecordTypeId)
                                                           From Account
                                                           Where Id IN: listAccount];
            for(Account acc:listAccountWithlistStayAndOpp)
            {
                //Get the old Business accounts that have to be recalculated
                if(oldMap.get(acc.Id).Current_Compagny__pc != null)
                {
                    listBusinessAccount.add(oldMap.get(acc.Id).Current_Compagny__pc);
                }
                list<Stay__c> listStay = acc.Stays__r;
                list<Opportunity> listOpportunity = acc.Opportunities__r;
                if(listOpportunity.size() > 0)
                {
                    listOpportunityToUpdate.addAll(listOpportunity);
                }
                if(listStay.size() > 0)
                {
                    listStayToUpdate.addAll(listStay);
                }
            }
            
            list<Contact> listContact = new list<Contact>();
            list<Id> listPersonAccountId = new list<Id>();
            //Get the business account that have to be recalculated
            list<Account> listBusinessAccountWithStayAndOpp = [Select Id,
                                                               (Select Id,AccountId
                                                                From Contacts1__r
                                                                Where IsPersonAccount =: true)
                                                               From Account
                                                               Where Id IN: listBusinessAccount];
            if(listBusinessAccount.size() > 0)
            {
                for(Account acc: listBusinessAccountWithStayAndOpp)
                {
                    list<Contact> listGuestAccount = acc.Contacts1__r;
                    //If the business account has not guests accounts, update all fiels to zero
                    if(listGuestAccount.size() <= 0)
                    {
                        acc.Total_Nights__c = 0;
                        acc.Total_Revenue__c = 0;
                        acc.Total_Transactions__c = 0;
                        acc.MaxBookingMinArrival__c = null;
                        listBusinessAccountToUpdate.add(acc);
                    }
                    //else get the list of the remaining guest accounts
                    else
                    {
                        listContact.addall(acc.Contacts1__r);
                    }
                } 
                for(Contact con: listContact)
                {
                    listPersonAccountId.add(con.AccountId);
                }
                listAccountWithlistStayAndOpp = [Select Id,Current_Compagny__pc,
                                                 (Select Id,BusinessAccountId__c,Guest_Account__c,Min_Arrival__c
                                                  From Stays__r),
                                                 (Select Id,recordTypeId,Person_Account__c,BusinessAccountId__c
                                                  From Opportunities__r
                                                  Where RecordTypeId =: label.MasterBookingRecordTypeId)
                                                 From Account
                                                 Where Id IN: listPersonAccountId];
                //get the stays and master Bookings of these remaining guests accounts in order to recalculate the fields
                for(Account acc:listAccountWithlistStayAndOpp)
                { 
                    list<Stay__c> listStay = acc.Stays__r;
                    list<Opportunity> listOpportunity = acc.Opportunities__r;
                    if(listOpportunity.size() > 0)
                    {
                        listOpportunityToUpdate.addAll(listOpportunity);
                    }
                    if(listStay.size() > 0)
                    {
                        listStayToUpdate.addAll(listStay);
                    }
                }
            }
            
            //update all the lists
            //The methods are called one by one because the other methods in the AfterUpdateStay and AfterUpdateOpportunity trigger should not be called
            AP02_Stay.UpdateTotalNights(listStayToUpdate , null,null);
            AP03_Stay.UpdateTotalRevenue(listStayToUpdate , null,null);
            AP05_Stay.UpdateMaxBookingMinArrival(listStayToUpdate , null,null);
            AP04_Opportunity.UpdateTotalTransactions(listOpportunityToUpdate, null, null);
            update listBusinessAccountToUpdate;
        }
    }
    public static void getAccountOfStayWhenGuestAccountDelete(list<Account> triggerOld)
    {
        list<Account> listAccountWithlistStay = [Select Id,
                                                 (Select Id
                                                  From Stays__r)
                                                 From Account
                                                 Where Id IN: triggerOld
                                                 And recordTypeId =: label.PersonAccountRecordTypeId];
        list<Stay__c> listStayAffected = new list<Stay__c>();
        for(Account acc: listAccountWithlistStay)
        {
            list<Stay__c> listStay = acc.Stays__r;
            if(listStay.size() > 0)
            {
                listStayAffected.addAll(listStay);
            }
        }
        delete listStayAffected;
    }
    public static void updatePartnerShipFieldsWhenPartnerCodeChange(list<Account> triggerNew, map<Id,Account> oldMap)
    {
        list<String> listPartnerCode = new list<string>();
        for(Account acc:triggerNew)
        {
            if(acc.RecordTypeId != label.PersonAccountRecordTypeId && (oldMap==null || oldMap.get(acc.Id).Partner_Code__c != acc.Partner_Code__c))
            {
                if(!string.IsBlank(acc.Partner_Code__c))
                {
                    listPartnerCode.add(acc.Partner_Code__c);
                }
            }
        }
        if(listPartnerCode.size() > 0)
        {
            list<Opportunity> listBookingAffected = [Select Id,Partner_Code__c,recordTypeId
                                                     From Opportunity
                                                     Where Partner_Code__c IN: listPartnerCode];
            AP03_Opportunity.UpdateTotalNightsPartnerShip(listBookingAffected ,null, null);
            AP03_Opportunity.UpdateTotalRevenuePartnerShip(listBookingAffected ,null, null);
            AP03_Opportunity.UpdateTotalTransactionsPartnerShip(listBookingAffected,null,null);
        }
    }
}