force-app/main/default/objects/Account/fields/MaxBookingMinArrival__c.field-meta.xml
<CustomField>
    <fullName>MaxBookingMinArrival__c</fullName>
    <label>MaxBookingMinArrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessAccountId__c.field-meta.xml
<CustomField>
    <fullName>BusinessAccountId__c</fullName>
    <formula>Person_Account__r.PersonContact.Current_Compagny__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BusinessAccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <label>Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/Stay__c/Stay__c.object-meta.xml
<CustomObject>
    <description>Junction object between booking and Person account (Account object)</description>
    <label>Stay</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Stay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stay__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000R4WJ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Guest Account</relationshipLabel>
    <relationshipName>Stays</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/BusinessAccountId__c.field-meta.xml
<CustomField>
    <fullName>BusinessAccountId__c</fullName>
    <formula>Guest_account__r.PersonContact.Current_Compagny__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BusinessAccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Guest_account__c.field-meta.xml
<CustomField>
    <fullName>Guest_account__c</fullName>
    <label>Guest account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Guest Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Stays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <formula>Booking__r.Min_Arrival__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Min Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AP05_Stay.cls
/*
* Get the maximum date of Min_Arrival__c on opportunity with record type booking and put it in the technical custom field MaxBookingMinArrival__c on account
* @author: Jenny Jawhar
* @date: 13/11/2017
* @Test: AP05_Stay_Test
*/
public class AP05_Stay 
{
    /*
    public static void UpdateMaxBookingMinArrival(list<Stay__c> triggerNew, Map<Id,Stay__c> oldMap, List<Stay__c> triggerOld)
    {
        System.debug('##### AP05_Stay Start');
        set<string> listAccountId = new set<string>();     
        set<string> listPersonAccount = new set<string>();
        if(triggerNew != null)
        {
            for(Stay__c stay: triggerNew)
            {
                Stay__c oldStay=oldMap==null ? stay : oldMap.get(stay.Id);
                if(stay.Min_Arrival__c != null)
                {
                    if(oldMap==null && String.isNotBlank(stay.Guest_Account__c))listPersonAccount.add(stay.Guest_account__c);
                    if(oldMap==null && String.isNotBlank(stay.BusinessAccountId__c)) listAccountId.add(stay.BusinessAccountId__c);                       
                    if(oldMap != null && oldStay.Guest_account__c != stay.Guest_account__c)
                    {
                       if(String.isNotBlank(stay.Guest_Account__c))listPersonAccount.add(stay.Guest_account__c); 
                       if(String.isNotBlank(oldStay.Guest_account__c)) listPersonAccount.add(oldStay.Guest_account__c);
                    }
                    if(oldMap!=null && oldStay.BusinessAccountId__c!=stay.BusinessAccountId__c )
                    {
                        if(String.isNotBlank(stay.BusinessAccountId__c)) listAccountId.add(stay.BusinessAccountId__c);
                      if(String.isNotBlank(oldStay.BusinessAccountId__c))  listAccountId.add(oldStay.BusinessAccountId__c);                     
                    }
                }                
            }
        }
        else
        {
            for(Stay__c stay:triggerOld)
            {
                if(stay.Min_Arrival__c!=null)
                {
                     if(String.isNotBlank(stay.Guest_Account__c))listPersonAccount.add(stay.Guest_account__c);
                    if(String.isNotBlank(stay.BusinessAccountId__c))
                    {
                        listAccountId.add(stay.BusinessAccountId__c);                    
                    }
                }   
            }
        }
        if(listPersonAccount.size() > 0)
        {
            List<Account> ListAccToUpdate = new List<Account>();
            list<Account> listSelectedAccount= [Select Id,MaxBookingMinArrival__c,
                                                (select Id,Min_Arrival__c
                                                 from Stays__r
                                                 where Min_Arrival__c != null
                                                 Order by Min_Arrival__c desc limit 1)
                                                from Account
                                                where Id IN: listPersonAccount];   
            System.debug('##### AP05_Stay listSelectedAccount ' + listSelectedAccount);
            for(Account acc : listSelectedAccount)
            {
                list<Stay__c> listStay = acc.Stays__r;
                if(listStay.size() > 0)
                {
                    acc.MaxBookingMinArrival__c = listStay[0].Min_Arrival__c;
                }
                else
                {
                    acc.MaxBookingMinArrival__c  = null;
                }
                ListAccToUpdate.add(acc);
            }
            update ListAccToUpdate;
        }
        if(listAccountId.size() > 0)
        {           
            List<Account> listAccToUpdate = new List<Account>();
            List<Stay__c> listStays = [Select Id, BusinessAccountId__c,Min_Arrival__c
                                       From Stay__c
                                       where BusinessAccountId__c IN: listAccountId
                                       And Min_Arrival__c != null];
            System.debug('##### AP05_Stay listStays ' + listStays);
            list<Account> listAccount = [Select Id, MaxBookingMinArrival__c
                                         From Account
                                         Where Id IN:listAccountId];
            for(Account acc: listAccount)
            {
                Date minArrDate;
                for(Stay__c stay: listStays)
                {
                    if(stay.BusinessAccountId__c == acc.Id)
                    {                       
                        if(stay.Min_Arrival__c > minArrDate || minArrDate==null)
                        {  
                            minArrDate = stay.Min_Arrival__c; 
                        }
                    }
                }
                acc.MaxBookingMinArrival__c = minArrDate;
                listAccToUpdate.add(acc);
            }
            update listAccToUpdate;
        }
    }    */
}