force-app/main/default/objects/Account/fields/Partner_Code__c.field-meta.xml
<CustomField>
    <fullName>Partner_Code__c</fullName>
    <externalId>true</externalId>
    <label>Partner Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/Booking_Room_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line	 Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Room Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Line__c/fields/Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Booking_FK__c</fullName>
    <label>Booking_FK</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Option</relationshipLabel>
    <relationshipName>Bookings_Room_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line__c/fields/Price_Euros__c.field-meta.xml
<CustomField>
    <fullName>Price_Euros__c</fullName>
    <label>Price €</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line_Price__c/Booking_Room_Line_Price__c.object-meta.xml
<CustomObject>
    <label>Booking Room Line Price</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Booking Room Line Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings Room Line Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Room_Line_Price__c/fields/Booking_Room_Line_FK__c.field-meta.xml
<CustomField>
    <fullName>Booking_Room_Line_FK__c</fullName>
    <label>Booking Room Line_FK</label>
    <referenceTo>Booking_Room_Line__c</referenceTo>
    <relationshipLabel>Bookings Room Line Price</relationshipLabel>
    <relationshipName>Bookings_Room_Line_Price</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking_Room_Line_Price__c/fields/Price_Euros__c.field-meta.xml
<CustomField>
    <fullName>Price_Euros__c</fullName>
    <description>Price in €</description>
    <inlineHelpText>Price in €</inlineHelpText>
    <label>Price €</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000R4WJ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FR</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>EN</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spanish</label>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>Italian</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>German</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Catalan</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>Czech</label>
            </value>
            <value>
                <fullName>PL</fullName>
                <label>Polish</label>
            </value>
            <value>
                <fullName>PT-BR</fullName>
                <label>Brazilian Portuguese</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <externalId>true</externalId>
    <label>Hotel ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Hotel_Room_Option__c/Hotel_Room_Option__c.object-meta.xml
<CustomObject>
    <label>Hotel Room Code &amp; Option</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Hotel Room &amp; Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels Rooms &amp; Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Language__c/Language__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Language</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <formula>Hotel__r.Hotel_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Code__c.field-meta.xml
<CustomField>
    <fullName>Partner_Code__c</fullName>
    <label>Partner Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stay__c/Stay__c.object-meta.xml
<CustomObject>
    <description>Junction object between booking and Person account (Account object)</description>
    <label>Stay</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Stay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stay__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000R4WJ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Guest Account</relationshipLabel>
    <relationshipName>Stays</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Guest_account__c.field-meta.xml
<CustomField>
    <fullName>Guest_account__c</fullName>
    <label>Guest account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Guest Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Stays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Hotel_Id__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Id__c</fullName>
    <formula>Booking__r.Hotel__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Utils.cls
/*
* Description: 
* @author: Jenny Jawhar
* @date: 22/09/2017
* @Test: Utils_Test
*/
public class Utils {
    public static Account CreatePersonAccount(string Name, string companyId){
        Account acc = new Account(lastName = Name, recordTypeId = Label.PersonAccountRecordTypeId,
                                  Current_Compagny__pc = companyId, BillingCountry = 'France');//, recordTypeId = Label.PersonAccountRecordTypeId
        return acc;
    }
    public static Contact CreateContact(string Name,string AccountId,string language){
        Contact cont = new Contact(lastName=Name, AccountId = AccountId, language__c=language);
        return cont;
    }
    public static Account CreatePartnerAccount(string Name, string partnerCode){
        Account acc = new Account(Name = Name,  Partner_Code__c = partnerCode, BillingPostalCode = '12345', BillingCountry = 'France');//recordTypeId = label.PartnerRecordTypeID,
        return acc;
    }
    public static Opportunity CreateBookingOpportunity(string Name){
        Opportunity Opp = new Opportunity(Name = Name, CloseDate=date.Today(), recordTypeId = Label.BookingRecordTypeId);
        return Opp;
    }
    public static Opportunity CreateMasterBookingOpportunity(string Name, string accId){
        Opportunity opp = new Opportunity(Name = Name, CloseDate=date.Today(), StageName = label.ClosedWonStage,
                                          Person_Account__c = accId, recordTypeId = Label.MasterBookingRecordTypeId);
        return opp;
    }
    public static Booking_Room_Line__c CreateBookingRoomLine(string bookingId){
        Booking_Room_Line__c roomLine = new Booking_Room_Line__c(Booking_FK__c = bookingId);
        return roomLine;
    }
    public static Booking_Room_Line_Price__c CreateBookingRoomLinePrice(string bookingRoomLineId, decimal price){
        Booking_Room_Line_Price__c roomPrice = new Booking_Room_Line_Price__c(Booking_Room_Line_FK__c = bookingRoomLineId, Price_euros__c = price);
        return roomPrice;
    }
    public static Contract CreateContract(){
        Contract cont = new Contract();
        return cont;
    } 
    public static Hotel__c CreateHotel(string hotelId){
        Hotel__c hotel = new Hotel__c(Hotel_ID__c = hotelId);
        return hotel;
    } 
    public static Product2 CreateProduct(){
        Product2 prod = new Product2();
        return prod;
    }
    public static Case CreateCase(){
        Case cas = new Case();
        return cas;
    }
    public static Hotel_Room_Option__c CreateHotelRoomOptionAndCode(){
        Hotel_Room_Option__c hotelRoomOptionAndCode = new Hotel_Room_Option__c();
        return hotelRoomOptionAndCode;
    }
    public static Stay__c CreateStay(string AccountId, string BookingId){
        Stay__c stay = new Stay__c(Guest_Account__c = AccountId , Booking__c = BookingId);
        return stay;
    }
    public static Messaging.SingleEmailMessage CreateSingleEmailMessage(string[] toAddresses,string[] CcAddresses,Id targetId,
                                                                        Id whatId,string templateId,string ReplyEmail){
        Messaging.SingleEmailMessage singleEmailMessage = new Messaging.SingleEmailMessage();                    
        singleEmailMessage.setTargetObjectId(targetId);
        singleEmailMessage.setWhatId(whatId);       
        singleEmailMessage.setTemplateId(templateId);
        singleEmailMessage.setToAddresses(toAddresses);
        singleEmailMessage.setCcAddresses(CcAddresses);
        singleEmailMessage.SetReplyTo(ReplyEmail);  
        singleEmailMessage.setSenderDisplayName(ReplyEmail);
        return singleEmailMessage;
    }
    public static Integer getBatchSize(string aClassName){
        Integer batchSize = 200;
        List<CMT003_BatchSize__mdt> batchsizeList = [SELECT Id, BatchSize__c, ApexClass__c
                                                        FROM CMT003_BatchSize__mdt
                                                        WHERE ApexClass__c =:aClassName];   
        if (batchsizeList != null && batchsizeList.Size() > 0){
            batchSize = batchsizeList[0].BatchSize__c != null ? Integer.ValueOf(batchsizeList[0].BatchSize__c) : 200;
        }
        return batchSize;
    }
    
    public static Task CreateTask(string tskStatus, string tskWhoId, string tskWhatId,date tskWDueDate, string tskPriority, string tskSubject, string tskDescription){
        Task tsk = new Task();
        tsk.Status=tskStatus;
        tsk.WhoId=tskWhoId;
        tsk.WhatId=tskWhatId;
        tsk.ActivityDate=tskWDueDate;
        tsk.Priority=tskPriority;
        tsk.Subject=tskSubject;
        tsk.description=tskDescription;
        return tsk;
    }

}