force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Hot Prospect</fullName>
            </value>
            <value>
                <fullName>New Customer</fullName>
            </value>
            <value>
                <fullName>Active Customer</fullName>
            </value>
            <value>
                <fullName>In decline</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status_Text__c.field-meta.xml
<CustomField>
    <fullName>Status_Text__c</fullName>
    <defaultValue>&apos;Prospect&apos;</defaultValue>
    <label>Status Text</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <label>Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/objects/Stay__c/Stay__c.object-meta.xml
<CustomObject>
    <description>Junction object between booking and Person account (Account object)</description>
    <label>Stay</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Stay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stay__c/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <formula>Booking__r.Min_Arrival__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Min Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AP01_Account_Test.cls
/**
* 
* @version 1.00 3/10/2017
* @author Jenny Jawhar
* @CodeCoverage 100%
*/
@isTest
public class AP01_Account_Test 
{
    private static testMethod void UpdateAccount()
    {
        Account PartnerAccount = Utils.CreatePartnerAccount('Partner',null);  
        insert PartnerAccount;  
        
        Account PersonAccount = Utils.CreatePersonAccount('Person',PartnerAccount.Id);
        insert PersonAccount;
        
        Contract cont = Utils.CreateContract();
        cont.AccountId = PartnerAccount.Id;
        insert cont;      
        
        Opportunity booking = Utils.CreateBookingOpportunity('Booking');
        booking.StageName = label.StatusChecked;
        booking.Min_Arrival__c = date.Today();
        insert booking;
        //Stay__c stay = Utils.CreateStay(PersonAccount.Id, booking.Id);
        //insert stay;
        Account acc = [Select Id,Status__c,Status_Text__c
                       From Account
                       Where Id =: PartnerAccount.Id];    
        system.assertEquals(acc.Status_Text__c, acc.Status__c);
        acc = [Select Id,Lifecycle_status__pc,Status_Text__c
               From Account
               Where Id =: PersonAccount.Id];
        system.assertequals(acc.Status_Text__c,acc.Lifecycle_status__pc);
    }   
}