force-app/main/default/objects/Account/fields/TechIsNotFirst_03__c.field-meta.xml
<CustomField>
    <fullName>TechIsNotFirst_03__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to flag company accounts being processed in the batch Batch_PartnershipFieldsUpdate</description>
    <label>TechIsNotFirst_03</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Bookings_Checked_Count__c.field-meta.xml
<CustomField>
    <fullName>Bookings_Checked_Count__c</fullName>
    <label># Bookings Checked</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoiced_amount__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_Departure__c.field-meta.xml
<CustomField>
    <fullName>Max_Departure__c</fullName>
    <label>Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <label>Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PartnerCode__c.field-meta.xml
<CustomField>
    <fullName>PartnerCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (partner code)</relationshipLabel>
    <relationshipName>BookingsPartnerCode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Master_Booking.recordType-meta.xml
<RecordType>
    <fullName>Master_Booking</fullName>
    <active>true</active>
    <businessProcess>Master booking process</businessProcess>
    <label>Master Booking</label>
</RecordType>

force-app/main/default/objects/User/fields/BypassValidationRule__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/BypassWorkflow__c.field-meta.xml
<CustomField>
    <fullName>BypassWorkflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_PartnershipFieldsUpdate_Test.cls
/*
* Description: Test class for Batch_PartnershipFieldsUpdate , AP03_Opportunity , OpportunityHandler,Batch_DeflagAccount_PartnerFields 
* @author: TMA-EIL CG
* @date: 06-01-2020
*/


@isTest
public class Batch_PartnershipFieldsUpdate_Test {
    
    @isTest
    static void Batch_PartnershipFieldsUpdate(){
        
        Profile prof = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        
        User userTest = new User(Alias = 'systadm', Email='systadm@testorg.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = prof.Id, 
                                 TimeZoneSidKey='America/Los_Angeles', UserName='systadm@testorg.com');
        
        userTest.BypassValidationRule__c = true;
        userTest.BypassWorkflow__c = true;
        
        insert userTest;
        
        System.runAs(userTest){
            String companyAccRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Company').getRecordTypeId();
            String masterBookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Master_Booking').getRecordTypeId();
            String bookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Booking').getRecordTypeId();
            
            
            List<Account> listCompanyAcc = new List<Account>();
            List<Opportunity> listMasterBookings = new List<Opportunity>();
            List<Opportunity> listBookings = new List<Opportunity>();
            
            Account compAcc1 = new Account(Name = 'compAccTest', RecordTypeId = companyAccRTId,TechIsNotFirst_03__c=true);
            listCompanyAcc.add(compAcc1);
            Account compAcc2 = new Account(Name = 'compAccTest2', RecordTypeId = companyAccRTId);
            listCompanyAcc.add(compAcc2);
            insert listCompanyAcc;
            
            Opportunity masterBook1 = new Opportunity(Name = 'masterBookingTest1', Bookings_Checked_Count__c =2, StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today());
            listMasterBookings.add(masterBook1);
            Opportunity masterBook2 = new Opportunity(Name = 'masterBookingTest2', Bookings_Checked_Count__c=1, StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today());
            listMasterBookings.add(masterBook2);
            
            insert listMasterBookings;
            
            Opportunity book1 = new Opportunity(Name = 'Booking1', CloseDate = date.today(), StageName = 'Checked', Min_Arrival__c = date.today(),Max_Departure__c = date.today() + 1,Invoiced_amount__c=100, PartnerCode__c = compAcc1.id, RecordTypeId = bookingRTId,Master_Booking_FK__c=masterBook1.Id);
            listBookings.add(book1);
            
            Opportunity book2 = new Opportunity(Name = 'Booking2',  CloseDate = date.today(), StageName = 'Checked',Min_Arrival__c = date.today(),Max_Departure__c = date.today() + 2,Invoiced_amount__c=50, PartnerCode__c = compAcc1.id, RecordTypeId = bookingRTId,Master_Booking_FK__c=masterBook1.Id);
            listBookings.add(book2);
            
            Opportunity book3 = new Opportunity(Name = 'Booking3',  CloseDate = date.today(), StageName = 'Cancelled',Min_Arrival__c = date.today(),Max_Departure__c = date.today() + 2,Invoiced_amount__c=30, PartnerCode__c = compAcc2.id, RecordTypeId = bookingRTId,Master_Booking_FK__c=masterBook2.Id);
            listBookings.add(book3);
            
            Opportunity book4 = new Opportunity(Name = 'Booking4', CloseDate = date.today(), StageName = 'Checked',Min_Arrival__c = date.today(),Max_Departure__c = date.today() + 1,Invoiced_amount__c=20, PartnerCode__c = compAcc2.id, RecordTypeId = bookingRTId,Master_Booking_FK__c=masterBook2.Id);
            listBookings.add(book4);
            
            insert listBookings;
            
            
            
            
            test.startTest();
            
            map<String,String> mapPAId = new map<String,String>();
            mapPAId.put(listCompanyAcc[0].ID,'Test class error');
            mapPAId.put(listCompanyAcc[1].ID,'Test class error');
            
            Batch_PartnershipFieldsUpdate batchObj = new Batch_PartnershipFieldsUpdate(mapPAId,0);
            DataBase.executeBatch(batchObj);
            
            database.delete(listBookings[1].ID, false);
            
            batchObj = new Batch_PartnershipFieldsUpdate(mapPAId,3);
            DataBase.executeBatch(batchObj);
            
            String[] toAddresses = new String[] {'cynthia.geagea@ei-technologies.com'};
                String Subject = 'Batch Error : Batch_PartnershipFieldsUpdate ';
            
            Utils_Email.sendEmailApex(toAddresses, Subject,mapPAId);
            
            test.stopTest();
            
            
        }
    }
}