force-app/main/default/objects/Account/fields/TechIsNotFirst_03__c.field-meta.xml
<CustomField>
    <fullName>TechIsNotFirst_03__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to flag company accounts being processed in the batch Batch_PartnershipFieldsUpdate</description>
    <label>TechIsNotFirst_03</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Nights_PartnerShip__c.field-meta.xml
<CustomField>
    <fullName>Total_Nights_PartnerShip__c</fullName>
    <label>Total Nights PartnerShip</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Revenue_PartnerShip__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue_PartnerShip__c</fullName>
    <label>Total Revenue PartnerShip</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Transactions_PartnerShip__c.field-meta.xml
<CustomField>
    <fullName>Total_Transactions_PartnerShip__c</fullName>
    <label>Total Transactions PartnerShip</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Booking_Person_account__c.field-meta.xml
<CustomField>
    <fullName>Booking_Person_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Person account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bookings_Checked_Count__c.field-meta.xml
<CustomField>
    <fullName>Bookings_Checked_Count__c</fullName>
    <label># Bookings Checked</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Chambre__c.field-meta.xml
<CustomField>
    <fullName>Chambre__c</fullName>
    <label>#Chambre</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <label>Confirmation Number</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoiced_amount__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_Departure__c.field-meta.xml
<CustomField>
    <fullName>Max_Departure__c</fullName>
    <label>Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <label>Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_of_nights__c.field-meta.xml
<CustomField>
    <fullName>Number_of_nights__c</fullName>
    <formula>Max_Departure__c -  Min_Arrival__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label># Nights</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OnTheCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>OnTheCurrentYear__c</fullName>
    <formula>if(YEAR(Min_Arrival__c)== YEAR(Today()),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OnTheCurrentYear</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PartnerCode__c.field-meta.xml
<CustomField>
    <fullName>PartnerCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (partner code)</relationshipLabel>
    <relationshipName>BookingsPartnerCode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Master_Booking.recordType-meta.xml
<RecordType>
    <fullName>Master_Booking</fullName>
    <active>true</active>
    <businessProcess>Master booking process</businessProcess>
    <label>Master Booking</label>
</RecordType>

force-app/main/default/classes/OpportunityHandlerTest.cls
/*
* Description: Test class for OpportunityHandler
* @author: TMA-EIL CG
* @date:
*/
@isTest
public class OpportunityHandlerTest {
    @isTest
    public static void testMethod1()
    {
        String companyAccRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Company').getRecordTypeId();
        String masterBookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Master_Booking').getRecordTypeId();
        String bookRTID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Booking').getRecordTypeId();
        Account testAcc=Utils.CreatePersonAccount('accName',null);
        Account testAcc2=Utils.CreatePersonAccount('accName2',null);
        insert testAcc;
        insert testAcc2;
        
        Account compAcc1 = new Account(Name = 'compAccTest', RecordTypeId = companyAccRTId,TechIsNotFirst_03__c=true, BillingCountry = 'France', BillingPostalCode = '99999');
        insert compAcc1;
        
        Opportunity testOpp=Utils.CreateMasterBookingOpportunity('oppName',testAcc.id);
        testOpp.StageName=Label.StageNameBooking_Checked;
        testOpp.RecordTypeId = masterBookingRTId;
        insert testOpp;
        Opportunity masterBook1 = new Opportunity(Name = 'masterBookingTest1', Bookings_Checked_Count__c =2, StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today());
        insert masterBook1;
        
        Account getAcc=[Select id,Total_Transactions__pc from account where id=:testAcc.id limit 1];
        //System.assertEquals(getAcc.Total_Transactions__pc, 1);
        
        List<Opportunity> listOpp=new List<Opportunity>();
        Map<id,Opportunity> mapOpp=new Map<id,Opportunity>();
        listOpp.add(testOpp);
        mapOpp.put(testOpp.id,testOpp);
        /*MasterBookingHandler.FilterOpportunity(listOpp, null);
MasterBookingHandler.FilterOpportunity(listOpp, mapOpp);
MasterBookingHandler.FilterOpportunity(null, mapOpp);*/
        testOpp.Person_Account__c=testAcc2.id;
        update testOpp;
        Account getAcc2=[Select id,Total_Transactions__pc from account where id=:testAcc2.id limit 1];
        //System.assertEquals(getAcc.Total_Transactions__pc, 1);
        // delete testOpp;
        Account getAcc3=[Select id,Total_Transactions__pc from account where id=:testAcc2.id limit 1];
        //System.assertEquals(getAcc3.Total_Transactions__pc, 0);
        Opportunity testBook=Utils.CreateMasterBookingOpportunity('oppName',testAcc.id);
        testBook.StageName=Label.StageNameBooking_Checked;
        testBook.RecordTypeId = bookRTID;
        testBook.Confirmation_Number__c = '123';
        //testOpp.Number_of_nights__c = 1;
        testBook.Master_Booking_FK__c = testOpp.id;
        testBook.chambre__c = 1;
        testBook.Booking_Person_account__c = testAcc2.id;
        insert testBook;
        
        Opportunity book1 = new Opportunity(Name = 'Booking1', CloseDate = date.today(), StageName = Label.StageNameBooking_Checked, Min_Arrival__c = date.today(),Max_Departure__c = date.today() + 1,Invoiced_amount__c=100, PartnerCode__c = compAcc1.id, RecordTypeId = bookRTID,Master_Booking_FK__c=masterBook1.Id);
        insert book1;
        Account getAcc4=[Select id,TechIsNotFirst_03__c from account where id=:compAcc1.id limit 1];
        Opportunity getBook1=[Select id,Name,CloseDate,StageName,Min_Arrival__c,Max_Departure__c,OnTheCurrentYear__c, IsDeleted, Number_of_nights__c, PartnerCode__c,Invoiced_amount__c,RecordTypeId,Master_Booking_FK__c,PartnerCode__r.TechIsNotFirst_03__c,PartnerCode__r.Total_Transactions_PartnerShip__c, PartnerCode__r.Total_Revenue_PartnerShip__c, PartnerCode__r.Total_Nights_PartnerShip__c from Opportunity where id=:book1.id and PartnerCode__c=:getAcc4.id limit 1];
        
        Map<String,String> mapCongHotelNAme = OpportunityHandler.filterBookingsBatch_UpdateMB_ConfNb_HotelName(new List<opportunity>{testBook});
        Map<String,String> mapRoomStage = OpportunityHandler.filterBookingsBatch_UpdateMB_Nights_Rooms_StageCount(new List<opportunity>{testBook});
        Map<String,String> mapHotelCount = OpportunityHandler.filterBookings_Batch_HotelCountChecked(new List<opportunity>{testBook});
        Map<String,String> mapPartnerShipFieldUpdt = OpportunityHandler.filterBookings_Batch_PartnershipFieldsUpdate(new List<opportunity>{getBook1});
        
        
    }
}