force-app/main/default/objects/Account/fields/Total_Nights__c.field-meta.xml
<CustomField>
    <fullName>Total_Nights__c</fullName>
    <label>Total nights</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessAccountId__c.field-meta.xml
<CustomField>
    <fullName>BusinessAccountId__c</fullName>
    <formula>Person_Account__r.PersonContact.Current_Compagny__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BusinessAccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel_ID__c.field-meta.xml
<CustomField>
    <fullName>Hotel_ID__c</fullName>
    <formula>Hotel__r.Hotel_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_Departure__c.field-meta.xml
<CustomField>
    <fullName>Max_Departure__c</fullName>
    <label>Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <label>Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OnTheCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>OnTheCurrentYear__c</fullName>
    <formula>if(YEAR(Min_Arrival__c)== YEAR(Today()),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OnTheCurrentYear</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <summarizedField>Booking_Room_Line__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Booking_Room_Line__c.Booking_FK__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trip_Context__c.field-meta.xml
<CustomField>
    <fullName>Trip_Context__c</fullName>
    <label>Trip Context</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stay__c/Stay__c.object-meta.xml
<CustomObject>
    <description>Junction object between booking and Person account (Account object)</description>
    <label>Stay</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Stay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stay__c/fields/BusinessAccountId__c.field-meta.xml
<CustomField>
    <fullName>BusinessAccountId__c</fullName>
    <formula>Guest_account__r.PersonContact.Current_Compagny__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BusinessAccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Guest_account__c.field-meta.xml
<CustomField>
    <fullName>Guest_account__c</fullName>
    <label>Guest account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Guest Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Stays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Hotel_Id__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Id__c</fullName>
    <formula>Booking__r.Hotel__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Max_Departure__c.field-meta.xml
<CustomField>
    <fullName>Max_Departure__c</fullName>
    <formula>Booking__r.Max_Departure__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Max Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <formula>Booking__r.Min_Arrival__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Min Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/OnTheCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>OnTheCurrentYear__c</fullName>
    <formula>if(YEAR(Min_Arrival__c)== YEAR(Today()),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OnTheCurrentYear</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <formula>Booking__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <formula>TEXT(Booking__r.StageName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StageName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Trip_Context__c.field-meta.xml
<CustomField>
    <fullName>Trip_Context__c</fullName>
    <formula>Booking__r.Trip_Context__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trip Context</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP02_Stay.cls
/*
* Update the total nights field on person account and business account based on the opportunity max departure and min arrival (Person account on stay object)
* @author: Jenny Jawhar
* @date: 01/12/2017
* @Test: AP02_Stay_Test - AP04_Stay_Test
*/
public class AP02_Stay 
{
    /*
    public static void UpdateTotalNightsTotalRevenueFavoriteHotel(List<Stay__c> triggerNew,Map<Id,Stay__c> oldMap,List<Stay__c> triggerOld)
    {
         if(UserInfo.getUserId().contains(Label.InterfaceID)){  return;  }
        System.debug('##### AP02_Stay Start' );
        Set<string> ListAccountId = new Set<string>();
        Set<string> ListCurrentCompanyId = new Set<string>();       
        if(triggerNew != null)
        {
            for(Stay__c stay: triggerNew)
            {
                Stay__c oldStay=oldMap==null ? stay : oldMap.get(stay.Id);
                if(oldMap==null && String.isNotBlank(stay.Guest_account__c)) ListAccountId.add(stay.Guest_account__c);
                if(oldMap==null && String.isNotBlank(stay.BusinessAccountId__c)) ListCurrentCompanyId.add(stay.BusinessAccountId__c);                                        
                
                if(oldMap!=null && oldStay.Guest_Account__c!=stay.Guest_Account__c)
                {
                 if(String.isNotBlank(stay.Guest_Account__c))listAccountId.add(stay.Guest_account__c); 
                 if(String.isNotBlank(oldStay.Guest_Account__c))   ListAccountId.add(oldStay.Guest_Account__c);                     
                }
                if(oldMap!=null &&  oldStay.BusinessAccountId__c != stay.BusinessAccountId__c)
                {
                    if(String.isNotBlank(stay.BusinessAccountId__c)) ListCurrentCompanyId.add(stay.BusinessAccountId__c);
                    if(String.isNotBlank(oldStay.BusinessAccountId__c)) ListCurrentCompanyId.add(oldStay.BusinessAccountId__c);
                }
            }
        }
        else
        {
            for(Stay__c stay:triggerOld)
            {
                if((stay.Max_Departure__c!=null && stay.Min_Arrival__c!=null) || stay.Price__c!= null)
                {
                    if(String.isNotBlank(stay.Guest_Account__c))ListAccountId.add(stay.Guest_Account__c);
                    if(String.isNotBlank(stay.BusinessAccountId__c))  ListCurrentCompanyId.add(stay.BusinessAccountId__c);
                }
                if(stay.Hotel_Id__c!=null)
                {
                   if(String.isNotBlank(stay.Guest_account__c)) ListAccountId.add(stay.Guest_account__c);                    
                }
            }
        }
    
        if(ListAccountId.Size() > 0)
        {           
             
            list<Stay__c> listSelectedStay = [select Id,Min_Arrival__c,Max_Departure__c,Guest_account__c,StageName__c,Price__c
                                              ,Hotel_Id__c
                                                 from Stay__c
                                                 where ((OnTheCurrentYear__c =: true and ((StageName__c=:Label.StatusChecked  
                                                 And Max_Departure__c != null And Min_Arrival__c != null) or Price__c != 0))
                                                 or Hotel_Id__c!=null )
                                              	 and Guest_account__c in :ListAccountId];
       
            if(listSelectedStay != null && listSelectedStay.size()>0 ){
               update Night_Revenue_Account(listSelectedStay,true);  
                //Start AP04_Stay updateFavoriteHotel
                ////count for each account the total hotel per hotel_id
                map<string,Map<String,Integer>> mapAccount_hotel = new map<string,Map<String,Integer>>();
                for(Stay__c stay:listSelectedStay)
                {
                    if(String.isNotBlank(stay.Hotel_Id__c) && String.isNotBlank(stay.Guest_account__c) ){
                        
                        if(!mapAccount_hotel.containsKey(stay.Guest_account__c))
                        {
                            Map<String,Integer> temp = new Map<String,Integer>();
                            temp.put(stay.Hotel_Id__c,0);
                            mapAccount_hotel.put(stay.Guest_account__c,temp);
                        }
                        Map<String,Integer> temp = mapAccount_hotel.get(stay.Guest_account__c);
                        if(temp==null ){
                            temp = new Map<String,Integer>();
                            temp.put(stay.Hotel_Id__c,0);
                        }
                        else if(!temp.containskey(stay.Hotel_Id__c)){
                            temp.put(stay.Hotel_Id__c,0);
                        }
                        temp.put(stay.Hotel_Id__c,temp.get(stay.Hotel_Id__c) + 1);
                        mapAccount_hotel.put(stay.Guest_account__c,temp);
                    } 	
                }
                system.debug('listSelectedStay.size()' + listSelectedStay.size());
                system.debug('#### mapAccount_hotel' + mapAccount_hotel);
                integer maxValue=0;
                string maxHotel;
                List<Account> listAccToUpdate = new List<Account>();
                for(String Account_id : mapAccount_hotel.Keyset() )
                {
                    maxValue=0;
                    maxHotel=null;
                    Map<String,Integer> Hotel_count=mapAccount_hotel.get(Account_id);
                    if(Hotel_count!= null)
                    for(String hotel_id : Hotel_count.Keyset()){
                        if(Hotel_count.get(hotel_id) > maxValue){
                            maxHotel = hotel_id;
                            maxValue=Hotel_count.get(hotel_id); 
                        }
                    }
                    Account acc = new Account();
                    acc.id=Account_id;
                    if(maxHotel != null)
                    {
                        acc.Favorite_hotel__pc = maxHotel;
                    }
                    else
                    {
                        acc.Favorite_hotel__pc = null;
                    }
                     listAccToUpdate.add(acc);    
                }
                 update listAccToUpdate;   
                //END AP04_Stay updateFavoriteHotel
            }
           
        }
        if(ListCurrentCompanyId.Size()>0)
        {
            
            List<Stay__c> listStays = [Select Id, BusinessAccountId__c,Min_Arrival__c,Max_Departure__c,StageName__c,Price__c
                                       from Stay__c
                                       where BusinessAccountId__c IN: ListCurrentCompanyId                  
                                       And OnTheCurrentYear__c =: true and ((StageName__c=:Label.StatusChecked  
                                       And Max_Departure__c != null And Min_Arrival__c != null) or Price__c != 0)
                                       And Trip_Context__c =: Label.BusinessCustomerType];
            
             if(listStays != null && listStays.size()>0 ){
               update Night_Revenue_Account(listStays,false);  
            }
        }        
    }
    //AP03_Stay and AP02_Stay
    public static List<Account> Night_Revenue_Account(list<Stay__c> listStay,Boolean isGuest)
    {   
        List<Account> listAccToUpdate = new List<Account>();
        Map<id,Account> MapAccount  = new  Map<id,Account>();                                       
        
        for(Stay__c stay: listStay)
        {
            system.debug('## stay' + stay);
            String AccountOrQuest =null;
            if(isGuest){
                AccountOrQuest = stay.Guest_account__c;   
            } else{
              AccountOrQuest =   stay.BusinessAccountId__c ; 
            }
            
            if(String.isNotBlank(AccountOrQuest))
            {
                Boolean loadinMap=false;
                if(!MapAccount.containskey(AccountOrQuest)){
                    Account temp = new Account();
                    if(stay.StageName__c==Label.StatusChecked && stay.Max_Departure__c != null && stay.Min_Arrival__c != null)
                    {
                        if(!isGuest) {
                          temp.Total_Nights__c=0;  
                        }else{
                          temp.Total_nights__pc=0;  
                        }
                         loadinMap=true;
                    }
                    if(stay.Price__c!= null)
                    {
                        if(!isGuest) {
                          temp.Total_Revenue__c=0;  
                        }else{
                          temp.Total_Revenue__pc=0;  
                        } 
                        loadinMap=true;
                    }
                    if(loadinMap){
                        temp.id =AccountOrQuest;
                        MapAccount.put(AccountOrQuest,temp);
                    }
                    
                }
                
                if(MapAccount.containsKey(AccountOrQuest)){
                Account temp =MapAccount.get(AccountOrQuest);
                
                if(stay.StageName__c==Label.StatusChecked && stay.Max_Departure__c != null && stay.Min_Arrival__c != null)
                {
                    Integer numberDays = stay.Min_Arrival__c.daysBetween(stay.Max_Departure__c);
                    if(!isGuest ) { 
                        if(MapAccount.get(AccountOrQuest).Total_Nights__c == null){
                            MapAccount.get(AccountOrQuest).Total_Nights__c = 0;
                        }
                        temp.Total_Nights__c = (Integer)MapAccount.get(AccountOrQuest).Total_Nights__c  + numberDays; 
                    }else { 
                        if(MapAccount.get(AccountOrQuest).Total_nights__pc == null){
                            MapAccount.get(AccountOrQuest).Total_nights__pc = 0;
                        }
                        temp.Total_nights__pc = (Integer)MapAccount.get(AccountOrQuest).Total_nights__pc  + numberDays; 
                    } 
                }
                
                if(stay.Price__c!=null)
                {
                    if(!isGuest) { 
                        if(MapAccount.get(AccountOrQuest).Total_Revenue__c == null){
                            MapAccount.get(AccountOrQuest).Total_Revenue__c = 0;
                        }
                        temp.Total_Revenue__c = (Integer)MapAccount.get(AccountOrQuest).Total_Revenue__c  + stay.Price__c; 
                    }else{ 
                         if(MapAccount.get(AccountOrQuest).Total_Revenue__pc == null){
                            MapAccount.get(AccountOrQuest).Total_Revenue__pc = 0;
                        }
                        temp.Total_Revenue__pc = (Integer)MapAccount.get(AccountOrQuest).Total_Revenue__pc  + stay.Price__c; 
                    }  
                } 
                MapAccount.put(AccountOrQuest, temp) ;    
                }
            }
        }
        return MapAccount.values();
    }*/
}