force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Commercial_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Hotel_Name__c</fullName>
    <label>Commercial Hotel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/Opportunity_Hotel_Junction__c/Opportunity_Hotel_Junction__c.object-meta.xml
<CustomObject>
    <description>Objetc to link an opportunity to several hotel</description>
    <label>Opportunity_Hotel_Junction</label>
    <nameField>
        <label>Opportunity_Hotel_Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities_Hotels_Junction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Hotel_Junction__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance (Km)</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Hotel_Junction__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities_Hotels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AP01_Opportunity_Test.cls
/**
* 
* @version 1.00 23/10/2017
* @author Jenny Jawhar
* @CodeCoverage 93%
*/
@isTest
public class AP01_Opportunity_Test 
{
    @testSetup
    public static void InsertData()
    {
        list<Hotel__c> listHotelsToInsert = new list<Hotel__c>();
        integer i;       
        for(i=0; i<5; i++)
        {
            Hotel__c hotel = Utils.CreateHotel('Hotel'+i);           
            hotel.Commercial_Hotel_Name__c ='Hotel'+i;
            hotel.GPS_code__Latitude__s = 44;
            hotel.GPS_code__Longitude__s = 0;
            listHotelsToInsert.add(hotel);
        }
        for(i=0; i<5; i++)
        {
            Hotel__c hotel = Utils.CreateHotel('Hotel1'+i);           
            hotel.Commercial_Hotel_Name__c ='Hotel1'+i;
            hotel.GPS_code__Latitude__s = 34;
            hotel.GPS_code__Longitude__s = -118;
            listHotelsToInsert.add(hotel);
        }
        insert listHotelsToInsert;
        
        Opportunity Booking = Utils.CreateBookingOpportunity('Booking');
        Booking.StageName = label.ClosedWonStage;
        insert Booking;
    }
    public static testMethod void getListHotels()
    {       
        list<Hotel__c> listHotel = [Select Id
                                    From Hotel__c];
        list<Hotel__c> listActualHotel = AP01_Opportunity.getHotels();       
        system.assertEquals(listHotel.size(), listActualHotel.size());    
    }
  
    public static testMethod void testCreateOLI()
    {
        Opportunity Booking = [Select Id 
                               From Opportunity
                               Where Name = 'Booking' 
                               Limit 1];
        
        string listPredictions = AP01_Opportunity.getAddressAutoComplete('los');
        system.assertEquals(label.BodyAutoCompleteAddress,listPredictions);
        string address = 'Los Angeles,USA';
        
        string bodylatlong = AP01_Opportunity.getlocationlatlong(address);       
        system.assertEquals(label.BodyLongLat,bodylatlong);       
        
        list<Hotel__c> listHotels = AP01_Opportunity.Filter('34.05,-118.24');
        system.assertEquals(5, listHotels.size());
        
        list<Hotel__c> listHotel = [Select Id, Distance__c
                                    From Hotel__c
                                    Where Id IN: listHotels Limit 2];
        AP01_Opportunity.createHotel(Booking.Id,listHotel, address);
        list<Opportunity_Hotel_Junction__c> listJunction = [Select Id
                                                           From Opportunity_Hotel_Junction__c];
        system.assertEquals(2, listJunction.Size());        
    }
}