force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Max_Departure__c.field-meta.xml
<CustomField>
    <fullName>Max_Departure__c</fullName>
    <label>Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <label>Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trip_Context__c.field-meta.xml
<CustomField>
    <fullName>Trip_Context__c</fullName>
    <label>Trip Context</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/objects/Stay__c/Stay__c.object-meta.xml
<CustomObject>
    <description>Junction object between booking and Person account (Account object)</description>
    <label>Stay</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Stay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stay__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000R4WJ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Guest Account</relationshipLabel>
    <relationshipName>Stays</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Max_Departure__c.field-meta.xml
<CustomField>
    <fullName>Max_Departure__c</fullName>
    <formula>Booking__r.Max_Departure__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Max Departure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <formula>Booking__r.Min_Arrival__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Min Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Trip_Context__c.field-meta.xml
<CustomField>
    <fullName>Trip_Context__c</fullName>
    <formula>Booking__r.Trip_Context__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trip Context</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/batch_ap02_stay_test.cls
/**
* 
* @version 1.00 
* @author 
* @CodeCoverage 
*/
@isTest
public class batch_ap02_stay_test {
	/*
    private static testMethod void InsertUpdateDeleteStay(){
        //insert Account      
        Account PartnerAccount = Utils.CreatePartnerAccount('Partner',null);      
        insert PartnerAccount;
        Account PersonAccount =  Utils.CreatePersonAccount('Person', PartnerAccount.Id);                      
        insert PersonAccount;
        //insert Opportunities
        list<Hotel__c> listHotel = new list<Hotel__c>();
        Hotel__c hotel1 = Utils.CreateHotel('123');
        listHotel.add(hotel1);
        Hotel__c hotel2 = Utils.CreateHotel('456');
        listHotel.add(hotel2);
        Hotel__c hotel3 = Utils.CreateHotel('789');
        listHotel.add(hotel3);
        insert listHotel;
        List<Opportunity> ListOpp = new List<Opportunity>(); 
        Opportunity opp1 = Utils.CreateBookingOpportunity('B1');            
        opp1.Min_Arrival__c = date.Today();
        opp1.Max_Departure__c = date.Today() + 1;         
        opp1.StageName=Label.StatusChecked; 
        opp1.Trip_Context__c =Label.BusinessCustomerType;
        opp1.Hotel__c = hotel1.Id;
        ListOpp.add(opp1);
        Opportunity opp2 = Utils.CreateBookingOpportunity('B2');            
        opp2.Min_Arrival__c = date.Today();
        opp2.Max_Departure__c = date.Today() + 2;         
        opp2.StageName=Label.StatusChecked; 
        opp2.Hotel__c = hotel2.Id;
        ListOpp.add(opp2);
        insert ListOpp; 
        //insert list of stays
        list<Stay__c> listStay = new list<Stay__c>();
        Stay__c stay1 = Utils.CreateStay(PersonAccount.Id,opp1.Id);
        listStay.add(stay1);    
        Stay__c stay2 = Utils.CreateStay(PersonAccount.Id,opp2.Id);
        listStay.add(stay2);  
        test.startTest();
        insert listStay;
        Account acc=[Select Id,Total_nights__pc
                     From Account
                     Where Id=:PersonAccount.Id];            
        System.assertEquals(3,acc.Total_nights__pc);
        //Delete Opportunity
        delete (stay2);
        acc=[Select Id,Total_nights__pc
             From Account
             Where Id=:PersonAccount.Id];             
        System.assertEquals(1,acc.Total_nights__pc);
        //update Opportunity    
        stay1.Booking__c = opp2.Id;      
        update (stay1);
        acc=[Select Id,Total_nights__pc
             From Account
             Where Id=:PersonAccount.Id];        
        //System.assertEquals(2,acc.Total_nights__pc);
        Database.executeBatch(new batch_ap02_Stay());
        test.stopTest();
    }*/
}