force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Hotel  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/Commercial_Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Hotel_Name__c</fullName>
    <label>Commercial Hotel Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/expireDate__c.field-meta.xml
<CustomField>
    <fullName>expireDate__c</fullName>
    <label>expireDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Hotel_Validite_France__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Validite_France__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel Validité</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Hotel__c.Country__c</field>
            <operation>equals</operation>
            <value>France</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Invitations France</relationshipLabel>
    <relationshipName>Invitation_France</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Prestation_offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_offerte__c</fullName>
    <label>Prestation offerte</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>6000</fullName>
                <label>Une nuit en chambre 1-2 personnes</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>Une nuit en chambre familiale</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>Une nuit en chambre 1-2 personnes avec petits déjeuners</label>
            </value>
            <value>
                <fullName>6003</fullName>
                <label>Une nuit en chambre familiale avec petits déjeuners</label>
            </value>
            <value>
                <fullName>6004</fullName>
                <label>Un petit déjeuner</label>
            </value>
            <value>
                <fullName>6005</fullName>
                <label>Deux petits déjeuners</label>
            </value>
            <value>
                <fullName>6006</fullName>
                <label>Trois petits déjeuners</label>
            </value>
            <value>
                <fullName>6007</fullName>
                <label>Quatre petits déjeuners</label>
            </value>
            <value>
                <fullName>60 euros</fullName>
                <label>Voucher 60 euros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Validite__c.field-meta.xml
<CustomField>
    <fullName>Validite__c</fullName>
    <description>(read only dès la création, always &quot;Du lundi au dimanche&quot; for IR)</description>
    <label>Validité</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9000</fullName>
                <default>true</default>
                <label>Du lundi au dimanche</label>
            </value>
            <value>
                <fullName>Les vendredis, samedis, dimanches ou jours fériés</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/recordTypes/OC.recordType-meta.xml
<RecordType>
    <fullName>OC</fullName>
    <active>true</active>
    <description>Opération Commerciale-C&apos;est pour afficher/masquer les champs à la page de Consultation/Modification des Vouchers</description>
    <label>OC</label>
</RecordType>

force-app/main/default/classes/VFC01_GetRelatedVouchers.cls
/*
* Description: Class to get the list of vouchers related to Master voucher OC
* @author: TMA JK
* @date: 06/10/2020
* @Test: VFC01_GetRelatedVouchers_Test
* @Coverage: 80%
*/
public with sharing class VFC01_GetRelatedVouchers {
    
    Id recordId;
    
    public ApexPages.StandardController relatedVoucher {get; set;}
    public list<Voucher__c> RelatedVouchers {get; set;}
    
    
    public VFC01_GetRelatedVouchers(ApexPages.StandardController cntrl) {
        
        //recordId = cntrl.getId(); //Commented by TMA-EIT CG CRMSS-884 27/10/2020
        recordId = apexpages.currentpage().getparameters().get('id');//Added by TMA-EIT CG CRMSS-884 27/10/2020
        
        RelatedVouchers = [select id,Code_OC__c,Zone_de_validite_OC__c,toLabel(Prestation_offerte__c),Nom_Prenom_du_client__c,Offert_occasion_de__c,toLabel(Validite__c),expireDate__c,Hotel_Validite_France__r.Commercial_Hotel_Name__c 
                           from Voucher__c 
                           where Master_Voucher_OC__c=: recordId];
        
        system.debug('recordId ' + recordId);
        
    }
}