force-app/main/default/objects/InvitationValorisationmdt__mdt/InvitationValorisationmdt__mdt.object-meta.xml
<CustomObject>
    <label>InvitationValorisation</label>
    <pluralLabel>InvitationValorisations</pluralLabel>
</CustomObject>

force-app/main/default/objects/InvitationValorisationmdt__mdt/fields/Prestation_offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_offerte__c</fullName>
    <label>Prestation offerte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvitationValorisationmdt__mdt/fields/Valorisation__c.field-meta.xml
<CustomField>
    <fullName>Valorisation__c</fullName>
    <label>Valorisation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/Master_Voucher__c.object-meta.xml
<CustomObject>
    <label>Master Voucher OC</label>
    <nameField>
        <displayFormat>MOC-{00000000}</displayFormat>
        <label>Master Voucher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Vouchers OC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Voucher__c/fields/Date_d_expiration__c.field-meta.xml
<CustomField>
    <fullName>Date_d_expiration__c</fullName>
    <label>Date d&apos;expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Dur_e_de_validit__c.field-meta.xml
<CustomField>
    <fullName>Dur_e_de_validit__c</fullName>
    <defaultValue>&apos;2 mois&apos;</defaultValue>
    <label>Durée de validité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6 mois</fullName>
            </value>
            <value>
                <fullName>2 mois</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Nom_Pr_nom_client__c.field-meta.xml
<CustomField>
    <fullName>Nom_Pr_nom_client__c</fullName>
    <label>Prénom / Nom client</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Num_ro_de_t_l_phone_client__c.field-meta.xml
<CustomField>
    <fullName>Num_ro_de_t_l_phone_client__c</fullName>
    <label>Numéro de téléphone client</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Personal_account__c.field-meta.xml
<CustomField>
    <fullName>Personal_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Vouchers OC (Personal account)</relationshipLabel>
    <relationshipName>Master_Vouchers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Pr_nom_Nom_de_l_m_tteur__c.field-meta.xml
<CustomField>
    <fullName>Pr_nom_Nom_de_l_m_tteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prénom / Nom de l&apos;émetteur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Master_Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Prestation_Offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_Offerte__c</fullName>
    <label>Prestation Offerte</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Une nuit en chambre 1-2 personnes</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre familiale</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre 1-2 personnes avec petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Une nuit en chambre familiale avec petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Un petit déjeuner</fullName>
            </value>
            <value>
                <fullName>Deux petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Trois petits déjeuners</fullName>
            </value>
            <value>
                <fullName>Quatre petits déjeuners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Service_emetteur__c.field-meta.xml
<CustomField>
    <fullName>Service_emetteur__c</fullName>
    <defaultValue>$User.Department</defaultValue>
    <description>Filled by the user or automatically with the user&apos;s department if not filled by the user</description>
    <label>Service émetteur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BUILD</fullName>
            </value>
            <value>
                <fullName>DIRECTION GENERALE</fullName>
            </value>
            <value>
                <fullName>MARKETING</fullName>
            </value>
            <value>
                <fullName>RH</fullName>
            </value>
            <value>
                <fullName>SRC</fullName>
            </value>
            <value>
                <fullName>SRC Promos</fullName>
            </value>
            <value>
                <fullName>VENTE CORPORATE</fullName>
            </value>
            <value>
                <fullName>VENTE LOISIRS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Voucher__c/fields/Valorisation__c.field-meta.xml
<CustomField>
    <fullName>Valorisation__c</fullName>
    <label>Valorisation €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AP01_MasterVoucher.cls
/*
* Description: Class to fill the information of the master voucher on before insert CRMSS-826
* @author: TMA JK
* @date: 01/10/2020
* @Test: AP01_MasterVoucher_Test
* @Coverage: 89%
*/

public class AP01_MasterVoucher {
    
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////Fill Information On the Master Voucher /////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    public static void fillMasterVoucherInformationInsert(list<Master_Voucher__c> listMasterVoucher){
        
        //Get only user id and contact / person account id that need to be fetched
        List<id> listUserIdToCheck = new List<Id>();
        List<id> listContactIdToCheck = new List<Id>();
        
        for(Master_Voucher__c masterVoucher : listMasterVoucher){
            
            if(masterVoucher.OwnerId != null)
                listUserIdToCheck.add(masterVoucher.OwnerId);
            
            if(masterVoucher.Personal_account__c != null)
                listContactIdToCheck.add(masterVoucher.Personal_account__c);
        }
        
        //Get Custom settings data for the value of valorisation
        List<InvitationValorisationmdt__mdt> listInvitationValorisation = [select Prestation_offerte__c,Valorisation__c
                                                                      from InvitationValorisationmdt__mdt
                                                                      Where object__c = 'Master Voucher'];
        //Set  a map of prestation offerte -> Valorisation
        Map<String,Decimal> mapPrestaValorisation = new Map<String,Decimal>();
        
        For(InvitationValorisationmdt__mdt val :listInvitationValorisation){
            mapPrestaValorisation.put(val.Prestation_offerte__c, val.Valorisation__c);           
        }
        
        
        //Fetch the info of the User and Contact / Person Account
        Map<Id,User> mapUser;
        
        if(listUserIdToCheck != null && listUserIdToCheck.size() >0 )
            mapUser = new Map<Id,User> ([Select id,division,Department
                                         From User
                                         Where isActive = True and id in :listUserIdToCheck]);
        Map<Id,Contact> mapContact;
        
        if(listContactIdToCheck != null && listContactIdToCheck.size() >0 )
            mapContact = new Map<Id,Contact> ([Select id,name, MobilePhone, Email
                                               From Contact
                                               Where id in :listContactIdToCheck]);
        String MasterVoucherRT = Schema.SObjectType.Master_Voucher__c.getRecordTypeInfosByDeveloperName().get(Label.MasterVoucher_RT_Consultation_DevName).getRecordTypeId();
        
        //Fill the Information on the Master Voucher Based on the data fetched
        for(Master_Voucher__c masterVoucher : listMasterVoucher){
            
            if(Schema.SObjectType.Master_Voucher__c.getRecordTypeInfosByDeveloperName().get(Label.MasterVoucher_RT_OnCreation_DevName) != null && masterVoucher.RecordTypeID  == Schema.SObjectType.Master_Voucher__c.getRecordTypeInfosByDeveloperName().get(Label.MasterVoucher_RT_OnCreation_DevName).getRecordTypeId()){
                masterVoucher.RecordTypeID = MasterVoucherRT;
            }
            
            //Fill prenom nom emetteur
            masterVoucher.Pr_nom_Nom_de_l_m_tteur__c = masterVoucher.OwnerId;
      
            //Fill Service emetteur TMA-EIT CG CRMSS-960 26/11/2020
            if(masterVoucher.OwnerId != null && mapUser.containskey(masterVoucher.OwnerId) ){
                
                if(mapUser.get(masterVoucher.OwnerId).Department != null && mapUser.get(masterVoucher.OwnerId).Department != 'SRC'){
                    
                    masterVoucher.Service_emetteur__c = mapUser.get(masterVoucher.OwnerId).Department;
                }
            }
            
            //Fill person account information
            if(masterVoucher.Personal_account__c != null &&  mapContact.containskey(masterVoucher.Personal_account__c)){
                
                masterVoucher.Nom_Pr_nom_client__c = mapContact.get(masterVoucher.Personal_account__c).name;
                masterVoucher.Email_client__c = mapContact.get(masterVoucher.Personal_account__c).Email;
                masterVoucher.Num_ro_de_t_l_phone_client__c = mapContact.get(masterVoucher.Personal_account__c).mobilePhone;
            }
            
            //Fill valorisation
            if(masterVoucher.Prestation_offerte__c != null && mapPrestaValorisation.containsKey(masterVoucher.Prestation_offerte__c)){
                masterVoucher.Valorisation__c = mapPrestaValorisation.get(masterVoucher.Prestation_offerte__c);
            }
            
            //Fill date d'expiration
            if(masterVoucher.Dur_e_de_validit__c != null ){
                if(masterVoucher.Dur_e_de_validit__c == Label.AP01_MasterVoucher_Duree2Mois )
                    masterVoucher.Date_d_expiration__c = date.today().addmonths(2);
                
                if(masterVoucher.Dur_e_de_validit__c == Label.AP01_MasterVoucher_Duree6Mois )
                    masterVoucher.Date_d_expiration__c = date.today().addmonths(6);
            }
        }
    }
}