force-app/main/default/objects/Loyalty_Card__c/Loyalty_Card__c.object-meta.xml
<CustomObject>
    <label>Loyalty Card</label>
    <nameField>
        <displayFormat>LoyaltyCard-{0000}</displayFormat>
        <label>Loyalty Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Card__c/fields/E_Club_Renewal_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>E_Club_Renewal_Period_End_Date__c</fullName>
    <label>E-Club Renewal Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loyalty_Card__c/fields/E_Club_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>E_Club_Start_Date__c</fullName>
    <label>E-Club Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loyalty_Card__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loyalty Cards</relationshipLabel>
    <relationshipName>Loyalty_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_LoyaltyCardSubcription_Test.cls
/**
* 
* @version 1.00 09/08/2018
* @author Joyce Saidy
* @CodeCoverage 88%
*/
@isTest
public class Batch_LoyaltyCardSubcription_Test {
    static testMethod void testLoyaltyCardSubcription(){
        
        Account acc = new account();
        acc.lastName='Test';
        acc.RecordTypeId=Label.PersonAccountRecordTypeId; 
        insert acc;
        
        Loyalty_Card__c LC= new Loyalty_Card__c();
        LC.Person_Account__c=acc.id;
        LC.E_Club_Start_Date__c=system.today();
        LC.E_Club_Renewal_Period_End_Date__c=system.today();
        insert LC;
        
        Test.startTest();
        Database.executeBatch(new Batch_LoyaltyCardSubcription());
        Test.stopTest(); 
        
    }
}