force-app/main/default/objects/Opportunity/fields/Booking_Person_account__c.field-meta.xml
<CustomField>
    <fullName>Booking_Person_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Person account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Masterbooking_Person_account__c.field-meta.xml
<CustomField>
    <fullName>Masterbooking_Person_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Masterbooking Person account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Masterbookings</relationshipLabel>
    <relationshipName>Masterbookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/classes/Batch_repriseMB_test.cls
@isTest
public class Batch_repriseMB_test {
    @isTest
    static void Batch_repriseMB_test(){
        
        Account PartnerAccount = Utils.CreatePartnerAccount('Partner',null);      
        insert PartnerAccount;
        Account PersonAccount = Utils.CreatePersonAccount('Person', PartnerAccount.Id);                      
        insert PersonAccount;
        
        Opportunity masterBooking = Utils.CreateMasterBookingOpportunity('MasterBooking', PersonAccount.Id);
        masterBooking.Person_Account__c = PersonAccount.Id;
        masterBooking.StageName =  label.ClosedWonStage;
        masterBooking.CloseDate = date.today();
        
        Opportunity booking = Utils.CreateBookingOpportunity('Booking');
        booking.Person_Account__c = PersonAccount.Id;
        booking.StageName =  label.ClosedWonStage;
        booking.CloseDate = date.today();
        
        insert (new List<Opportunity>{masterBooking, booking});
        booking.Booking_Person_account__c = null;
        masterBooking.Masterbooking_Person_account__c = null;
        update (new List<Opportunity>{masterBooking, booking});
        database.executeBatch(new Batch_repriseMB());        
    }
}