force-app/main/default/objects/Opportunity/fields/Booking_Person_account__c.field-meta.xml
<CustomField>
    <fullName>Booking_Person_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Person account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Masterbooking_Person_account__c.field-meta.xml
<CustomField>
    <fullName>Masterbooking_Person_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Masterbooking Person account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Masterbookings</relationshipLabel>
    <relationshipName>Masterbookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_repriseMB.cls
Global class Batch_repriseMB implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        String MBRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Label.MasterBookingRTDevName).getRecordTypeId();
        String BRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Label.BookingRecordTypeName).getRecordTypeId();
        string query='select id,person_account__c,Booking_Person_account__c, Masterbooking_Person_account__c, RecordTypeId '+
            ' from opportunity where Person_Account__c != null and ((RecordTypeId  = :BRT and Booking_Person_account__c = null) or (RecordTypeId  = :MBRT and Masterbooking_Person_account__c = null))' ;
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Opportunity> listOpp){
        List<Opportunity> listOppToUpdate = new List<Opportunity>();
        for(Opportunity opp: listOpp){
            if(opp.Person_Account__c != null){
                if(opp.RecordTypeId == Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Label.MasterBookingRTDevName).getRecordTypeId()){
                    opp.Masterbooking_Person_account__c = opp.Person_Account__c;
                    listOppToUpdate.add(opp);
                }else if(opp.RecordTypeId == Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Label.BookingRecordTypeName).getRecordTypeId()){
                    opp.Booking_Person_account__c = opp.Person_Account__c;
                    listOppToUpdate.add(opp);
                }
            }
        }
        if(listOppToUpdate != null && listOppToUpdate.size()>0){
            update listOppToUpdate;
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
}