force-app/main/default/objects/Opportunity/fields/Booking_Person_account__c.field-meta.xml
<CustomField>
    <fullName>Booking_Person_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Person account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OldParent__c.field-meta.xml
<CustomField>
    <fullName>OldParent__c</fullName>
    <label>OldParent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OldParentAccount__c.field-meta.xml
<CustomField>
    <fullName>OldParentAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OldParentAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings / Opportunities (OldParentAccount)</relationshipLabel>
    <relationshipName>Bookings_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP17_Opportunity.cls
/*
* Description: CRMSS-401
* @author: TMA-EIL JKA
* @date: 
* @Test: Batch_HotelCountChecked_Test || Batch_FirstLastBooking_Test
* @Coverage:100% || 83%
*/
public without sharing class  AP17_Opportunity {
    
    Public static void  FillOldPArent(List<Opportunity> listOPP, map<id,opportunity> mapOldOpp){
        
        for(opportunity opp : listOPP){
            
            if(opp.Booking_Person_account__c != mapOldOpp.get(opp.id).Booking_Person_account__c && mapOldOpp.get(opp.id).Booking_Person_account__c != null){
                
                opp.OldParentAccount__c = mapOldOpp.get(opp.id).Booking_Person_account__c;
            }
            
            if(opp.Person_Account__c != mapOldOpp.get(opp.id).Person_Account__c && mapOldOpp.get(opp.id).Person_Account__c != null){
                
                opp.OldParent__c = mapOldOpp.get(opp.id).Person_Account__c;
            }
        }
    }
    
}