force-app/main/default/objects/Opportunity/fields/Booking_Person_account__c.field-meta.xml
<CustomField>
    <fullName>Booking_Person_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Person account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Masterbooking_Person_account__c.field-meta.xml
<CustomField>
    <fullName>Masterbooking_Person_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Masterbooking Person account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Masterbookings</relationshipLabel>
    <relationshipName>Masterbookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP08_Opportunity.cls
/**
 * @author TMA-EI JK
 * @date 28/03/2019
 * @description fill the lookup Masterbooking_Person_account__c or Booking_Person_account__c depending on opp record type
 */
public without sharing class AP08_Opportunity {
   
    public static void fillBookingLookups(List<Opportunity> insertedOpps){
         system.debug('@@@@@ in AP08_Opportunity fillBookingLookups');
        for(Opportunity opp: insertedOpps){
            if(opp.Person_Account__c != null){
                if(opp.RecordTypeId == Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Label.MasterBookingRTDevName).getRecordTypeId()){
                    opp.Masterbooking_Person_account__c = opp.Person_Account__c;
                }else if(opp.RecordTypeId == Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Label.BookingRecordTypeName).getRecordTypeId()){
                    opp.Booking_Person_account__c = opp.Person_Account__c;
                }
            }
        }
    }
}