force-app/main/default/objects/Opportunity/fields/Chambre__c.field-meta.xml
<CustomField>
    <fullName>Chambre__c</fullName>
    <label>#Chambre</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Master_Booking.recordType-meta.xml
<RecordType>
    <fullName>Master_Booking</fullName>
    <active>true</active>
    <businessProcess>Master booking process</businessProcess>
    <label>Master Booking</label>
</RecordType>

force-app/main/default/classes/AP13_Opportunity_Test.cls
/*
* Description: Test Class for AP13_Opportunity 
* @author: TMA-EI JKA
* @date: 02/10/2019
*/

@isTest
public class AP13_Opportunity_Test {
    
    @isTest
    public static void CalculateRoomTest(){
        
        String masterBookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Master_Booking').getRecordTypeId();
        String bookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Booking').getRecordTypeId();
        
        Opportunity MB1 = new Opportunity(Name = 'MB1', StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today());
        insert MB1;
        
        Opportunity MB2 = new Opportunity(Name = 'MB2', StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today());
        insert MB2;
        
        Opportunity MB3 = new Opportunity(Name = 'MB3', StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today());
        insert MB3;
        
        list<Opportunity> listOpp =  new list<Opportunity>();
        
        
        Opportunity Opp1 = new Opportunity(Name = 'Booking1', StageName= 'Checked', CloseDate=date.Today(), recordTypeId = bookingRTId, chambre__c =1, Master_Booking_FK__c = MB1.id);
        listOpp.add(Opp1);
        Opportunity Opp2 = new Opportunity(Name = 'Booking2', StageName= 'Checked', CloseDate=date.Today(), recordTypeId = bookingRTId, chambre__c =2, Master_Booking_FK__c = MB1.id);
        listOpp.add(Opp2);
        Opportunity Opp3 = new Opportunity(Name = 'Booking3', StageName= 'Checked', CloseDate=date.Today(), recordTypeId = bookingRTId, chambre__c =2, Master_Booking_FK__c = MB1.id);
        listOpp.add(Opp3);
        Opportunity Opp4 = new Opportunity(Name = 'Booking4', StageName= 'Checked', CloseDate=date.Today(), recordTypeId = bookingRTId, chambre__c =1, Master_Booking_FK__c = MB2.id);
        listOpp.add(Opp4);
        Opportunity Opp5 = new Opportunity(Name = 'Booking5', StageName= 'Checked', CloseDate=date.Today(), recordTypeId = bookingRTId, chambre__c =1, Master_Booking_FK__c = MB3.id);
        listOpp.add(Opp5);
        
        test.startTest();
        
        Database.insert(listOpp, false);
        
        Opp2.chambre__c =1;
        Opp3.Master_Booking_FK__c = MB2.Id;
        Database.update(listOpp, false);
        
        Database.delete(Opp1, false);
        
        test.stopTest();
        
    }
}