force-app/main/default/objects/Opportunity/fields/Confirmation_Number__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Number__c</fullName>
    <label>Confirmation Number</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Master_Booking_FK__c.field-meta.xml
<CustomField>
    <fullName>Master_Booking_FK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Booking FK</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master Booking</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Master_Booking.recordType-meta.xml
<RecordType>
    <fullName>Master_Booking</fullName>
    <active>true</active>
    <businessProcess>Master booking process</businessProcess>
    <label>Master Booking</label>
</RecordType>

force-app/main/default/objects/User/fields/BypassValidationRule__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP10_Opportunity_Test.cls
/*
* Description: Test Class for AP10_Opportunity 
* @author: TMA-EI Cynthia Geagea
* @date: 16/08/2019
*/

@isTest
public class AP10_Opportunity_Test {
    
    @isTest
    public static void bookingsStageCountOnMBTest(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User testUser = new User(Alias = 'systadm', Email='systadm@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='systadm@testorg.com');
        testUser.BypassValidationRule__c = true;
        insert testUser;
        
        system.runAs(testUser){
            
            String bookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Booking').getRecordTypeId();
            String masterBookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Master_Booking').getRecordTypeId();
            
            list<Opportunity> listMasterBookings = new list<Opportunity>();
            
            Opportunity masterBook1 = new Opportunity(Name = 'masterBookingTest1', StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today());
            listMasterBookings.add(masterBook1);
            Opportunity masterBook2 = new Opportunity(Name = 'masterBookingTest2', StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today());
            listMasterBookings.add(masterBook2);
            
            insert listMasterBookings;
            
            list<Opportunity> listBookings = new list<Opportunity>();
            
            Opportunity book1 = new Opportunity(Name = 'Booking1', CloseDate = date.today(), StageName = 'Cancelled', RecordTypeId = bookingRTId, Master_Booking_FK__c = masterBook1.id);
            listBookings.add(book1);
            
            Opportunity book2 = new Opportunity(Name = 'Booking2', CloseDate = date.today(), StageName = 'Error', RecordTypeId = bookingRTId, Master_Booking_FK__c = masterBook1.id);
            listBookings.add(book2);
            
            Opportunity book3 = new Opportunity(Name = 'Booking3', CloseDate = date.today(), StageName = 'No Show', RecordTypeId = bookingRTId, Master_Booking_FK__c = masterBook1.id);
            listBookings.add(book3);
            
            Opportunity book4 = new Opportunity(Name = 'Booking4', CloseDate = date.today(), StageName = 'Checked', RecordTypeId = bookingRTId, Master_Booking_FK__c = masterBook1.id);
            listBookings.add(book4);
            
            Opportunity book5 = new Opportunity(Name = 'Booking5', CloseDate = date.today(), StageName = 'Booked', RecordTypeId = bookingRTId, Master_Booking_FK__c = masterBook1.id);
            listBookings.add(book5);
            
            //Added by TMA Cynthia Geagea - CRMSS 284-258 - 16/09/2019 - Start
            Opportunity book6 = new Opportunity(Name = 'Booking1', CloseDate = date.today(), Confirmation_Number__c = '010101', StageName = 'Cancelled', RecordTypeId = bookingRTId, Master_Booking_FK__c = masterBook1.id);
            listBookings.add(book6);
            
            Opportunity book7 = new Opportunity(Name = 'Booking2', CloseDate = date.today(), Confirmation_Number__c = '010101', StageName = 'Cancelled', RecordTypeId = bookingRTId, Master_Booking_FK__c = masterBook1.id);
            listBookings.add(book7);
            //Added by TMA Cynthia Geagea - CRMSS 284-258 - 16/09/2019 - End
            
            test.startTest();
            
            database.insert(listBookings, false);
            
            book5.StageName = 'Cancelled';
            book4.Master_Booking_FK__c = masterBook2.Id;
            database.update(listBookings, false);
            
            //Added by TMA Cynthia Geagea - CRMSS 284-258 - 16/09/2019 - Start
            book7.Master_Booking_FK__c = masterBook2.id;
            database.update(listBookings, false);
            
            book6.Master_Booking_FK__c = masterBook2.Id;
            database.update(listBookings, false);
            //Added by TMA Cynthia Geagea - CRMSS 284-258 - 16/09/2019 - End
            
           // database.delete(book3, false);
            
            //Added by TMA Cynthia Geagea - CRMSS 284-258 - 16/09/2019 - Start
            database.delete(book6, false);
            database.delete(book7, false);
            //Added by TMA Cynthia Geagea - CRMSS 284-258 - 16/09/2019 - End
            
            test.stopTest();
            
        }
    }

}