force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP014_Opportunity.cls
public without sharing class AP014_Opportunity {
    Public Static Void ReCalculateContract(list<opportunity> listOppNew, map<id,opportunity> mapOppOld){
        set<id> setOppId = new set<id>();
        for(Opportunity opp :listOppNew){
            if(opp.accountId != mapOppOld.get(opp.ID).accountId || opp.contact__c != mapOppOld.get(opp.ID).contact__c){
                setOppId.add(opp.id);
            }
        }
        List<Contract> listContractToUpdate = [select id,recordtypeId,opportunity__c from contract where opportunity__c in :setOppId];
        if(listContractToUpdate != null && listContractToUpdate.size()>0){
            system.debug('@@@@ ap014 Change ');
            AP02_Contract.fillContactAndAccount(listContractToUpdate,null,True);
        }
    }

}