force-app/main/default/objects/Opportunity/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Master_Booking.recordType-meta.xml
<RecordType>
    <fullName>Master_Booking</fullName>
    <active>true</active>
    <businessProcess>Master booking process</businessProcess>
    <label>Master Booking</label>
</RecordType>

force-app/main/default/objects/User/fields/BypassValidationRule__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/BypassWorkflow__c.field-meta.xml
<CustomField>
    <fullName>BypassWorkflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_Account_BookingDates_Test.cls
/*
* Description: Test Class for Batch_Account_BookingDates. This class must be run with the triggers AfterInsertOpportunity and AfterUpdateOpportunity bypassed
* @author: TMA-EIL JKA
* @date: 03/12/2019
*/

@isTest
public class Batch_Account_BookingDates_Test {
    
    @isTest
    static void batchAccBookDateTest(){
        
        Profile prof = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        
        User userTest = new User(Alias = 'systadm', Email='systadm@testorg.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = prof.Id, 
                                 TimeZoneSidKey='America/Los_Angeles', UserName='systadm@testorg.com');
        
        userTest.BypassValidationRule__c = true;
        userTest.BypassWorkflow__c = true;
        
        insert userTest;
        
        System.runAs(userTest){
            
            String masterBookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Master_Booking').getRecordTypeId();
            
            list<opportunity> listMBs = new list<opportunity>();
            list<Account> listPersonAcc = new list<Account>();
            
            Account personAcc1 = new Account(LastName = 'test1', Email__pc = 'test1@asce.com');
            listPersonAcc.add(personAcc1);
            Account personAcc2 = new Account(LastName = 'test2', Email__pc = 'test2@asce.com');
            listPersonAcc.add(personAcc2);
           
            insert listPersonAcc;
                        
            for(integer i = 0; i < 5; i++){
                
                Opportunity masterBook = new Opportunity(Person_Account__c=personAcc1.id, Name = 'masterBookingTest'+i, StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today(),Departure_Date__c=Date.Today()+20);
                listMBs.add(masterBook);
            }
            
            for(integer i = 0; i < 5; i++){
                
                Opportunity masterBook2 = new Opportunity(Person_Account__c =personAcc2.Id,Name = 'masterBookingTest2'+i, StageName = 'Open', RecordTypeId = masterBookingRTId, CloseDate = Date.Today(),Departure_Date__c=Date.Today()+24);
                listMBs.add(masterBook2);
            }
            insert listMBs;
            
           
            test.startTest();
            map<String,String> mapAccId = new map<String,String>();
            mapAccId.put(personAcc1.ID,'Test class error');
            Batch_Account_BookingDates batchObj = new Batch_Account_BookingDates(mapAccId,0);
            DataBase.executeBatch(batchObj);
            batchObj = new Batch_Account_BookingDates(mapAccId,3);
            DataBase.executeBatch(batchObj);
            
             batchObj = new Batch_Account_BookingDates(null,0);
            DataBase.executeBatch(batchObj);
            test.stopTest();
            
        }
    }
    
}