force-app/main/default/objects/Opportunity/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120Y000000QklY</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Master Bookings</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Master_Booking.recordType-meta.xml
<RecordType>
    <fullName>Master_Booking</fullName>
    <active>true</active>
    <businessProcess>Master booking process</businessProcess>
    <label>Master Booking</label>
</RecordType>

force-app/main/default/objects/User/fields/BypassValidationRule__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP16_Opportunity_Test.cls
/*
* Description: Test Class for AP16_Opportunity 
* @author: TMA-EIL Cynthia Geagea
* @date: 18/11/2019
*/

@isTest
public class AP16_Opportunity_Test {
    
    @isTest
    public static void updateFirstBookDateTest(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User testUser = new User(Alias = 'systadm', Email='systadm@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='systadm@testorg.com');
        testUser.BypassValidationRule__c = true;
        insert testUser;
        
        system.runAs(testUser){
            
            String masterBookingRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Master_Booking').getRecordTypeId();
            
            list<Account> listPersonAcc = new list<Account>();
            
            Account personAcc1 = new Account(LastName = 'test1', Email__pc = 'test1@asce.com');
            listPersonAcc.add(personAcc1);
            Account personAcc2 = new Account(LastName = 'test2', Email__pc = 'test2@asce.com');
            listPersonAcc.add(personAcc2);
            
            insert listPersonAcc;
            
            list<Opportunity> listNewMasterBookings =  new list<Opportunity>();
            
            Opportunity book1 = new Opportunity(Name = 'MBooking1', CloseDate = date.today(), StageName = 'Open', Person_account__c = personAcc1.id, RecordTypeId = masterBookingRTId, Departure_Date__c = date.today());
            listNewMasterBookings.add(book1);
            
            Opportunity book2 = new Opportunity(Name = 'MBooking2', CloseDate = date.today(), StageName = 'Open', Person_account__c = personAcc1.id, RecordTypeId = masterBookingRTId, Departure_Date__c = date.today());
            listNewMasterBookings.add(book2);
            
            Test.startTest();
            
            insert listNewMasterBookings;
            
            book2.Person_account__c = personAcc2.Id;
            update listNewMasterBookings;
            
            Test.stopTest();
                
        }
    }

}