force-app/main/default/objects/Opportunity/fields/Guest_Account_1__c.field-meta.xml
<CustomField>
    <fullName>Guest_Account_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Account 1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings (Guest Account 1)</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trip_Context__c.field-meta.xml
<CustomField>
    <fullName>Trip_Context__c</fullName>
    <label>Trip Context</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <businessProcess>Booking process</businessProcess>
    <label>Booking</label>
</RecordType>

force-app/main/default/classes/OpportunityTriggerHandler_Test.cls
/** 
* Test class for the OpportunityTriggerHandler Apex Class
* @author  JKA
* @version 0.1
* @date 24/01/2020
*/

@isTest
private class OpportunityTriggerHandler_Test {
    
    public static testMethod void testOppTrH() {
        User testUser = TestDataFactory.createSingleUser(false);
        Insert testUser ;
        System.runAs(testUser) {
            List<Account> lstGuestAccounts = TestDataFactory.createGuestAccounts(1);
            insert lstGuestAccounts;
            List<Opportunity> lstBookings = TestDataFactory.createBusinessBookings(1, lstGuestAccounts);
            insert lstBookings;
            
            Opportunity booking = [SELECT Id, StageName, Trip_Context__c, Guest_Account_1__c
                                   FROM Opportunity
                                   WHERE Id = :lstBookings[0].Id
                                  ];
            booking.Guest_Account_1__c = null;
            Test.startTest();
            update booking;
            Account guestAccount = [SELECT Id,Customer_type__pc
                                    FROM Account
                                    WHERE Id = :lstGuestAccounts[0].Id
                                   ];
            delete booking;
            undelete booking;
            Test.stopTest();
        } 
    }
}