force-app/main/default/objects/Opportunity/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <label>Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trip_Context__c.field-meta.xml
<CustomField>
    <fullName>Trip_Context__c</fullName>
    <label>Trip Context</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Guest Account</label>
</RecordType>

force-app/main/default/objects/Stay__c/Stay__c.object-meta.xml
<CustomObject>
    <description>Junction object between booking and Person account (Account object)</description>
    <label>Stay</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Stay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stay__c/fields/Min_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Min_Arrival__c</fullName>
    <formula>Booking__r.Min_Arrival__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Min Arrival</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stay__c/fields/Trip_Context__c.field-meta.xml
<CustomField>
    <fullName>Trip_Context__c</fullName>
    <formula>Booking__r.Trip_Context__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trip Context</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP02_Opportunity_Test.cls
/**
* 
* @version 1.00 06/12/2017
* @author Jenny Jawhar
* @CodeCoverage 92%
*/
@isTest
public class AP02_Opportunity_Test {
    public static testMethod void updateDeleteBooking()
    {
        //insert person account
        Account PersonAccount =  Utils.CreatePersonAccount('Person', null);                      
        insert PersonAccount;
        //insert bookings
        list<Opportunity> listBookingToInsert = new list<Opportunity>();
        Opportunity opp1 = Utils.CreateBookingOpportunity('Booking1');                 
        opp1.StageName=Label.StatusChecked; 
        listBookingToInsert.add(opp1);
        Opportunity opp2 = Utils.CreateBookingOpportunity('Booking2');
        opp2.StageName=label.StatusChecked;
        listBookingToInsert.add(opp2);
        insert listBookingToInsert;
        list<Stay__c> listStayToInsert = new list<Stay__c>();
        Stay__c stay1 = Utils.CreateStay(PersonAccount.Id,opp1.Id);
        listStayToInsert.add(stay1);
        Stay__c stay2 = Utils.CreateStay(PersonAccount.Id,opp2.Id);
        listStayToInsert.add(stay2);
        insert listStayToInsert;
      
        opp1.Min_Arrival__c = date.Today();
        opp1.Trip_Context__c = label.BusinessCustomerType;
        update opp1;
        delete opp2;
    }
}