force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>Voucher</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Prestation_offerte__c.field-meta.xml
<CustomField>
    <fullName>Prestation_offerte__c</fullName>
    <label>Prestation offerte</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>6000</fullName>
                <label>Une nuit en chambre 1-2 personnes</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>Une nuit en chambre familiale</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>Une nuit en chambre 1-2 personnes avec petits déjeuners</label>
            </value>
            <value>
                <fullName>6003</fullName>
                <label>Une nuit en chambre familiale avec petits déjeuners</label>
            </value>
            <value>
                <fullName>6004</fullName>
                <label>Un petit déjeuner</label>
            </value>
            <value>
                <fullName>6005</fullName>
                <label>Deux petits déjeuners</label>
            </value>
            <value>
                <fullName>6006</fullName>
                <label>Trois petits déjeuners</label>
            </value>
            <value>
                <fullName>6007</fullName>
                <label>Quatre petits déjeuners</label>
            </value>
            <value>
                <fullName>60 euros</fullName>
                <label>Voucher 60 euros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>En attente</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Annulé(e)</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <label>Périmé(e)</label>
            </value>
            <value>
                <fullName>Used</fullName>
                <label>Consommé(e)</label>
            </value>
            <value>
                <fullName>Generated</fullName>
                <label>Emis</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LCC17_DashboardConsultOC.cls
/*
* Description: Controller class for LC17_DashboardConsultOC 
* @author: TMA-EI CG
* @date: 22/10/2020
* @Test class: LCC17_DashboardConsultOC_Test
* @Coverage: 100%
* @Lightning Components: LC17_DashboardConsultOC
*/

public without sharing class LCC17_DashboardConsultOC {
    
    @AuraEnabled
    public static ReturnedInfo GetRelatedVouchers(string mvId) {
        
        ReturnedInfo ret = new ReturnedInfo();
        
        ret.listRelatedVouchers = [select Id, Name, Code_OC__c, Statut__c,Tech_Statut__c, Prestation_offerte__c 
                               from Voucher__c
                               where Master_Voucher_OC__c =: mvId];
        
        return ret;
    }
    
    public class ReturnedInfo{
        
        @AuraEnabled public List<Voucher__c> listRelatedVouchers;
    }
    
}